### ISSUE TITLE
Double height buttons in keymap editor

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#108]
<img width="1442" alt="screen shot 2018-09-10 at 8 10 16 am" src="https://user-images.githubusercontent.com/22350787/45302681-2cf1aa80-b4d1-11e8-96e5-1cc771539d2d.png">

**Comment by rcoreilly** [comment]
hopefully fixed now?

**Comment by rcoreilly** [comment]
I can now replicate this -- only on my mac laptop retina display, not on my 2nd 4k external display!  That gives me a good lead on it..

**Comment by rohrlich** [comment]
On my 5k external they seem about 1.5 height
<img width="713" alt="screen shot 2018-09-10 at 7 08 07 pm" src="https://user-images.githubusercontent.com/22350787/45332322-17aa6980-b52d-11e8-95d9-7e6bc51c31ad.png">

**Comment by rcoreilly** [comment]
that was a biggie!  careful debugging is painful but useful..
