### ISSUE TITLE
Keymap set/edit vastly improved - a few usability issues

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#110]
• View Std only has title/prompt
• Keymap edit dialog should name the map being edited
• Sometimes hangs when choosing "overwrite" of keymap function - not sure about precipitating condition
• If I am adding a new keymapping and the key sequence is already being used and I click overwrite (and I'm sorted by key sequence) the row moves before I've had a chance to edit the function (i.e. change from nil) -- Best solution for "Add" is to raise dialog with single key mapping and add when the dialog is dismissed
• Solution above (separate dialog) would also address the problem of doing an "Add" when sorted by function. In that case the added keymapping is buried - you need to look for the "nil" button.

**Comment by rcoreilly** [comment]
not worth it..
