### ISSUE TITLE
Gide new project UI confusing

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#114]
• Not obvious that project is directory
• I created a new folder but then couldn't rename it
• Suggest a dialog that allows you to set path, name the project and likely choose a template (e.g. emergent StdLeabra)

**Comment by rohrlich** [comment]
Still confused about creating a new project. I've tried opening an empty directory, creating a new directory by extending the path, etc. Here are my results:
2018/09/17 21:03:14 gide.ProjPathParse: Cannot open at given path: "/Users/rohrlich/sandbox/C": Error: lstat /Users/rohrlich/sandbox/C: no such file or directory
2018/09/17 21:03:46 gi.FileView error: Path "/Users/rohrlich/sandbox/C": Error: lstat /Users/rohrlich/sandbox/C: no such file or directory
2018/09/17 21:03:52 gide.ProjPathParse: Cannot open at given path: "/Users/rohrlich/sandbox/C": Error: lstat /Users/rohrlich/sandbox/C: no such file or directory
2018/09/17 21:05:28 gide.ProjPathParse: Cannot open at given path: "/Users/rohrlich/sandbox/D": Error: lstat /Users/rohrlich/sandbox/D: no such file or directory

**Comment by rcoreilly** [comment]
fixing in gide, closing this ticket.
