### ISSUE TITLE
Missing menus from menubar when keymap editing is front

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#117]

**Comment by rcoreilly** [comment]
right now every window has its own menubar, and popup edits don't have any basis for creating one.  Probably need to figure out some kind of OS-specific setting for the window type that allows it to just inherit previous / main window menus.

**Comment by rcoreilly** [comment]
this actually got fixed -- if a window doesn't have a menu, it doesn't push one, so previous remains in effect..
