### ISSUE TITLE
Crash opening textview.go - threads

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#120]
Johns-Mac-Pro:~/go/src/github.com/goki/gi/examples/textview $ ./textview 
2018/09/17 08:58:30 KeyMap: key function is nil -- probably renamed, for key: Control+C
2018/09/17 08:58:30 KeyMap: key function is nil -- probably renamed, for key: Control+X
warning - KeyFunNil has no key mappingwarning - KeyFunNil has no key mappingfatal error: concurrent map read and map write

goroutine 11 [running]:
runtime.throw(0x4853774, 0x21)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc420595338 sp=0xc420595318 pc=0x402da11
runtime.mapaccess1_fast64(0x4723800, 0xc4204a4cc0, 0xc, 0x7)
	/usr/local/go/src/runtime/hashmap_fast.go:101 +0x197 fp=0xc420595360 sp=0xc420595338 pc=0x400dcc7
github.com/goki/gi.(*FontLib).Font(0x51d1000, 0xc4252dfad0, 0x7, 0xc, 0x0, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/font.go:739 +0x55a fp=0xc420595438 sp=0xc420595360 pc=0x42c99aa
github.com/goki/gi.(*FontStyle).OpenFont(0xc424fd3290, 0xc420198d64)
	/Users/rohrlich/go/src/github.com/goki/gi/font.go:357 +0xfd fp=0xc4205954c0 sp=0xc420595438 pc=0x42c81cd
github.com/goki/gi.(*TextRender).SetHTMLPre(0xc420157f00, 0xc424e26bab, 0x1f5, 0x1f5, 0xc422d6fb90, 0xc420198ce0, 0xc420198d64, 0xc42055c360)
	/Users/rohrlich/go/src/github.com/goki/gi/text.go:1405 +0x16a7 fp=0xc420595e90 sp=0xc4205954c0 pc=0x4308d07
github.com/goki/gi/giv.(*TextView).HiAllLines(0xc420198a00)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:448 +0x4fb fp=0xc420595fd8 sp=0xc420595e90 pc=0x45a7d4b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420595fe0 sp=0xc420595fd8 pc=0x4059871
created by github.com/goki/gi/giv.(*TextView).LayoutAllLines
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:505 +0x669

goroutine 1 [syscall, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver._Cfunc_startDriver()
	_cgo_gotypes.go:682 +0x41
github.com/goki/gi/oswin/driver/macdriver.startDriver()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:102 +0x3b
github.com/goki/gi/oswin/driver/macdriver.Main(0xc42019fe70)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/macdriver.go:27 +0x36
github.com/goki/gi/oswin/driver.main(0xc42019fe70)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver_darwin.go:20 +0x2b
github.com/goki/gi/oswin/driver.Main(0xc42019fe70)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver.go:27 +0x2b
github.com/goki/gi/gimain.Main(0x4890aa0)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:24 +0x5c
main.main()
	/Users/rohrlich/go/src/github.com/goki/gi/examples/textview/textview.go:22 +0x2d

goroutine 10 [runnable]:
github.com/goki/gi.(*StyledFields).ToDots(0xc4200ae910, 0x477bc80, 0xc420213138, 0xc42021336c)
	/Users/rohrlich/go/src/github.com/goki/gi/style.go:579 +0x100
github.com/goki/gi.(*Style).ToDots(0xc420213138)
	/Users/rohrlich/go/src/github.com/goki/gi/style.go:318 +0x51
github.com/goki/gi.(*Style).SetUnitContext(0xc420213138, 0xc4205a8000, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/style.go:291 +0x102
github.com/goki/gi.(*WidgetBase).Style2DWidget(0xc420213008)
	/Users/rohrlich/go/src/github.com/goki/gi/widget.go:163 +0x45a
github.com/goki/gi.(*Layout).StyleLayout(0xc420213008)
	/Users/rohrlich/go/src/github.com/goki/gi/layout.go:1711 +0x31
github.com/goki/gi.(*Layout).Style2D(0xc420213008)
	/Users/rohrlich/go/src/github.com/goki/gi/layout.go:1719 +0x2b
github.com/goki/gi.(*Node2DBase).Style2DTree.func1(0x49d8640, 0xc420213008, 0x3, 0x47dada0, 0xc4205a8a80, 0xb)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:517 +0x51
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc420213008, 0x3, 0x47dada0, 0xc4205a8a80, 0x48900b8, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:999 +0x6b
github.com/goki/ki.(*Node).FuncDownMeFirst.func1(0x49d8640, 0xc420213008, 0x3, 0x47dada0, 0xc4205a8a80, 0xc420212c00)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1004 +0x59
github.com/goki/ki.(*Node).FuncFields(0xc420212c00, 0x3, 0x47dada0, 0xc4205a8a80, 0xc422633460)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:963 +0xe8
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc420212c00, 0x3, 0x47dada0, 0xc4205a8a80, 0x48900b8, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1003 +0xee
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc4205a8e88, 0x2, 0x47dada0, 0xc4205a8a80, 0x48900b8, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x15c
github.com/goki/ki.(*Node).FuncDownMeFirst.func1(0x49d8640, 0xc4205a8e88, 0x1, 0x47dada0, 0xc4205a8a80, 0xc4205a8a80)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1004 +0x59
github.com/goki/ki.(*Node).FuncFields(0xc4205a8a80, 0x1, 0x47dada0, 0xc4205a8a80, 0xc4226335f0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:963 +0xe8
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc4205a8a80, 0x1, 0x47dada0, 0xc4205a8a80, 0x48900b8, 0x49f6e01)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1003 +0xee
github.com/goki/gi.(*Node2DBase).Style2DTree(0xc4205a8a80)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:512 +0x90
github.com/goki/gi.(*WidgetBase).ReRender2DTree(0xc4205a8a80)
	/Users/rohrlich/go/src/github.com/goki/gi/widget.go:387 +0x178
github.com/goki/gi.(*WidgetBase).FullReRenderIfNeeded(0xc4205a8a80, 0x42e3e75)
	/Users/rohrlich/go/src/github.com/goki/gi/widget.go:315 +0x98
github.com/goki/gi.(*SplitView).Render2D(0xc4205a8a80)
	/Users/rohrlich/go/src/github.com/goki/gi/splitview.go:290 +0x31
github.com/goki/gi.(*Layout).Render2DChildren(0xc42068e000)
	/Users/rohrlich/go/src/github.com/goki/gi/layout.go:1258 +0x1c1
github.com/goki/gi.(*Frame).Render2D(0xc42068e000)
	/Users/rohrlich/go/src/github.com/goki/gi/frame.go:149 +0xc1
github.com/goki/gi.(*Layout).Render2DChildren(0xc420458a00)
	/Users/rohrlich/go/src/github.com/goki/gi/layout.go:1258 +0x1c1
github.com/goki/gi.(*Layout).Render2D(0xc420458a00)
	/Users/rohrlich/go/src/github.com/goki/gi/layout.go:1796 +0xaf
github.com/goki/gi.(*Node2DBase).Render2DChildren(0xc4205a8000)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:628 +0x8e
github.com/goki/gi.(*Viewport2D).Render2D(0xc4205a8000)
	/Users/rohrlich/go/src/github.com/goki/gi/viewport2d.go:436 +0x6a
github.com/goki/gi.(*Node2DBase).Render2DTree(0xc4205a8000)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:589 +0x90
github.com/goki/gi.(*Node2DBase).FullRender2DTree(0xc4205a8000)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:481 +0x89
github.com/goki/gi.(*Viewport2D).FullRender2DTree(0xc4205a8000)
	/Users/rohrlich/go/src/github.com/goki/gi/viewport2d.go:373 +0x90
github.com/goki/gi.(*Window).FullReRender(0xc4201a2000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:592 +0x4f
github.com/goki/gi.(*Window).Resized(0xc4201a2000, 0x6d2, 0x4ed)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:452 +0x1a9
github.com/goki/gi.(*Window).EventLoop(0xc4201a2000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1004 +0x21ae
github.com/goki/gi.(*Window).StartEventLoop(0xc4201a2000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:521 +0x32
main.mainrun()
	/Users/rohrlich/go/src/github.com/goki/gi/examples/textview/textview.go:118 +0x15c6
main.main.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/examples/textview/textview.go:23 +0x20
github.com/goki/gi/gimain.Main.func1(0x49ac300, 0x51ac6c0)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:25 +0x24
github.com/goki/gi/oswin/driver/macdriver.driverStarted.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:172 +0x40
created by github.com/goki/gi/oswin/driver/macdriver.driverStarted
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:171 +0x60

goroutine 23 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc4204c8900, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:220 +0x223
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:162 +0xfa

goroutine 12 [runnable]:
strings.lastIndexFunc(0x480cf09, 0x7, 0x48910c0, 0x4891000, 0x0)
	/usr/local/go/src/strings/strings.go:733 +0xb1
strings.TrimRightFunc(0x480cf09, 0x7, 0x48910c0, 0x480cf09, 0x7)
	/usr/local/go/src/strings/strings.go:690 +0x48
strings.TrimFunc(0x480cf09, 0x7, 0x48910c0, 0x1, 0x1)
	/usr/local/go/src/strings/strings.go:703 +0x61
strings.TrimSpace(0x480cf09, 0x7, 0x4802fe3, 0x1)
	/usr/local/go/src/strings/strings.go:814 +0x41
github.com/goki/gi.FontFaceName(0x480cf09, 0x7, 0x0, 0x0, 0x1000000000004, 0x4ae0)
	/Users/rohrlich/go/src/github.com/goki/gi/font.go:253 +0x7ea
github.com/goki/gi.(*FontStyle).FaceNm(0xc422d0dc20, 0xc420516400, 0x40d9879)
	/Users/rohrlich/go/src/github.com/goki/gi/font.go:240 +0x4d
github.com/goki/gi.(*FontStyle).OpenFont(0xc422d0dc20, 0xc420680364)
	/Users/rohrlich/go/src/github.com/goki/gi/font.go:348 +0x35
github.com/goki/gi.(*TextRender).SetHTMLPre(0xc42015a3c0, 0xc42510789e, 0xf0, 0xf0, 0xc422d0dc20, 0xc4206802e0, 0xc420680364, 0xc420b440c0)
	/Users/rohrlich/go/src/github.com/goki/gi/text.go:1273 +0x21c
github.com/goki/gi/giv.(*TextView).HiAllLines(0xc420680000)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:448 +0x4fb
created by github.com/goki/gi/giv.(*TextView).LayoutAllLines
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:505 +0x669

goroutine 13 [semacquire]:
sync.runtime_SemacquireMutex(0xc420198fb4, 0xc4209d6e00)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420198fb0)
	/usr/local/go/src/sync/mutex.go:134 +0x108
github.com/goki/gi/giv.(*TextView).HiAllLines(0xc420198a00)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:438 +0x2bd
created by github.com/goki/gi/giv.(*TextView).LayoutAllLines
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:505 +0x669

goroutine 14 [semacquire]:
sync.runtime_SemacquireMutex(0xc4206805b4, 0xc422309e00)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc4206805b0)
	/usr/local/go/src/sync/mutex.go:134 +0x108
github.com/goki/gi/giv.(*TextView).HiAllLines(0xc420680000)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:438 +0x2bd
created by github.com/goki/gi/giv.(*TextView).LayoutAllLines
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:505 +0x669

goroutine 15 [semacquire]:
sync.runtime_SemacquireMutex(0xc420198fb4, 0xc422305e00)
	/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420198fb0)
	/usr/local/go/src/sync/mutex.go:134 +0x108
github.com/goki/gi/giv.(*TextView).HiAllLines(0xc420198a00)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:438 +0x2bd
created by github.com/goki/gi/giv.(*TextView).LayoutAllLines
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:505 +0x669

goroutine 16 [runnable]:
github.com/dlclark/regexp2/syntax.(*BmPrefix).IsMatch(0xc420a86070, 0xc424ece76c, 0x16c, 0x225, 0x0, 0x0, 0x16c, 0x43ba500)
	/Users/rohrlich/go/src/github.com/dlclark/regexp2/syntax/prefix.go:747 +0x115
github.com/dlclark/regexp2.(*runner).findFirstChar(0xc420524800, 0x1)
	/Users/rohrlich/go/src/github.com/dlclark/regexp2/runner.go:1287 +0x137
github.com/dlclark/regexp2.(*runner).scan(0xc420524800, 0xc424ece76c, 0x16c, 0x225, 0x0, 0x0, 0x7fffffffffffffff, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/dlclark/regexp2/runner.go:130 +0x12a
github.com/dlclark/regexp2.(*Regexp).run(0xc42050c500, 0x0, 0xffffffffffffffff, 0xc424ece76c, 0x16c, 0x225, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/dlclark/regexp2/runner.go:91 +0xf2
github.com/dlclark/regexp2.(*Regexp).FindRunesMatch(0xc42050c500, 0xc424ece76c, 0x16c, 0x225, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/dlclark/regexp2/regexp.go:163 +0x57
github.com/alecthomas/chroma.matchRules(0xc424ece76c, 0x16c, 0x225, 0xc42031ba00, 0x1a, 0x20, 0xc4258183f0, 0xc4203f98b0, 0xc4258183e0, 0x1, ...)
	/Users/rohrlich/go/src/github.com/alecthomas/chroma/regexp.go:399 +0x9a
github.com/alecthomas/chroma.(*LexerState).Iterator(0xc424eee000, 0xc4258207e0)
	/Users/rohrlich/go/src/github.com/alecthomas/chroma/regexp.go:270 +0x343
github.com/alecthomas/chroma.(*LexerState).Iterator-fm(0xc4258207e0)
	/Users/rohrlich/go/src/github.com/alecthomas/chroma/regexp.go:394 +0x2a
github.com/alecthomas/chroma.(*coalescer).Tokenise.func1(0xc4258207a0)
	/Users/rohrlich/go/src/github.com/alecthomas/chroma/coalesce.go:15 +0x3b
github.com/alecthomas/chroma.Iterator.Tokens(0xc424ef4000, 0x488ff60, 0xc424ec5eb8, 0x1347)
	/Users/rohrlich/go/src/github.com/alecthomas/chroma/iterator.go:13 +0x5f
github.com/alecthomas/chroma/formatters/html.(*Formatter).Format(0xc420aa1720, 0x4983540, 0xc4201a0070, 0xc42027e520, 0xc424ef4000, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/alecthomas/chroma/formatters/html/html.go:95 +0x67
github.com/goki/gi/giv.(*TextView).HiAllLines(0xc420680000)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:426 +0x11e
created by github.com/goki/gi/giv.(*TextView).LayoutAllLines
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:505 +0x669

**Comment by rohrlich** [comment]
To be clear I was running textview.go and opening textview.go but you can crash opening other files. Here I ran textview.go and was opening textfield.go. The crash doesn't happen every time.

Johns-Mac-Pro:~/go/src/github.com/goki/gi/examples/textview $ ./textview 
2018/09/17 09:04:27 KeyMap: key function is nil -- probably renamed, for key: Control+X
2018/09/17 09:04:27 KeyMap: key function is nil -- probably renamed, for key: Control+C
warning - KeyFunNil has no key mappingwarning - KeyFunNil has no key mappingJohns-Mac-Pro:~/go/src/github.com/goki/gi/examples/textview $ ./textview 
2018/09/17 09:04:40 KeyMap: key function is nil -- probably renamed, for key: Control+X
2018/09/17 09:04:40 KeyMap: key function is nil -- probably renamed, for key: Control+C
warning - KeyFunNil has no key mappingwarning - KeyFunNil has no key mappingpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x42c8524]

goroutine 131 [running]:
github.com/goki/gi.(*FontStyle).ComputeMetrics(0xc42018ec58, 0xc42018ed64)
	/Users/rohrlich/go/src/github.com/goki/gi/font.go:384 +0xe4
github.com/goki/gi.(*FontStyle).OpenFont(0xc42018ec58, 0xc42018ed64)
	/Users/rohrlich/go/src/github.com/goki/gi/font.go:367 +0x18e
github.com/goki/gi.(*TextRender).LayoutStdLR(0xc420a99b40, 0xc42018ece0, 0xc42018ec58, 0xc42018ed64, 0x4498300044484d00, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/text.go:1778 +0xc2
github.com/goki/gi/giv.(*TextView).HiAllLines(0xc42018ea00)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:449 +0x321
created by github.com/goki/gi/giv.(*TextView).LayoutAllLines
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:505 +0x669
Johns-Mac-Pro:~/go/src/github.com/goki/gi/examples/textview $

**Comment by rcoreilly** [comment]
this is from doing highlighting in a separate task.  Was working reliably for me, after I thought I caught all the crash points.. :)  anyway, other fixes mean this happens much less often now so I'll revert this back to non-parallel which will definitely be more robust..
