### ISSUE TITLE
Completion should be case insensitive

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#123]
Passing ignore-case to gocode but it isn't working - likely something I'm doing wrong or not doing

**Comment by rohrlich** [comment]
need to up the priority as this is a problem for the directory args completion case

**Comment by rohrlich** [comment]
I've commented to gocode issues as there is an issue regarding case insensitive search but it isn't clear if it was implemented or not.

**Comment by rohrlich** [comment]
I could make completion for non-code fields like the command directory variable case insensitive even if code completion isn't case insensitive but that might be more confusing. Thoughts?

**Comment by rcoreilly** [comment]
yep I like that paradigm

**Comment by rcoreilly** [comment]
ps. it is how interactive-search works already

**Comment by rohrlich** [comment]
Now implemented
