### ISSUE TITLE
gide: crash double clicking on file in navigator

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#127]
Pretty sure I had just double-clicked to open file into editor

runtime.startpanic at panic.go:588
runtime.gopanic at panic.go:544
runtime.panicdottypeE at iface.go:252
runtime.panicdottypeI at iface.go:262
github.com/goki/gide.(*Gide).ConfigSplitView.func1 at gide.go:1160
github.com/goki/ki.(*Signal).Emit at signal.go:157
github.com/goki/gi/giv.(*TreeView).UnselectAll at treeview.go:425
github.com/goki/gi/giv.(*TreeView).SelectAction at treeview.go:509
github.com/goki/gi/giv.(*TreeView).TreeViewEvents.func5 at treeview.go:1342
github.com/goki/gi.(*WinEventRecv).Call at window.go:1330
github.com/goki/gi.(*Window).SendEventSignal at window.go:1450
github.com/goki/gi.(*Window).EventLoop at window.go:1204
runtime.goexit at asm_amd64.s:2361

**Comment by rcoreilly** [comment]
probably fixed -- reopen if happens again.  need the specific panic to see what the problem was.
