### ISSUE TITLE
A few completion issues

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#130]
* textview: if ISearchMode = true, don't run completer
* also in TextViewOpts, add an overall opt for running completer or not -- I just added a similar option to gide prefs to set this pref..
* fileview: as mentioned today, if filename already there, then overwrite instead of adding.

**Comment by rcoreilly** [comment]
actually I just the options stuff and isearchmode stuff right now.

**Comment by rohrlich** [comment]
I made a small behavior change. If ISearchMode is true - no completion

If completion pref is false but you issue keyFunComplete you get completion - this allows you to always have completion if you want it for specific cases rather than generally

**Comment by rohrlich** [comment]
I finally figured out that there the project also has settings for wrap/line_no/completion and that is why completion was off.
