### ISSUE TITLE
Prefs files should be created from defaults if not found

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#132]
I deleted my gogi prefs and they weren't recreated. Grabbed a copy from another machine.

**Comment by rcoreilly** [comment]
if you don't have a prefs file then by definition you are running on defaults!  perfectly fine to do so.

**Comment by rohrlich** [comment]
Fair enough but it isn't getting created when I change my prefs in some way and I've tried a few.

**Comment by rcoreilly** [comment]
*gide* prefs are in gide dir. gogi prefs are in gogi dir.. ~/Library/gide or GoGi

**Comment by rcoreilly** [comment]
but earlier gide was still in gogi so you might have had something there..

**Comment by rohrlich** [comment]
Yes, I did and I didn't see the "gide" directory. Thanks!
