### ISSUE TITLE
fileview completer not showing keyfun.go in gide

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#135]
![screen shot 2018-09-19 at 12 43 58 am](https://user-images.githubusercontent.com/9605819/45797134-2dbcd600-bc61-11e8-9eb3-35f557e3ade7.png)

**Comment by rcoreilly** [comment]
100% replicable for me

**Comment by rohrlich** [comment]
The list of possible completions wasn't sorted before passing to MatchSeed so if your fileview was sorted by anything other than name it could fail. I moved the sort code into MatchSeed so callers don't need to. Thanks for finding this.
