### ISSUE TITLE
SVG App

### ISSUE THREAD

**Issue by ghost** [goki/gi#136]
Am calling this an App since the intent is a Inkscape like experience.

What follows is a complete spec ( if you will ) to get it all in one place for now.

**Spec:**
One of my long-term life goals is have a decent replacement for InkScape.
Mac, Windows and Linux.

_Current status:_
- All the svg rendering is in https://github.com/goki/gi/tree/master/svg
- Sprites and a transparent overlay available for rendering edit controls (control points, rubber bands, etc) on top of the underlying drawing, without affecting anything else. 
- The cursor in TextField is a sprite, and drag-n-drop uses the overlay, so you can look at those for examples..

_High Level approach:_
- Get basic Window and Canvas working such that screen DPI and horizontal / vertical scrolling work ok on all OS's first. 

- User editing via Property Editor: Get the 2D SVG rendering working, where the user can edit the "widgets" in the IDE by adding and removing nodes and changing the properties of elements.

- User editing via Canvas. Get an event loop going so that users can use mouse / touch to move, scale, rotate elements, such that the properties in the bullet point above
are changed.

- Have it savable and loadable from disk.

- Have it parametric, such that changing a property results in lots of other elements adjusting as well. A simple example is Group scaling where you select many objects and they scale together.
The IDE / Canvas can be used to create the links between objects to be parametric.
Standard Transformation like scale, rotate, initially.
Custom Transformations used form the Data Flow system. 
The parametric relationship should be described in the File format so that its not lost.

- Make a DataFlow system. Have the Parametric function customisable using the SVG system to build a Data FLow system. This allows users to setup complex transformation flows and run them in the GUI. Its almost a separate project.

**Comment by rcoreilly** [comment]
Everything except the last point is now in place (more-or-less) in the https://github.com/goki/grid app..

If this is still relevant, it would be more appropriate as a discussions topic:

* Make a DataFlow system. Have the Parametric function customisable using the SVG system to build a Data FLow system. This allows users to setup complex transformation flows and run them in the GUI. Its almost a separate project.
