### ISSUE TITLE
Can't update Label text inside Event ( button.ButtonSig.Connect )

### ISSUE THREAD

**Issue by benammann** [goki/gi#142]
Hi, im trying to simply update the label's text to `Updated Text` when clicking the given button. But nothing happens.

Is this a bug or am i missing something ?

This is my codebase:

```package main

import (
	"fmt"
	"github.com/goki/gi"
	"github.com/goki/gi/gimain"
	"github.com/goki/gi/oswin"
	"github.com/goki/ki"
)

func main() {
	gimain.Main(func() {
		mainrun()
	})
}

func mainrun() {
	width := 1024
	height := 768
	win := gi.NewWindow2D("gogi-basic", "Basic Test Window", width, height, true)

	vp := win.WinViewport2D()
	updt := vp.UpdateStart()

	mfr := win.SetMainFrame()

	rlay := mfr.AddNewChild(gi.KiT_Layout, "rowlay").(*gi.Layout)
	rlay.Lay = gi.LayoutHoriz
	rlay.SetProp("text-align", "center")

	rec := ki.Node{}
	rec.InitName(&rec, "rec")

	button1 := rlay.AddNewChild(gi.KiT_Button, "button1").(*gi.Button)
	button1.Text = "Update Label Text"

	displayLabel := rlay.AddNewChild(gi.KiT_Label, "label1").(*gi.Label)
	displayLabel.Text = "init Text"


	button1.ButtonSig.Connect(rec.This, func(recv, send ki.Ki, sig int64, data interface{}) {
		if sig == int64(gi.ButtonClicked) {
			displayLabel.SetText("Updated Text")
			fmt.Println("Updated label Text")
		}
	})

	appnm := oswin.TheApp.Name()
	mmen := win.MainMenu
	mmen.ConfigMenus([]string{appnm, "Edit", "Window"})

	amen := win.MainMenu.KnownChildByName(appnm, 0).(*gi.Action)
	amen.Menu = make(gi.Menu, 0, 10)
	amen.Menu.AddAppMenu(win)

	emen := win.MainMenu.KnownChildByName("Edit", 1).(*gi.Action)
	emen.Menu = make(gi.Menu, 0, 10)
	emen.Menu.AddCopyCutPaste(win)

	win.OSWin.SetCloseCleanFunc(func(w oswin.Window) {
		go oswin.TheApp.Quit()
	})

	win.MainMenuUpdated()

	vp.UpdateEndNoSig(updt)

	win.StartEventLoop()
}```

Cheers

**Comment by rcoreilly** [comment]
use SetTextAction instead of SetText -- most "Set" methods have an "Action" version that triggers updating and sending of signals. In this case, all it does is call UpdateSig on the label which is the general way to trigger updating of something.

**Comment by rcoreilly** [comment]
actually now that I look at this again, SetText should definitely be wrapped in UpdateStart / UpdateEnd and you should not need to call the Action version -- the Action version is only for sending signals, not for triggering updates.  I'm fixing this right now, so don't change your code!

**Comment by benammann** [comment]
Thank you @rcoreilly

**Comment by benammann** [comment]
I just tried to use `SetTextAction(txt)`, it updates the label but does not delete it's old state, the same behavior happens when using 

`
label.SetText(txt)
label.UpdateSig()
`

I tried to find the bug, but unfortunately im not that familiar with the codebase.

**Comment by rcoreilly** [comment]
add:	displayLabel.Redrawable = true

labels are transparent by default and write over top of themselves.  this flag sets them to draw a background to overwrite..

**Comment by rcoreilly** [comment]
assuming all good? reopen if not.
