### ISSUE TITLE
Edit Cmds: View Std should list in original window not open a second

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#147]
- Clicking the Edit Cmds button opens the Cmds editing window
- Then, clicking the View Std button shows a small dialog and clicking ok to that brings up another Cmds editing window that is populated with the std commands.

The first click of View Std should just populate the window. No need for small "Ok" dialog or second edit window.

**Comment by rohrlich** [comment]
Actually it would be better to get rid of "view std" altogether and "view std" displays the "builtin" cmds as well as the ones I've added so in what way is it standard?

**Comment by rohrlich** [comment]
And it would be nice if the Edit Cmds list of commands had an Edit... entry much like Splits does, for convenience.

**Comment by rcoreilly** [comment]
Comment above should be "Exec Cmds" has "Edit..." as an option.  should be doable.

about View Std: the two diff list of cmds are kept separate, so we can keep easily adding to the std commands list without user having stale list.  so you only add new ones that are not in std list.  so it is two diff lists.  anyway, got rid of the annoying window.

**Comment by rohrlich** [comment]
Good to see that extra dialog gone.  My understanding now is that the Std list is not user editable and that user defined commands go in a separate list presumably called something like "User Defined Commands" but the Std list says you can Duplicate and Add so it is confusing. Suggest either one list with Std ones not deletable or editable or 2 lists in one window (my preference) with duplicates and adds going to the second user list. The list on left would be Std (non-editable) and on right User (editable). Also as it is now both windows are labeled Gide Commands and though both entries are in the Window Menu you can only get to one via menu because it is always found first.
![screen shot 2018-10-17 at 7 48 10 pm](https://user-images.githubusercontent.com/22350787/47126784-62638380-d247-11e8-9c20-510cd298fbbd.png)

**Comment by rcoreilly** [comment]
for now I will fix that prompt.. :)  doing 2 lists in one window etc is not supported easily with existing views so not going to do that anytime soon -- lots more urgent issues.

**Comment by rcoreilly** [comment]
not relevant enough to keep on issues -- trying to keep this list small and useful for what we will actually fix..
