### ISSUE TITLE
Crash clicking edit cmds

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#148]
Johns-Mac-Pro:~/go/src/github.com/goki/gide/cmd/gide $ ./gide
fatal error: concurrent map read and map write

goroutine 13 [running]:
runtime.throw(0x4909897, 0x21)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0008f8518 sp=0xc0008f84e8 pc=0x402d8f2
runtime.mapaccess2_faststr(0x47bf5e0, 0xc00009ac90, 0xc004b9df60, 0x8, 0x487ede0, 0x4aaa260)
	/usr/local/go/src/runtime/map_faststr.go:110 +0x458 fp=0xc0008f8588 sp=0xc0008f8518 pc=0x4014a58
github.com/goki/ki/kit.(*TypeRegistry).PropsByName(...)
	/Users/rohrlich/go/src/github.com/goki/ki/kit/types.go:137
github.com/goki/ki/kit.(*TypeRegistry).Properties(0x557e980, 0x4aaa260, 0x4824e40, 0xc004b9df01, 0x4824e40)
	/Users/rohrlich/go/src/github.com/goki/ki/kit/types.go:153 +0x99 fp=0xc0008f85e0 sp=0xc0008f8588 pc=0x4119f09
github.com/goki/ki.(*Node).Fields(0xc005e72e00, 0xc005e72e00, 0x16, 0xc005e72e00)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:908 +0x55 fp=0xc0008f8688 sp=0xc0008f85e0 pc=0x4162555
github.com/goki/ki.(*Node).FuncFields(0xc005e72e00, 0x3, 0x0, 0x0, 0xc0008f8740)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:960 +0xcb fp=0xc0008f86f8 sp=0xc0008f8688 pc=0x4162e2b
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc005e72e00, 0x3, 0x0, 0x0, 0x4949890, 0x4164300)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1003 +0xf3 fp=0xc0008f8770 sp=0xc0008f86f8 pc=0x41633c3
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc005e70000, 0x2, 0x0, 0x0, 0x4949890, 0x400e200)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175 fp=0xc0008f87e8 sp=0xc0008f8770 pc=0x4163445
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc005e6c480, 0x1, 0x0, 0x0, 0x4949890, 0x80)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175 fp=0xc0008f8860 sp=0xc0008f87e8 pc=0x4163445
github.com/goki/ki.(*Node).DisconnectAll(0xc005e6c480)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1197 +0x48 fp=0xc0008f88a0 sp=0xc0008f8860 pc=0x4164398
github.com/goki/ki.(*Node).Destroy(0xc005e6c480)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:720 +0xa7 fp=0xc0008f88e8 sp=0xc0008f88a0 pc=0x4161607
github.com/goki/ki.(*Deleted).DestroyDeleted(0x557f760)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1650 +0x10f fp=0xc0008f8960 sp=0xc0008f88e8 pc=0x4167d9f
github.com/goki/ki.(*Node).Destroy(0xc006497d88)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:727 +0xf5 fp=0xc0008f89a8 sp=0xc0008f8960 pc=0x4161655
github.com/goki/ki.(*Node).Destroy.func1(0x4ad61a0, 0xc006497d88, 0x0, 0x0, 0x0, 0x4164398)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:724 +0x34 fp=0xc0008f89c0 sp=0xc0008f89a8 pc=0x4173834
github.com/goki/ki.(*Node).FuncFields(0xc006497980, 0x0, 0x0, 0x0, 0x4949880)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:963 +0x13a fp=0xc0008f8a30 sp=0xc0008f89c0 pc=0x4162e9a
github.com/goki/ki.(*Node).Destroy(0xc006497980)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:723 +0xe5 fp=0xc0008f8a78 sp=0xc0008f8a30 pc=0x4161645
github.com/goki/ki.(*Deleted).DestroyDeleted(0x557f760)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1650 +0x10f fp=0xc0008f8af0 sp=0xc0008f8a78 pc=0x4167d9f
github.com/goki/ki.(*Node).CopyFrom(0xc008633b18, 0x5dce4e0, 0xc00064ab18, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1271 +0x4cc fp=0xc0008f8c68 sp=0xc0008f8af0 pc=0x4164e7c
github.com/goki/ki.(*Node).CopyFieldsFrom(0xc008633000, 0x488f940, 0xc008633000, 0x488f940, 0xc00064a000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1340 +0x783 fp=0xc0008f8e40 sp=0xc0008f8c68 pc=0x4165ca3
github.com/goki/ki.(*Node).CopyFieldsFrom(0xc008633000, 0x4890a20, 0xc008633000, 0x4890a20, 0xc00064a000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1333 +0x7cd fp=0xc0008f9018 sp=0xc0008f8e40 pc=0x4165ced
github.com/goki/ki.(*Node).CopyFromRaw(0xc008633000, 0x4ae49a0, 0xc00064a000, 0x1, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1359 +0x114 fp=0xc0008f9088 sp=0xc0008f9018 pc=0x4165f24
github.com/goki/ki.(*Node).CopyFrom(0xc008633000, 0x4ae49a0, 0xc00064a000, 0x47906a0, 0x55a1640)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1270 +0x4a5 fp=0xc0008f9200 sp=0xc0008f9088 pc=0x4164e55
github.com/goki/gi/svg.(*Icon).CopyFromIcon(0xc008633000, 0xc00064a000)
	/Users/rohrlich/go/src/github.com/goki/gi/svg/icons.go:57 +0x48 fp=0xc0008f9238 sp=0xc0008f9200 pc=0x46b0b08
github.com/goki/gi/svg.(*IconMgr).SetIcon(0x55a0c40, 0xc008493b00, 0x48b9db7, 0x4, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/svg/icons.go:165 +0xe0 fp=0xc0008f9288 sp=0xc0008f9238 pc=0x46b13a0
github.com/goki/gi.(*Icon).SetIcon(0xc008493b00, 0x48b9db7, 0x4, 0xc0081bf020, 0x1, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/icon.go:68 +0x85 fp=0xc0008f92c8 sp=0xc0008f9288 pc=0x42f6415
github.com/goki/gi.(*PartsWidgetBase).ConfigPartsSetIconLabel(0xc008628000, 0x48b9db7, 0x4, 0x0, 0x0, 0x0, 0xffffffffffffffff)
	/Users/rohrlich/go/src/github.com/goki/gi/widget.go:832 +0x93 fp=0xc0008f9318 sp=0xc0008f92c8 pc=0x43453e3
github.com/goki/gi.(*Action).ConfigPartsButton(0xc008628000)
	/Users/rohrlich/go/src/github.com/goki/gi/action.go:227 +0x2a4 fp=0xc0008f93d8 sp=0xc0008f9318 pc=0x42d1a34
github.com/goki/gi.(*Action).ConfigParts(0xc008628000)
	/Users/rohrlich/go/src/github.com/goki/gi/action.go:285 +0x17f fp=0xc0008f93f0 sp=0xc0008f93d8 pc=0x42d25ff
github.com/goki/gi.(*ButtonBase).SetIcon(0xc008628000, 0x48b9db7, 0x4)
	/Users/rohrlich/go/src/github.com/goki/gi/buttons.go:197 +0xd6 fp=0xc0008f9430 sp=0xc0008f93f0 pc=0x42d5c16
github.com/goki/gi/giv.(*TableView).ConfigSliceGridRows(0xc0026c6600)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/tableview.go:523 +0xbd7 fp=0xc0008f9780 sp=0xc0008f9430 pc=0x45e0be7
github.com/goki/gi/giv.(*TableView).ConfigSliceGrid(0xc0026c6600, 0xc0026c0001)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/tableview.go:418 +0x15d1 fp=0xc0008f9af8 sp=0xc0008f9780 pc=0x45df3b1
github.com/goki/gi/giv.(*TableView).UpdateFromSlice(0xc0026c6600)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/tableview.go:160 +0x5a fp=0xc0008f9b20 sp=0xc0008f9af8 pc=0x45dcf7a
github.com/goki/gi/giv.(*TableView).Style2D(0xc0026c6600)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/tableview.go:714 +0x7b fp=0xc0008f9b40 sp=0xc0008f9b20 pc=0x45e284b
github.com/goki/gi.(*Node2DBase).Style2DTree.func1(0x4ae2560, 0xc0026c6600, 0x3, 0x488b720, 0xc002335500, 0xc005f25001)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:519 +0x51 fp=0xc0008f9b78 sp=0xc0008f9b40 pc=0x43593b1
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0026c6600, 0x3, 0x488b720, 0xc002335500, 0x4948fd8, 0xc005f24100)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:999 +0x6b fp=0xc0008f9bf0 sp=0xc0008f9b78 pc=0x416333b
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc005f24f00, 0x3, 0x488b720, 0xc002335500, 0x4948fd8, 0xc002335600)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175 fp=0xc0008f9c68 sp=0xc0008f9bf0 pc=0x4163445
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc005f24000, 0x2, 0x488b720, 0xc002335500, 0x4948fd8, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175 fp=0xc0008f9ce0 sp=0xc0008f9c68 pc=0x4163445
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc002335500, 0x1, 0x488b720, 0xc002335500, 0x4948fd8, 0x1)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175 fp=0xc0008f9d58 sp=0xc0008f9ce0 pc=0x4163445
github.com/goki/gi.(*Node2DBase).Style2DTree(0xc002335500)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:514 +0x8e fp=0xc0008f9da0 sp=0xc0008f9d58 pc=0x430965e
github.com/goki/gi.(*Node2DBase).FullRender2DTree(0xc002335500)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:480 +0x56 fp=0xc0008f9dc8 sp=0xc0008f9da0 pc=0x43094a6
github.com/goki/gi.(*Viewport2D).FullRender2DTree(0xc002335500)
	/Users/rohrlich/go/src/github.com/goki/gi/viewport2d.go:374 +0x91 fp=0xc0008f9e50 sp=0xc0008f9dc8 pc=0x433d871
github.com/goki/gi.(*Window).FullReRender(0xc002280a00)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:603 +0x4f fp=0xc0008f9e80 sp=0xc0008f9e50 pc=0x434867f
github.com/goki/gi.(*Window).EventLoop(0xc002280a00)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1244 +0x77d fp=0xc0008f9fd8 sp=0xc0008f9e80 pc=0x434ba5d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0008f9fe0 sp=0xc0008f9fd8 pc=0x405b091
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:542 +0x66

goroutine 1 [syscall, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver._Cfunc_startDriver()
	_cgo_gotypes.go:688 +0x41
github.com/goki/gi/oswin/driver/macdriver.startDriver()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:102 +0x3b
github.com/goki/gi/oswin/driver/macdriver.Main(0xc000273e10)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/macdriver.go:27 +0x35
github.com/goki/gi/oswin/driver.main(0xc000273e10)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver_darwin.go:20 +0x2b
github.com/goki/gi/oswin/driver.Main(0xc000273e10)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver.go:27 +0x2b
github.com/goki/gi/gimain.Main(0x4949d30)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:24 +0x57
main.main()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:20 +0x2d

goroutine 8 [semacquire]:
sync.runtime_Semacquire(0x55a0c98)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0x55a0c90)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
main.mainrun()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:81 +0x1c2
main.main.func1()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:21 +0x20
github.com/goki/gi/gimain.Main.func1(0x4aa92c0, 0x555aa20)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:25 +0x24
github.com/goki/gi/oswin/driver/macdriver.driverStarted.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:185 +0x40
created by github.com/goki/gi/oswin/driver/macdriver.driverStarted
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:184 +0x5f

goroutine 50 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc0004ca780, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:233 +0x220
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:175 +0xe8

goroutine 9 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0004ca820, 0x100000210)
	/usr/local/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc0004ca810)
	/usr/local/go/src/sync/cond.go:56 +0x92
github.com/goki/gi/oswin/driver/internal/event.(*Deque).NextEvent(0xc0004ca808, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/internal/event/event.go:55 +0x77
github.com/goki/gi/oswin/driver/macdriver.(*windowImpl).NextEvent(0xc0004ca780, 0xb0c009303, 0x5580e20)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/window.go:104 +0x33
github.com/goki/gi.(*Window).EventLoop(0xc0005e4500)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:987 +0x1b5
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:542 +0x66

goroutine 83 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc0004eec00, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:233 +0x220
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:175 +0xe8

goroutine 84 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0004eeca0, 0x100000083)
	/usr/local/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc0004eec90)
	/usr/local/go/src/sync/cond.go:56 +0x92
github.com/goki/gi/oswin/driver/internal/event.(*Deque).NextEvent(0xc0004eec88, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/internal/event/event.go:55 +0x77
github.com/goki/gi/oswin/driver/macdriver.(*windowImpl).NextEvent(0xc0004eec00, 0xb8cbbf4a5, 0x5580e20)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/window.go:104 +0x33
github.com/goki/gi.(*Window).EventLoop(0xc002721400)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:987 +0x1b5
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:542 +0x66

goroutine 11 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc0004cb800, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:233 +0x220
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:175 +0xe8

goroutine 85 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0004cb8a0, 0x10000003d)
	/usr/local/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc0004cb890)
	/usr/local/go/src/sync/cond.go:56 +0x92
github.com/goki/gi/oswin/driver/internal/event.(*Deque).NextEvent(0xc0004cb888, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/internal/event/event.go:55 +0x77
github.com/goki/gi/oswin/driver/macdriver.(*windowImpl).NextEvent(0xc0004cb800, 0xc520ef7ec, 0x5580e20)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/window.go:104 +0x33
github.com/goki/gi.(*Window).EventLoop(0xc004b1e000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:987 +0x1b5
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:542 +0x66

goroutine 41 [runnable]:
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0022bcc00, 0x3, 0x0, 0x0, 0x4949890, 0x4164300)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:998 +0x1b0
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0025a5900, 0x3, 0x0, 0x0, 0x4949890, 0x4164300)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0022b6000, 0x2, 0x0, 0x0, 0x4949890, 0xc0022b9900)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0022b9900, 0x1, 0x0, 0x0, 0x4949890, 0x80)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1008 +0x175
github.com/goki/ki.(*Node).DisconnectAll(0xc0022b9900)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1197 +0x48
github.com/goki/ki.(*Node).Destroy(0xc0022b9900)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:720 +0xa7
github.com/goki/gi.(*Window).EventLoop(0xc0022b9900)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1381 +0x7a5
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:542 +0x66

goroutine 12 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc0004ef500, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:233 +0x220
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:175 +0xe8

goroutine 14 [chan receive]:
github.com/goki/gi.TextFieldBlink()
	/Users/rohrlich/go/src/github.com/goki/gi/textfield.go:675 +0x46
created by github.com/goki/gi.(*TextField).StartCursor
	/Users/rohrlich/go/src/github.com/goki/gi/textfield.go:709 +0xf1
Johns-Mac-Pro:~/go/src/github.com/goki/gide/cmd/gide $

**Comment by rcoreilly** [comment]
types map needs a mutex!  should be fixed now -- reopen if you get it again..
