### ISSUE TITLE
Completion: Inserting completion into text should add parens, separator, etc

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#152]
If the selected completion is a function parens should be added
- if func takes args put cursor between parens
- if no args put cursor after right parens

**Comment by rohrlich** [comment]
if completion is package '.' should be added when inserting the completion

**Comment by rohrlich** [comment]
Infrastructure for  this now in and parens are added for funcs. Will be easy to enhance.

Might need another api mod for cursor positioning, e.g. with funcs that take args put cursor between parens but for no arg funcs put cursor past parens

**Comment by rcoreilly** [comment]
should be good now -- open new ticket under gide with any remaining issues.
