### ISSUE TITLE
spelling issues

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#157]
worked well in my test on the textbook -- couple of things:
*  should auto ignore numbers
* __bold__ and _italic_ are used in markdown -- would be good to get rid of __
* would be nice to show the current word in doc as it is being checked..
* how is it looking for dynamic spell-as-you-type?
* did pretty well on the words in my textbook (mostly flagged technical terms) but there were a few pretty standard English words it didn't know -- might be worth seeing if it is possible to just train up on one of the big dictionaries from hunspell -- can you just make like 10x copies of the same dictionary words they all get good frequency, train that up, and then ship the pretrained result instead of the training corpus?

**Comment by rohrlich** [comment]
• Show current word in text is good idea - I'm working on encoding the char pos now. I need that for the actual replacement and once I have that I'll be able to do the find for free.
• spell-as-you-type will be done after I do the spell correction replacement part
• I'll look into options for training - I think the reason for text is that frequency is part of the algorithm for what to suggest.
• Currently I'm only showing best suggestion - I plan to show several - just need to change out the text field for slice view I expect - is that correct?

**Comment by rohrlich** [comment]
Spelling bugs should be created as new issues
