### ISSUE TITLE
Missing from Edit menu

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#159]
Undo 
Redo
Format -- this is for selected text or entire file if no text selected
-- (not sure yet about common key combo - not sure any 2 IDEs use the same key combo)
Paste from History... (shift cmd V) (opens list of recent clipboard entries)

Visual studio uses:
Ctrl + E , Ctrl + D to format the entire document. Ctrl + E , Ctrl + F to format the selection. You can change these in Tools > Options > Environment -> Keyboard 
Goland uses:
cmd-option-L

**Comment by rcoreilly** [comment]
please do try to put these in the gide issues :)

format will be down-the-road.  unless it is just indent?

**Comment by rohrlich** [comment]
No, not indent. Was thinking about invoking of go formatter for selected text.

Yes, I'll be more diligent about where the issue is logged :)

**Comment by rcoreilly** [comment]
go format runs auto when you save.. I'm not sure about any api to run locally on just a chunk of text?

**Comment by rohrlich** [comment]
Yes, I know about when you save. Actually in Goland you can specify what you want to run at save and there are a bunch of options. It also has formatting of selected text so I thought it might be in the go tools.

**Comment by rcoreilly** [comment]
added new big ticket for this on gide
