### ISSUE TITLE
Can't open existing file...

### ISSUE THREAD

**Issue by thazy** [goki/gi#161]
This might just be user error but when I tried to open existing Untitled.tex (in svn_docs/bg/pvlv/bvpvlv sub direction) file by clicking OK as in the picture below - but nothing happened.
![img_0182](https://user-images.githubusercontent.com/30027010/47248612-c82b4900-d3c8-11e8-97b5-4557f9ca95b8.JPG)

**Comment by rcoreilly** [comment]
can you say what command you used to open the file?

**Comment by rcoreilly** [comment]
I mean, how did you get the file chooser in the first place?  what command were you using within the gide app?

**Comment by thazy** [comment]
File -> Open file… then I clicked thru to the subdirectory and file I wanted to open, selected it, then clicked the Ok button at the bottom left.

--
Thomas Emil Hazy MD
thazy@colorado.edu<mailto:thazy@colorado.edu>
303.883.1009





On Oct 19, 2018, at 10:27 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


I mean, how did you get the file chooser in the first place? what command were you using within the gide app?

**Comment by rcoreilly** [comment]
ok, probably the subdirectory was the issue.  how many subdir levels btw?  I'll take a look.

**Comment by thazy** [comment]
~[home]/svn_docs/bg/pvlv/bvpvlv/ …

--
Thomas Emil Hazy MD
thazy@colorado.edu<mailto:thazy@colorado.edu>
303.883.1009





On Oct 19, 2018, at 10:31 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


ok, probably the subdirectory was the issue. how many subdir levels btw? I'll take a look.

**Comment by rcoreilly** [comment]
aha -- there is a key misunderstanding here: gide has the notion of a "project" which is the *proximal* directory containing the files you want to work on.  opening a file way down in a subdir, starting from home, is not the intended use.  you should do "Open Path.." and get to bvpvlv as your project,  and THEN open specific files from there..

**Comment by thazy** [comment]
Okidoke!  Thanks!!

--
Thomas Emil Hazy MD
thazy@colorado.edu<mailto:thazy@colorado.edu>
303.883.1009





On Oct 19, 2018, at 10:39 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


aha -- there is a key misunderstanding here: gide has the notion of a "project" which is the proximal directory containing the files you want to work on. opening a file way down in a subdir, starting from home, is not the intended use. you should do "Open Path.." and get to bvpvlv as your project, and THEN open specific files from there..

**Comment by rcoreilly** [comment]
ps. wrote an intro: https://github.com/goki/gide/wiki/Intro
