### ISSUE TITLE
Edit button/tab opens menu with only filename of the file I was already in.

### ISSUE THREAD

**Issue by thazy** [goki/gi#162]
While in a new text file I was editing I clicked on Edit tab at top (above cursor in picture) to see what options were there and a menu opened in weird place listing the file I was in.  I didn't know what to expect, but am guessing the desired behavior is to get a choice list of "open" files to switch to for editing?  Anyway, where the menu opens seems weird. 

![img_0179](https://user-images.githubusercontent.com/30027010/47248714-84850f00-d3c9-11e8-8a4e-6a0f23b43d6d.JPG)

**Comment by rcoreilly** [comment]
now  is a dropdown menu.
