### ISSUE TITLE
Paste into selection is in wrong location - fix for beta

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#172]
Similar to #151 - 

- Copy some text
- select some other text
- paste
- text will be pasted into wrong place

**Comment by rohrlich** [comment]
John will fix

**Comment by rohrlich** [comment]
Should be good now.

**Comment by rohrlich** [comment]
Not working correctly for multiline paste

**Comment by rcoreilly** [comment]
can you add some docs to replicate?

**Comment by rcoreilly** [comment]
I think this is now working.

**Comment by rohrlich** [comment]
I tried it 5 or 6 times to make sure I wasn't mistaken but now it is working correctly after quitting and restarting gide.

**Comment by rcoreilly** [comment]
hmm.  I've never seen that but maybe it is related to auto-indent?  I had some weirdness associated with that -- like it is auto indenting as you paste or something like that?

**Comment by rcoreilly** [comment]
I'm going to close this one again :)
