### ISSUE TITLE
Completion: possible to get 2 completion popups

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#173]
The mutex isn't working as expected.  See image.
<img width="329" alt="screen shot 2018-10-31 at 5 15 24 pm" src="https://user-images.githubusercontent.com/22350787/47824089-d5352a00-dd30-11e8-9fdc-51c3053eede4.png">

**Comment by rohrlich** [comment]
In this case I entered gi. and I think while the first popup was visible I typed 't'. So perhaps it isn't a problem with the mutex but rather we need to wait for the update to complete after the first popup is deleted.

**Comment by rcoreilly** [comment]
mutex is possibly ok but it just isn't registering the delete?  yeah, what you just said.

run with --race might help.

and, I REALLY think we should have a setting MaxCompletions with a default of 20 and it shouldn't show the completions if there are more than than that max!

If you hit the completion key, you override that and can see everything, but as a matter of course it is not useful when you have so many options..

**Comment by rohrlich** [comment]
Ok, I'll add MaxCompletions and implement.

**Comment by rohrlich** [comment]
Add to GoGi Detailed?

**Comment by rohrlich** [comment]
MaxCompletions fully implemented all using gide and delve. Give it a try.

**Comment by rcoreilly** [comment]
forgot to push??

**Comment by rohrlich** [comment]
Yep, forgot. Just did it. -- You may not like getting the single item popup but users need some clue that there were completions.

**Comment by rcoreilly** [comment]
yeah I was just going to say that!  if you're going to insist on that, you'll need to add a flag that disables it after the first time...  IMO it is not worth it.  Instead let's put a menu item in View or Edit menu that is Show completions and people can see the shortcut..

**Comment by rohrlich** [comment]
My first choice is to implement a limit on the number of items in the popup which I really think we need anyway. I think a menu item for showing the shortcut is a good idea anyway and could go in the edit menu.

**Comment by rohrlich** [comment]
To be clear the limit is just on visible items, not on the items accessible via scroll.

**Comment by rcoreilly** [comment]
ok I'll add the menu item, but seriously we can't have a menu that pops up EVERY TIME you are at a point where there might be more than 20 completions, right?

**Comment by rohrlich** [comment]
I'll get rid of the one line popup but I've never found it a problem with other IDEs to have the popup there no matter how long the list. Typically they have maybe a dozen items visible in the popup. I think if you haven't written the API :) you often are looking to see the full range of functions and fields rather than going to the doc. But that is easy to get to with the "force" shortcut.

**Comment by rohrlich** [comment]
So we still have the freeze with the long popup list. Here is the output scrolling the long list and running with the race option.
WARNING: DATA RACE
Write at 0x00c00ba8c768 by goroutine 22:
  github.com/goki/gi/giv.(*TextBuf).DeleteText()
      /Users/rohrlich/go/src/github.com/goki/gi/giv/textbuf.go:1013 +0x3f1
  github.com/goki/gi/giv.(*TextView).CursorBackspace()
      /Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:1141 +0x300
  github.com/goki/gi/giv.(*TextView).KeyInput()
      /Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:3416 +0x174a
  github.com/goki/gi/giv.(*TextView).TextViewEvents.func4()
      /Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:3689 +0xb1
  github.com/goki/gi.(*WinEventRecv).Call()
      /Users/rohrlich/go/src/github.com/goki/gi/window.go:1648 +0xaa
  github.com/goki/gi.(*Window).SendEventSignal()
      /Users/rohrlich/go/src/github.com/goki/gi/window.go:1792 +0x5ef
  github.com/goki/gi.(*Window).EventLoop()
      /Users/rohrlich/go/src/github.com/goki/gi/window.go:1515 +0x156c

Previous read at 0x00c00ba8c768 by goroutine 37:
  github.com/goki/gide.CompleteGo()
      /Users/rohrlich/go/src/github.com/goki/gide/gide.go:2992 +0x1d0
  github.com/goki/gi.(*Complete).ShowNow()
      /Users/rohrlich/go/src/github.com/goki/gi/complete.go:104 +0x24d
  github.com/goki/gi.(*Complete).Show.func1()
      /Users/rohrlich/go/src/github.com/goki/gi/complete.go:84 +0xdc

Goroutine 22 (running) created at:
  github.com/goki/gi.(*Window).GoStartEventLoop()
      /Users/rohrlich/go/src/github.com/goki/gi/window.go:660 +0xa1
  github.com/goki/gide.NewGideWindow()
      /Users/rohrlich/go/src/github.com/goki/gide/gide.go:2969 +0x57b
  github.com/goki/gide.NewGideProjPath()
      /Users/rohrlich/go/src/github.com/goki/gide/gide.go:2895 +0x77
  main.mainrun()
      /Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:81 +0x41f
  main.main.func1()
      /Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:21 +0x2f
  github.com/goki/gi/gimain.Main.func1()
      /Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:27 +0x3d
  github.com/goki/gi/oswin/driver/macdriver.driverStarted.func1()
      /Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:189 +0x77

Goroutine 37 (running) created at:
  time.goFunc()
      /usr/local/go/src/time/sleep.go:172 +0x51
==================
==================
WARNING: DATA RACE
Read at 0x00c00a9cdc68 by goroutine 44:
  runtime.slicerunetostring()
      /usr/local/go/src/runtime/string.go:190 +0x0
  github.com/goki/gide.CompleteGo()
      /Users/rohrlich/go/src/github.com/goki/gide/gide.go:2993 +0x203
  github.com/goki/gi.(*Complete).ShowNow()
      /Users/rohrlich/go/src/github.com/goki/gi/complete.go:104 +0x24d
  github.com/goki/gi.(*Complete).Show.func1()
      /Users/rohrlich/go/src/github.com/goki/gi/complete.go:84 +0xdc

Previous write at 0x00c00a9cdc6e by goroutine 22:
  [failed to restore the stack]

Goroutine 44 (running) created at:
  time.goFunc()
      /usr/local/go/src/time/sleep.go:172 +0x51

Goroutine 22 (running) created at:
  github.com/goki/gi.(*Window).GoStartEventLoop()
      /Users/rohrlich/go/src/github.com/goki/gi/window.go:660 +0xa1
  github.com/goki/gide.NewGideWindow()
      /Users/rohrlich/go/src/github.com/goki/gide/gide.go:2969 +0x57b
  github.com/goki/gide.NewGideProjPath()
      /Users/rohrlich/go/src/github.com/goki/gide/gide.go:2895 +0x77
  main.mainrun()
      /Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:81 +0x41f
  main.main.func1()
      /Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:21 +0x2f
  github.com/goki/gi/gimain.Main.func1()
      /Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:27 +0x3d
  github.com/goki/gi/oswin/driver/macdriver.driverStarted.func1()
      /Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:189 +0x77
==================

**Comment by rcoreilly** [comment]
I can take a look at this if you want -- let me know.

**Comment by rohrlich** [comment]
I'm done for today so feel free to look at it. If you don't get to it I'll take a look tomorrow.

**Comment by rcoreilly** [comment]
I'm pretty sure this is now fixed per checkin comments..
