### ISSUE TITLE
Find highlights should be updated for all edits, not just replace

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#175]
If you do a "find" and then edit text, e.g. insert a line, all of the highlights beyond are wrong!

**Comment by rohrlich** [comment]
The fix is to move a bit of the code from QReplaceReplace into DeleteText and InsertText but it also means adjusting for the line as well as the character and currently we only adjust for the character position. Perhaps we should let this one go until after beta.

**Comment by rcoreilly** [comment]
yes I think wait on it.. very easy to just do a re-find..

**Comment by rohrlich** [comment]
Nice infrastructure fix by Randy resolved this problem
