### ISSUE TITLE
After creating new project, then tried to create File -> New -> File - got beach ball.

### ISSUE THREAD

**Issue by thazy** [goki/gi#176]
![img_0185](https://user-images.githubusercontent.com/30027010/47827835-abd2c900-dd45-11e8-836f-02dbbe307a39.JPG)

**Comment by rcoreilly** [comment]
couldn't replicate.. can you?

**Comment by rcoreilly** [comment]
ps. assume you did git pull on ki, gi, gide?

**Comment by thazy** [comment]
It does replicate for me.  Can’t further define it so far...

--
Thomas Emil Hazy MD
thazy@colorado.edu<mailto:thazy@colorado.edu>
303.883.1009





On Oct 31, 2018, at 8:59 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


couldn't replicate.. can you?

**Comment by thazy** [comment]
After doing a brew upgrade (for Mojave) I did:

~/go/src/github.com/goki$<http://github.com/goki$> go get -u …

then …/gide/cmd/gide> go build and go install

###

I’ll try the git pulls instead...

--
Thomas Emil Hazy MD
thazy@colorado.edu<mailto:thazy@colorado.edu>
303.883.1009





On Oct 31, 2018, at 9:00 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


ps. assume you did git pull on ki, gi, gide?

**Comment by rcoreilly** [comment]
I notice in your screen shot that you don’t have the Console tab — so you’re not on the latest.. 

need to be in goki/gide/cmd/gide for go get -u ... to work I think!

**Comment by thazy** [comment]
After doing the three git pulls I got the beach ball after File -> New -> New project…

In case it helps here’s the first part of the error log (it’s way long):


Date/Time:       2018-10-31 22:05:05 -0600
End time:        2018-10-31 22:05:07 -0600
OS Version:      Mac OS X 10.14 (Build 18A391)
Architecture:    x86_64
Report Version:  27

Data Source:     Stackshots
Shared Cache:    0x10c37000 FFEAA314-1D6D-39C5-9E43-DA025BFF50A9
Shared Cache:    0 4B3A1C79-2F40-35BE-92B8-2483FBE34B2D

Command:         gide
Path:            /Users/USER/*/gide
Version:         ??? (???)
Parent:          bash [81106] [unique pid 280127]
Responsible:     bash [81106] [unique pid 280127]
PID:             81107

Event:           hang
Duration:        2.19s (process was unresponsive for 153 seconds before sampling)
Steps:           22 (100ms sampling interval)

Hardware model:  MacBookPro10,1
Active cpus:     8

Time Awake Since Boot: 330000s
Time Since Wake: 100000s

Fan speed:       2161 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------


Heaviest stack for the main thread of the target process:
  22  runtime.park_m + 174 (gide + 221086) [0x4035f9e]
  22  runtime.schedule + 729 (gide + 220697) [0x4035e19]
  22  runtime.stoplockedm + 138 (gide + 214762) [0x40346ea]
  22  runtime.notesleep + 227 (gide + 54851) [0x400d643]
  22  runtime.semasleep + 133 (gide + 179893) [0x402beb5]
  22  runtime.pthread_cond_wait + 81 (gide + 315905) [0x404d201]
  22  runtime.asmcgocall + 173 (gide + 373389) [0x405b28d]
  22  runtime.pthread_cond_wait_trampoline + 16 (gide + 382976) [0x405d800]
  22  __psynch_cvwait + 10 (libsystem_kernel.dylib + 16818) [0x7fff6934d1b2]
 *22  psynch_cvcontinue + 0 (pthread + 19278) [0xffffff7f81b55b4e]


Process:         gide [81107] [unique pid 280128]
UUID:            83F41830-ECD3-3533-90FD-2BA6A5FF2065
Path:            /Users/USER/*/gide
Architecture:    x86_64
Parent:          bash [81106] [unique pid 280127]
Responsible:     bash [81106] [unique pid 280127]
UID:             501
Footprint:       273.59 MB
Start time:      2018-10-31 22:05:05 -0600
End time:        2018-10-31 22:05:07 -0600
Num samples:     22 (1-22)
Note:            Unresponsive for 153 seconds before sampling
Note:            1 idle work queue thread omitted

  Thread 0x24eade           DispatchQueue 1           22 samples (1-22)         priority 46 (base 46)
  <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [79975] [unique pid 278996], IO tier 0>
  22  runtime.park_m + 174 (gide + 221086) [0x4035f9e] 1-22
    22  runtime.schedule + 729 (gide + 220697) [0x4035e19] 1-22
      22  runtime.stoplockedm + 138 (gide + 214762) [0x40346ea] 1-22
        22  runtime.notesleep + 227 (gide + 54851) [0x400d643] 1-22
          22  runtime.semasleep + 133 (gide + 179893) [0x402beb5] 1-22
            22  runtime.pthread_cond_wait + 81 (gide + 315905) [0x404d201] 1-22
              22  runtime.asmcgocall + 173 (gide + 373389) [0x405b28d] 1-22
                22  runtime.pthread_cond_wait_trampoline + 16 (gide + 382976) [0x405d800] 1-22
                  22  __psynch_cvwait + 10 (libsystem_kernel.dylib + 16818) [0x7fff6934d1b2] 1-22
                   *22  psynch_cvcontinue + 0 (pthread + 19278) [0xffffff7f81b55b4e] 1-22

  Thread 0x24eadf           22 samples (1-22)         priority 31 (base 31)
  <thread QoS default (requested default), process unclamped, process received importance donation from WindowServer [79975] [unique pid 278996], IO tier 0>
  22  thread_start + 13 (libsystem_pthread.dylib + 9253) [0x7fff69402425] 1-22
    22  _pthread_start + 70 (libsystem_pthread.dylib + 25255) [0x7fff694062a7] 1-22
      22  _pthread_body + 126 (libsystem_pthread.dylib + 13117) [0x7fff6940333d] 1-22
        22  crosscall_amd64 + 12 (gide + 7836797) [0x477947d] 1-22
          22  runtime.mstart + 102 (gide + 207590) [0x4032ae6] 1-22
            22  runtime.mstart1 + 230 (gide + 207846) [0x4032be6] 1-22
              22  runtime.sysmon + 371 (gide + 238883) [0x403a523] 1-22
                22  runtime.notetsleep + 105 (gide + 55673) [0x400d979] 1-22
                  22  runtime.notetsleep_internal + 269 (gide + 55213) [0x400d7ad] 1-22
                    22  runtime.semasleep + 271 (gide + 180031) [0x402bf3f] 1-22
                      22  runtime.pthread_cond_timedwait_relative_np + 81 (gide + 316017) [0x404d271] 1-22
                        22  runtime.asmcgocall + 173 (gide + 373389) [0x405b28d] 1-22
                          22  runtime.pthread_cond_timedwait_relative_np_trampoline + 20 (gide + 383012) [0x405d824] 1-22
                            22  __psynch_cvwait + 10 (libsystem_kernel.dylib + 16818) [0x7fff6934d1b2] 1-22
                             *22  psynch_cvcontinue + 0 (pthread + 19278) [0xffffff7f81b55b4e] 1-22


###

After doing a brew upgrade (for Mojave) I did:

~/go/src/github.com/goki$<http://github.com/goki$> go get -u …

then …/gide/cmd/gide> go build and go install

###

I’ll try the git pulls instead...

--
Thomas Emil Hazy MD
thazy@colorado.edu<mailto:thazy@colorado.edu>
303.883.1009





On Oct 31, 2018, at 9:00 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


ps. assume you did git pull on ki, gi, gide?

**Comment by rcoreilly** [comment]
do you have a console tab?
if so, can you do the following

go get github.com/derekparker/delve
cd to above in go/src/
cd to cmd/dlv
go install

then in goki/cmd/goki, do:

>  dlv debug  (it will build)
> c  (it will run)

then if you get a crash do the following, or if you don't get a crash but just the beach ball, hit Ctrl-C in dlv and then:

> goroutines

and attach that output here?  Thanks!

ps, need to make sure that ~/go/bin is on your PATH for dlv commandline to work.

**Comment by rcoreilly** [comment]
![screen shot 2018-10-31 at 10 17 43 pm](https://user-images.githubusercontent.com/9605819/47832386-d0856b80-dd5a-11e8-9123-06e5ae12821a.png)

ps this is the console tab..

**Comment by thazy** [comment]
Thanks!  I did the …/gide/cmd/gide>go get -u …  and now have the console and no more beach balls (at least yet)…

(didn’t do the last set of instructions for the console since above seems to have worked)

--
Thomas Emil Hazy MD
thazy@colorado.edu<mailto:thazy@colorado.edu>
303.883.1009





On Oct 31, 2018, at 10:18 PM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


[screen shot 2018-10-31 at 10 17 43 pm]<https://user-images.githubusercontent.com/9605819/47832386-d0856b80-dd5a-11e8-9123-06e5ae12821a.png>

ps this is the console tab..

**Comment by rcoreilly** [comment]
ok, let's close this and assume it was fixed. many such beach-ball scenarios have recently been fixed, but there may be more lurking somewhere so please report if you find!
