### ISSUE TITLE
typing over selected text does not put cursor in correct spot; need pos update from edit record(s)

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#184]
in textview.go: 2190 or so, InsertAtCursor, if there is selected text that is deleted, and the cursor is anywhere after that text, then the insertion point should be moved up to compensate for the removed text.

the problem now is that the cursor position is not at all updated as text is inserted or deleted.

various recent fixes have presumably dealt with this already in some cases, but this is another one. or perhaps the primary one?

would be good to have a general purpose method that takes any position and updates it as a function of a delete or insert:  anything earlier on the same line changes char pos, anything on prior lines changes line number.

could use undo buffer to compute updated cursor pos relative to changes back to a specific point -- could use time to tag -- thus, making the find / replace updates more automatic: you just take the original position, and the time when the find was run, and then update your coordinates for all changes since that point, and it should handle everything.

I kinda suspect this is what emacs does -- it seems to compensate for changes very generally, though I haven't explicitly tested.

**Comment by rohrlich** [comment]
Also fixed by Randy's recent changes
