### ISSUE TITLE
more spell checking issues

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#185]
* I'm getting a popup for things like  `1.`  `2.` `a`  or `A`

* would be good somehow to put the word being checked into the menu, at the top, as a Label, so you know for sure exactly what it is referring to right there in the menu. Mechanically, a Menu is just a slice of Ki elements, and it is easy to add a Label — not sure how the code works exactly but hopefully easy to add that..

also adding stuff from email thread into ticket, for records and if anyone else has any input..

FWIW, emacs uses “accept”, duration = “editing session”, versus “insert” into dictionary

https://www.gnu.org/software/emacs/manual/html_node/emacs/Spelling.html

And looks like word and openoffice use: Ignore Once, Ignore All, and Add

Anyway, I gather that “ignore” is still just for the editing session and “learn” or “add” is permanent.  Somehow I thought that Ignore All might be permanent too, but that doesn’t make any sense — that would be “Ignore Always" which is the same as Add..

I guess I do still feel like there are really 4 categories of actions at the finest grain:

* Ignore Once — like your quoted guys or a “sic” case

* Ignore Session — fully ignore for now but for whatever reason I’m not sure if I’d want to ignore later or not.. this seems like kicking the can down the road?  somehow it is very context sensitive, to this particular session (?) about whether this is a word to be ignored or not?  Why are we ignoring such words in the first place?  because they are somehow correct in this situation.  So, again, what is so special about this situation vs. any other one later?  Perhaps document type etc but then it seems like we need to have “ignore for all Markdown” or “ignore for this document” (in which case you’d need a dictionary per document..)

* Ignore Always — permanently ignore this word.  If it ever shows up again, don’t bug me about it, but it is not something that I want to add to an official dictionary or anything — e.g., latex formatting commands, names of random people, any cite keys that I might use, etc.  (btw, would be good if your word filter cut out the numbers at the end of cite keys).

* Add / Learn — this is a “real” word and should be used for generating completions next time etc.

I just did some more googling and it seems like I’m not the *only* one overthinking this:

https://ux.stackexchange.com/questions/83396/what-does-ignore-and-ignore-all-really-mean-in-spell-check

And, surprisingly, ignore actually means “for that specific word in that specific document” — how is that even done?  what does “that specific word” even mean?  somehow they are memorizing the context in which the word is appearing??  And, likewise, ignore all appears to be similarly document-specific.

**Comment by rcoreilly** [comment]
the "no suggestion" popup is coming up for all sorts of things that should not even be subject to spelling correction -- needs to only popup when a viable word has been typed.

**Comment by rcoreilly** [comment]
see latest commit and comments about moving completion, spellcheck to the buffer instead of textview (view can just access these structures on the buffer -- nobody is going to be doing spell checking / completion at the same time across multiple views!) - and then they should be under control of the Opts setting there, and then in gide they can be set as appropriate.

can add bool flags on languages to enable / disable each thing on them..

**Comment by rohrlich** [comment]
(Edited from earlier email)

Kind of funny how it can be so complicated :) And as always the hardest part is the nomenclature!

I do think there are at least 4 categories so which do we want and what are their names.

It seems that the most common options are ignore once, ignore all (meaning varies), and add to dictionary but your 4th, ignore always, is an important one I think. My suggestion would be to do that by document type as I think that is the main use case, i.e. ignore in Markdown, ignore in html, etc. We know the doc type so should be easy, though it does probably mean an additional file to save/load. Though thinking about it, I wonder how much markdown would actually cause the spell checker to pop, lots of symbols (once I fix "I'm getting a popup for things like 1. 2. a or A")

My suggestions

Inline spell check:
- (Ignore) user can press esc to skip word so don't put in menu but could for clarity
- Ignore in this Document (in this session) (I don't think a global no doc specific case is sensible)
- Add to Dictionary

File spell check:
- Ignore (single instance skip)
- Ignore in this Document
- Correct (correct this instance)
- Correct All in Document
- Add to Dictionary

**Comment by rohrlich** [comment]
This part "I'm getting a popup for things like 1. 2. a or A" mostly fixed

**Comment by rohrlich** [comment]
If we are meeting tomorrow we could finalize our decision then.

**Comment by rcoreilly** [comment]
working better now!  I just realized that probably the Word et al spelling systems just add a tag / flag in the document itself, marking the word to be ignored by spell check!  This is probably part of the internal markup language.

But that doesn't work for plain text editing like we're doing, or with markup.

unless we want to invent a new markup tag that doesn't do anything except mark a word as an exception.

I thought of this in considering what it would take to switch to just marking up text with underlines -- shouldn't be too hard -- would just have to into the markup code itself and insert / remove appropriate tags.  And then recognize those tags for context menu or something.

It definitely does get in the way to have the popup showing up mid-typing -- often don't expect it and end up typing over it.  I guess it isn't using the delay?

Anyway, we can discuss more tomorrow.

**Comment by rohrlich** [comment]
Issue - I think typing any character should close the popup and insert the character - Agree?

**Comment by rcoreilly** [comment]
maybe not: you can use a char to activate an item in the menu..  I'm leaning toward the markup version for this so that would make it moot..

**Comment by rohrlich** [comment]
Moving one specific item to new issue - I believe all other issues are resolved
