### ISSUE TITLE
Spell check and SelectWord aren't catching contractions, e.g. don't, they're, etc 

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#186]
Started to fix the spell issue when I found that it was an issue for SelectWord() as well. They both use IsWordBreak which takes a single rune. So I wrote IsWordBreak2 which takes 2 characters and that works but I found that the suggestions for "doon't" don't include "don't" (does include "dont". I will return to this issue, not worth taking time right now.

**Comment by rohrlich** [comment]
The fix for this problem for SelectWord is sitting on my computer but I have a question about the code in WordAt() which I separated out of SelectWord a while back to be more generally useful. The main "else" case looks to be there to catch leading spaces so that doing a double click in the spaces before the word dog in the text "    dog" catches the spaces and the word dog whereas a call to SelectWord from a double click between 'd' and 'o' result in just "dog". Why are we doing this? Suggest we drop the "else" part of the code.

**Comment by rohrlich** [comment]
Woke realizing that it provides a convenience in that you don't need to delete the extra space when you delete a word.

**Comment by rohrlich** [comment]
Tough to think through the logic with a bad cold but it I believe I got it!

**Comment by rcoreilly** [comment]
ok I'll test it.  hard to think about in the abstract -- need to see how it plays out in practice..
