### ISSUE TITLE
crash in spell.CorrectText

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#188]
panic: runtime error: slice bounds out of range

goroutine 5 [running]:
github.com/goki/gi/spell.CorrectText(0xc00d6ab080, 0x530, 0x50f, 0x0, 0x0, 0xc013965670, 0x9, 0xc00d6aab00, 0x530, 0xc00d6ab080)
	/Users/oreilly/go/src/github.com/goki/gi/spell/spell.go:147 +0x45e

not sure what exactly caused it, but likely just adding some guards on the LastIndex "last" var are needed.  i'm not sure what the right err behavior is though.. or why it happened in this one time..

**Comment by rohrlich** [comment]
added - If last index is -1 print message and return

**Comment by rohrlich** [comment]
should never occur, but ....
