### ISSUE TITLE
Crash on SaveAll

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#189]
Johns-Mac-Pro:~/go/src/github.com/goki/gide/cmd/gide $ ./gide
2018/11/06 08:06:48 giv.FileNode UpdateNode Path "/Users/rohrlich/go/src/github.com/goki/gi/giv/#textview.go#": Error: stat /Users/rohrlich/go/src/github.com/goki/gi/giv/#textview.go#: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x472bcc5]

goroutine 192 [running]:
github.com/goki/ki/bitflag.HasAtomic(...)
	/Users/rohrlich/go/src/github.com/goki/ki/bitflag/bitflag.go:141
github.com/goki/ki.(*Node).HasFlag(...)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:755
github.com/goki/gi/giv.(*TextBuf).IsChanged(...)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textbuf.go:139
github.com/goki/gide.(*Gide).SaveAllOpenNodes(0xc000b2a000)
	/Users/rohrlich/go/src/github.com/goki/gide/gide.go:851 +0x55
github.com/goki/gide.(*Gide).SaveAllCheck.func1(0x4b5aa20, 0xc000b2a000, 0x4b476a0, 0xc0096bb500, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gide/gide.go:260 +0x65
github.com/goki/ki.(*Signal).Emit(0xc0096bbec8, 0x4b476a0, 0xc0096bb500, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/signal.go:167 +0x1e6
github.com/goki/gi.(*Dialog).Accept(0xc0096bb500)
	/Users/rohrlich/go/src/github.com/goki/gi/dialogs.go:231 +0x85
github.com/goki/gi.ChoiceDialog.func2(0x4b476a0, 0xc0096bb500, 0x4b463e0, 0xc00c515300, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/dialogs.go:520 +0x134
github.com/goki/ki.(*Signal).Emit(0xc00c516b80, 0x4b463e0, 0xc00c515300, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/signal.go:167 +0x1e6
github.com/goki/gi.(*ButtonBase).ButtonReleased(0xc00c515300)
	/Users/rohrlich/go/src/github.com/goki/gi/buttons.go:290 +0xfd
github.com/goki/gi.(*ButtonBase).ButtonRelease(0xc00c515300)
	/Users/rohrlich/go/src/github.com/goki/gi/buttons.go:525 +0x2b
github.com/goki/gi.(*ButtonBase).MouseEvent.func1(0x4b463e0, 0xc00c515300, 0x4b4d460, 0xc0087ca000, 0x0, 0x48820c0, 0xc00a53f530)
	/Users/rohrlich/go/src/github.com/goki/gi/buttons.go:414 +0xcb
github.com/goki/gi.(*WinEventRecv).Call(0xc013d1dc48, 0x4b4d460, 0xc0087ca000, 0x0, 0x48820c0, 0xc00a53f530)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1667 +0x6d
github.com/goki/gi.(*Window).SendEventSignal(0xc0087ca000, 0x4afc120, 0xc00a53f530, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1811 +0x527
github.com/goki/gi.(*Window).EventLoop(0xc0087ca000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:1534 +0x153a
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:670 +0x94

**Comment by rohrlich** [comment]
Happened again. Seems like it might be if I save a file and then build and the backup for the saved file is now gone. I tried to reproduce this way but I didn't get the save dialog when starting build.

**Comment by rcoreilly** [comment]
likely fixed now?  reopen if not.

**Comment by rcoreilly** [comment]
btw I fixed this one recently :)
