### ISSUE TITLE
Vertical scroll difficult if all horizontal content not visible

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#191]
In other words if horizontal scrollbar is in play vertical scroll is hard because you get horizontal as well.

Try opening font window and reduce width to invoke horizontal scroll bar

**Comment by rcoreilly** [comment]
btw  this worked fine for me using my scroll wheel -- only scrolled vertically, unless I put mouse over horiz in which case it scrolled horizontally.  I'll test on trackpad later..

**Comment by rohrlich** [comment]
Yes try with trackpad. I don't have an alternative input device handy.

**Comment by rohrlich** [comment]
Most of the time it is working smoothly so I'm going to close.
