### ISSUE TITLE
crash selecting font

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#192]
2018/11/08 14:16:58 gi.FontLib: error loading font applesdgothicneo, removed from list
panic: interface conversion: ki.Ki is nil, not *giv.FileNode

goroutine 114 [running]:
github.com/goki/gi/giv.(*FileTreeView).FileNode(0xc00b1c0000, 0x19bf74c0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/filetree.go:776 +0x9f
github.com/goki/gi/giv.(*FileTreeView).Style2D(0xc00b1c0000)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/filetree.go:1068 +0x2f
github.com/goki/gi.(*Node2DBase).Style2DTree.func1(0x4b65da0, 0xc00b1c0000, 0x8, 0x48ed6a0, 0xc00aa60000, 0xc00aa60001)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:552 +0x51
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00b1c0000, 0x8, 0x48ed6a0, 0xc00aa60000, 0x49b07d8, 0xc00aa60000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1035 +0x98
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc0033bb300, 0x8, 0x48ed6a0, 0xc00aa60000, 0x49b07d8, 0xc00adf7700)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1044 +0x1a2
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00333ac00, 0x7, 0x48ed6a0, 0xc00aa60000, 0x49b07d8, 0xc00aa60000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1044 +0x1a2
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00adf7600, 0x6, 0x48ed6a0, 0xc00aa60000, 0x49b07d8, 0xc00aa60000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1044 +0x1a2
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00aa60a80, 0x5, 0x48ed6a0, 0xc00aa60000, 0x49b07d8, 0xc00adf6600)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1044 +0x1a2
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc000a35b00, 0x4, 0x48ed6a0, 0xc00aa60000, 0x49b07d8, 0xc00adf4600)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1044 +0x1a2
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00adf6580, 0x3, 0x48ed6a0, 0xc00aa60000, 0x49b07d8, 0xc00aa60100)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1044 +0x1a2
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00adf4500, 0x2, 0x48ed6a0, 0xc00aa60000, 0x49b07d8, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1044 +0x1a2
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc00aa60000, 0x1, 0x48ed6a0, 0xc00aa60000, 0x49b07d8, 0xc000a35b01)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1044 +0x1a2
github.com/goki/gi.(*Node2DBase).Style2DTree(0xc00aa60000)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:547 +0xb2
github.com/goki/gi.(*WidgetBase).ReRender2DTree(0xc00aa60000)
	/Users/rohrlich/go/src/github.com/goki/gi/widget.go:393 +0x184

**Comment by rcoreilly** [comment]
added nil guards to all FileNode() access in FileTreeView..
