### ISSUE TITLE
Underline for spelling error not always appearing

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#194]
Looks to be a problem with tags, not spelling, there are slew of nil tags in buf, maybe a problem with delete tag.

**Comment by rcoreilly** [comment]
nil tags are ok.  the problem is a surrounding tag.  For now I'm enforcing a "no nested tags" policy -- otherwise things get a git more complex.

and we have an issue with e.g., the heading tags not showing up in markdown, so probably you just can't see the other tag -- working on that now.

**Comment by rohrlich** [comment]
Still an issue but now consistently missing

**Comment by rcoreilly** [comment]
It is "working" for me -- the tags etc are all there, but it is rendering an overbar instead of a dotted underline!  hmm..

**Comment by rcoreilly** [comment]
now fixed.  deco field is a bitflag.

**Comment by rohrlich** [comment]
Working consistently I believe - closing
