### ISSUE TITLE
textview: add parens / bracket matcher

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#196]
adds a highlight for the matching bracket or parens that you're on..

needs to count up all the intervening ones, and preferably not get confused by things in quotes etc, but that would await the actual parser -- just do something simple as a first pass.

**Comment by rohrlich** [comment]
Nearly done with simple version that doesn't worry about quotes, etc. -

**Comment by rohrlich** [comment]
The code is in but there are a couple of todos:
- works now with mouse click - also need key sequence to invoke - Randy let me know what that should be
- currently using highlight but perhaps it should be a different highlight color
- highlight should clear on next keystroke or click

**Comment by rcoreilly** [comment]
Nice!  highlight seems fine.  In emacs, if you type any of the relevant chars: ( ) { } [ ]  it does the match right then.  that seems like the most obvious thing, rather than another keystroke.  mouse click is good too.

**Comment by rohrlich** [comment]
This is complete now. Now works for square  brackets, parens and curlies. It now works based on cursor position whether mouse or keyinput (code is in SetCursor). The highlight on the braces, etc. is cleared on the next cursor movement.
