### ISSUE TITLE
Context menu on word should always provide cut/copy/paste

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#200]
This won't work:
func (tv *TextView) ContextMenu() {
	if tv.Buf.SpellCorrect != nil {
		if tv.OfferCorrect() {
			return
		}
	}
	tv.WidgetBase.ContextMenu()
}

What we want is to add "check spelling" to context menu with the shortcut. If the user types the shortcut then check spelling and popup suggestions but if they invoke menu give them the standard with additional action.

What is the mechanism for adding to context menu. Should the menu be returned from WidgetBase allowing additional actions?

**Comment by rcoreilly** [comment]
my thinking was that if you click on a misspelled word, your goal is to correct it and you don't wan't have to go through an extra menu.

if the word is not misspelled, OfferCorrect returns false and you get the normal context menu.

to me this makes more sense than the relatively rare use of other context menu options.

**Comment by rohrlich** [comment]
Mostly good but if you place the cursor just after a word (no selection) you get a spell menu so HasSelection() must be returning true. If you place cursor just before you get the paste menu item (i.e. correctly no selection)

I think I'll write a function that determines if you are at the start of a word, end of a word or midword. Will make it simpler to know when to spell check, clear the tag, etc.

**Comment by rohrlich** [comment]
I was starting to fix this when I realized that there are more fundamental issues/problems here, at least on a mac for a mac user. My own behavior is to tap with 2 fingers to get a context menu and that by itself should select the word under the cursor and pop a menu. Now we don't have to do it that way but as it is now you need to first get your cursor where you want it and the tap with 2 fingers because the menu options and spelling corrections are based on where the cursor is. The other related problem is that control+click on mouse should get you the context menu and it doesn't.

![screen shot 2018-11-15 at 7 32 30 pm](https://user-images.githubusercontent.com/22350787/48594525-2be45b80-e90e-11e8-8956-b41a307b2432.png)

**Comment by rohrlich** [comment]
The menu photo is the result of a 2 finger tap anywhere on the work demo with the cursor being somewhere else before the tap. Control + click would do the same.

**Comment by rohrlich** [comment]
I fixed one of the issues mentioned 2 comments back - a right mouse click now sets the cursor so you don't need to click and then separately invoke menu.
Also, fixed unreported problem of spelling menu showing up in code rather than just in comments

**Comment by rohrlich** [comment]
One issue remains - will file separately
