### ISSUE TITLE
If I am in "small" view and I drag the splitter between edit and tab frames I get a second edit window

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#201]

**Comment by rcoreilly** [comment]
yep, that is exactly what should happen!  that is the 2nd editor.  there are ALWAYS 5 panels, and the splitters just determine which ones are collapsed or not..

**Comment by rohrlich** [comment]
So if I want to change the relative sizes of the visible frames I need to open the dialog and enter values?

**Comment by rcoreilly** [comment]
i was able to drag both splitters around to adjust size of the single edit window, but yeah it can be a couple more steps sometimes depending on how lucky you get with the splitter grab.  It is not clear what an alternative would be for generic splitter functionality?  can't read the user's mind...  don't want to change gide to actually eliminate the 2nd editor as that would really add a lot of complexity to the logic everywhere.

**Comment by rcoreilly** [comment]
ps. we could add a double-click action to collapse and restore splitters -- that was on todo list ast some point.

**Comment by rohrlich** [comment]
I don't for sure what the best design would be but I do know that the splitters still have issues. I still find that some grabs just move the image and don't change the size of the panel

Suggestions:
- have a second splitter so you know that there are really two of them when a panel is invisible (see pic)
![screen shot 2018-11-12 at 1 33 29 pm](https://user-images.githubusercontent.com/22350787/48373751-fb878d80-e67f-11e8-8712-8e0dc0c0b715.png)

- allow the entire white space to be "grabable" (conflicts with prior suggestion)

**Comment by rcoreilly** [comment]
not going to fix this at this point -- got rid of extra panel and this is not a hi-freq case and existing logic is at least clear.
