### ISSUE TITLE
xurls.Relaxed is a variable, not a function

### ISSUE THREAD

**Issue by cbgo** [goki/gi#202]
Playing around with gi (go1.11.2 windows/amd64) I faced the following:
* create some folder
* `go mod init local`
* create `main.go` with the contents from https://github.com/goki/gi/blob/master/examples/basic/basic.go
* `go build` which fails with:
```
..\..\..\go\pkg\mod\github.com\goki\gi@v0.0.0-20181112192923-6c609aa46a98\gi\spell.go:73:23: cannot call non-function xurls.Relaxed (type *regexp.Regexp)
```
The build went over this after changing `isUrl = xurls.Relaxed()` to `isUrl = xurls.Relaxed`.

**Comment by rcoreilly** [comment]
looks like you need to do some form of `go get -u ./ ...` (e.g., in `github.com/goki/gi/examples/widgets`)  to update your repositories, or just specifically update github.com/mvdan/xurls -- it is now a method not a var.
