### ISSUE TITLE
Use vgo vendoring to deal with changing dependencies

### ISSUE THREAD

**Issue by cbgo** [goki/gi#203]
Playing around further (after #202) I faced the following during `go build`:
```
# github.com/goki/gi/histyle
..\..\..\go\pkg\mod\github.com\goki\gi@v0.0.0-20181112192923-6c609aa46a98\histyle\hitags.go:288:28: undefined: chroma.EOFType
```
Looks like they changed the types in chroma a few days ago. Maybe its a good idea for gi to leverage modules with specific version dependencies.

**Comment by rcoreilly** [comment]
yep looks like that might be necessary soon given the extent of dependencies here.
