### ISSUE TITLE
do spellcheck when cursor goes over text, not just after space / return

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#204]
if you go back and fix a spelling error, then moving past the end of the word should trigger an update and clear the error tag if corrected.  right now you have to re-enter a space to trigger the update.

**Comment by rohrlich** [comment]
Yes, good idea. I'll fix that.

**Comment by rohrlich** [comment]
Also noticed that mispeled. doesn't show as an error because of the period but the spell checker in "issues" does catch it :)

I'll start with that fix

**Comment by rcoreilly** [comment]
Doesn't look like it to me in my test just now.. I'm using chrome.  anyway, that would lead to a lot of false alarms I think..  and if you're typing fast you'd miss some.  I think the current strategy is good..

**Comment by rcoreilly** [comment]
I meant that it didn't look like chrome was using pauses to spell-check words mid-word.. :)

**Comment by rcoreilly** [comment]
and you can expt with mid-word stuff but my sense is that it will produce a lot of false alarms... and if you click away, then I think we don't need to worry about it.  this is really just to catch stuff as you're writing some text in a normal sequence -- can always go back and run spellcheck on it later..

**Comment by rohrlich** [comment]
Found that my repositories were out of sync and the commit/push didn't really happen. Had to do "git reset --hard origin/master". You should now find that words followed by period, comma, etc are correctly checked. I'll fix the clear tag issues today.

**Comment by rohrlich** [comment]
un-tagging for learn/ignore is in

**Comment by rcoreilly** [comment]
working well!  one thing overall about spelling: I'm constantly having to teach it about the plural forms of words.  Not sure there is anything sufficiently general to do about that, but perhaps if we did have a dictionary with singular and plural forms, that might help..

**Comment by rohrlich** [comment]
I'll think about that.
