### ISSUE TITLE
Support Wayland

### ISSUE THREAD

**Issue by xyproto** [goki/gi#208]
I'm on 64-bit Arch Linux, using the Sway windowmanager.

When compiling and running the `widgets` example with:

    GOOS=windows GOARCH=amd64 go build && wine widgets.exe

It works fine:

![gogi_widgets](https://user-images.githubusercontent.com/52813/48486195-1fcba180-e81b-11e8-9f3f-683258cd3789.jpg)

However, building and running the Linux version results in a segfault:

```
$ go build && ./widgets
gi.FontLib: error accessing path "/usr/share/fonts/truetype": lstat /usr/share/fonts/truetype: no such file or directory
2018/11/14 11:35:36 gi.FontLib: error walking the path "/usr/share/fonts/truetype": lstat /usr/share/fonts/truetype: no such file or directory
2018/11/14 11:35:36 open /home/afr/.config/GoGi/win_geom_prefs.json: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x7c7f5d]
goroutine 1 [running]:
github.com/goki/gi/gi.(*WindowGeomPrefs).RecordPref(0x1a4c268, 0xc000258d80)
/home/afr/clones/gi/gi/window.go:3286 +0x12d
github.com/goki/gi/gi.(*Window).Resized(0xc000258d80, 0x0, 0x0)
/home/afr/clones/gi/gi/window.go:568 +0x32c
github.com/goki/gi/gi.(*Window).EventLoop(0xc000258d80)
/home/afr/clones/gi/gi/window.go:1325 +0x6fe
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc000258d80)
/home/afr/clones/gi/gi/window.go:690 +0x63
main.mainrun()
/home/afr/clones/gi/examples/widgets/widgets.go:368 +0x3ed9
main.main.func1()
/home/afr/clones/gi/examples/widgets/widgets.go:24 +0x20
github.com/goki/gi/gimain.Main.func1(0xf3ed60, 0xc0001f0000)
/home/afr/clones/gi/gimain/gimain.go:27 +0x24
github.com/goki/gi/oswin/driver/x11driver.main(0xc00054bf60, 0x0, 0x0)
/home/afr/clones/gi/oswin/driver/x11driver/x11driver.go:65 +0x274
github.com/goki/gi/oswin/driver/x11driver.Main(0xc00069df60)
/home/afr/clones/gi/oswin/driver/x11driver/x11driver.go:38 +0x2f
github.com/goki/gi/oswin/driver.main(0xc00054bf60)
/home/afr/clones/gi/oswin/driver/driver_x11.go:22 +0x2b
github.com/goki/gi/oswin/driver.Main(0xc00054bf60)
/home/afr/clones/gi/oswin/driver/driver.go:27 +0x2b
github.com/goki/gi/gimain.Main(0xdd1888)
/home/afr/clones/gi/gimain/gimain.go:26 +0x49
main.main()
/home/afr/clones/gi/examples/widgets/widgets.go:23 +0x2d
```

This is also the case for the other examples.

**Comment by xyproto** [comment]
Screenshot:

![gogi_widgets](https://user-images.githubusercontent.com/52813/48486105-d5e2bb80-e81a-11e8-8473-6127e9155f5e.jpg)

**Comment by xyproto** [comment]
As far as I can tell, I get the same error with 31af460.

I do use Sway, which uses Wayland and not Xorg / X11, that is correct.

While Wayland is still new to many, Gnome supports it and KDE has stopped developing for X11 entirely. I would not be surprised if something else than X11 would become the default for most major distros not too far ahead in the future. Ubuntu already wanted to make the switch to Wayland, but postponed it, because it's not 100% ready yet. But X11 is not a given on Linux anymore.

**Comment by rcoreilly** [comment]
This is a big job!  The basic structure of wayland is very compatible with GoGi in that it is based on the client using a bit buffer to do all the rendering.  I didn't look into the input device API.

* https://golanglibs.com/tag/wayland
* https://wayland.freedesktop.org/

Shiny did not have any support for wayland, and I am not going to be able to do this anytime soon.. So, in the interim, it looks like the best way to use it is using the xserver under wayland: https://wayland.freedesktop.org/xserver.html

@xyproto can you try that and hopefully it works as a workaround for now?

**Comment by Russtopia** [comment]
I am getting similar errors on Linux trying to run the examples/widgets. As far as I know, I'm not using Wayland (KDE plasma on Funtoo Linux x86_64)

~/go/src/github.com/goki/gi/examples/widgets $ ./widgets 
2018/12/09 21:36:55 open /home/russtopia/.config/GoGi/win_geom_prefs.json: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x998d2d]

goroutine 1 [running]:
github.com/goki/gi/gi.(*WindowGeomPrefs).RecordPref(0x1ad4178, 0xc0000e2000)
	/home/russtopia/go/src/github.com/goki/gi/gi/window.go:3287 +0x12d
github.com/goki/gi/gi.(*Window).Resized(0xc0000e2000, 0x0, 0x0)
	/home/russtopia/go/src/github.com/goki/gi/gi/window.go:568 +0x32c
github.com/goki/gi/gi.(*Window).EventLoop(0xc0000e2000)
	/home/russtopia/go/src/github.com/goki/gi/gi/window.go:1325 +0x6fe
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc0000e2000)
	/home/russtopia/go/src/github.com/goki/gi/gi/window.go:690 +0x63
main.mainrun()
	/home/russtopia/go/src/github.com/goki/gi/examples/widgets/widgets.go:368 +0x3ed9
main.main.func1()
	/home/russtopia/go/src/github.com/goki/gi/examples/widgets/widgets.go:24 +0x20
github.com/goki/gi/gimain.Main.func1(0xf8d9a0, 0xc0006d6000)
	/home/russtopia/go/src/github.com/goki/gi/gimain/gimain.go:27 +0x24
github.com/goki/gi/oswin/driver/x11driver.main(0xc0004f1f60, 0x0, 0x0)
	/home/russtopia/go/src/github.com/goki/gi/oswin/driver/x11driver/x11driver.go:65 +0x274
github.com/goki/gi/oswin/driver/x11driver.Main(0xc0004edf60)
	/home/russtopia/go/src/github.com/goki/gi/oswin/driver/x11driver/x11driver.go:38 +0x2f
github.com/goki/gi/oswin/driver.main(0xc0004f1f60)
	/home/russtopia/go/src/github.com/goki/gi/oswin/driver/driver_x11.go:22 +0x2b
github.com/goki/gi/oswin/driver.Main(0xc0004f1f60)
	/home/russtopia/go/src/github.com/goki/gi/oswin/driver/driver.go:27 +0x2b
github.com/goki/gi/gimain.Main(0xe19fb8)
	/home/russtopia/go/src/github.com/goki/gi/gimain/gimain.go:26 +0x49
main.main()
	/home/russtopia/go/src/github.com/goki/gi/examples/widgets/widgets.go:23 +0x2d

**Comment by rcoreilly** [comment]
that looks very much like the same wayland crash.. KDE definitely can run on wayland and that may in fact be the default.  can you try running the wayland xserver per above comment: https://wayland.freedesktop.org/xserver.html

**Comment by rcoreilly** [comment]
@Russtopia could you try this latest version?  In looking through the code again, it seems like everything must actually be working (otherwise it would crash / warn earlier) and somehow the window just didn't get the screen pointer set.  that is what this fixes.  @xyproto would be great if you could try it on your wayland system too -- again it seems like it might actually "just work" hopefully with this fix..

**Comment by Russtopia** [comment]
Hi, thanks for the update.

I still get a crash. This time, I see for a 'split second' something try to draw a large window border, but then I get essentially the same crash. Note the first message in the dump is that there's a .json file I seem to be missing -- is there an install or init procedure I need to run to create this win_geom_prefs.json?

2018/12/10 21:54:25 open /home/russtopia/.config/GoGi/win_geom_prefs.json: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0xb9b144]

goroutine 1 [running]:
github.com/goki/gi/oswin/driver/x11driver.(*windowImpl).DeleteTexture(...)
	/home/russtopia/go/src/github.com/goki/gi/oswin/driver/x11driver/window.go:461
github.com/goki/gi/oswin/driver/x11driver.(*textureImpl).Release(0xc000305ac0)
	/home/russtopia/go/src/github.com/goki/gi/oswin/driver/x11driver/texture.go:57 +0x54
github.com/goki/gi/gi.(*Window).Resized(0xc00032a000, 0x400, 0x2e9)
	/home/russtopia/go/src/github.com/goki/gi/gi/window.go:559 +0x3a3
github.com/goki/gi/gi.(*Window).EventLoop(0xc00032a000)
	/home/russtopia/go/src/github.com/goki/gi/gi/window.go:1486 +0xcf5
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc00032a000)
	/home/russtopia/go/src/github.com/goki/gi/gi/window.go:690 +0x63
main.mainrun()
	/home/russtopia/go/src/github.com/goki/gi/examples/widgets/widgets.go:368 +0x3ed9
main.main.func1()
	/home/russtopia/go/src/github.com/goki/gi/examples/widgets/widgets.go:24 +0x20
github.com/goki/gi/gimain.Main.func1(0xf8f080, 0xc000702000)
	/home/russtopia/go/src/github.com/goki/gi/gimain/gimain.go:27 +0x24
github.com/goki/gi/oswin/driver/x11driver.main(0xc0006fff60, 0x0, 0x0)
	/home/russtopia/go/src/github.com/goki/gi/oswin/driver/x11driver/x11driver.go:65 +0x274
github.com/goki/gi/oswin/driver/x11driver.Main(0xc0006fff60)
	/home/russtopia/go/src/github.com/goki/gi/oswin/driver/x11driver/x11driver.go:38 +0x2f
github.com/goki/gi/oswin/driver.main(0xc0001b5f60)
	/home/russtopia/go/src/github.com/goki/gi/oswin/driver/driver_x11.go:22 +0x2b
github.com/goki/gi/oswin/driver.Main(0xc0001b5f60)
	/home/russtopia/go/src/github.com/goki/gi/oswin/driver/driver.go:27 +0x2b
github.com/goki/gi/gimain.Main(0xe1b9b0)
	/home/russtopia/go/src/github.com/goki/gi/gimain/gimain.go:26 +0x49
main.main()
	/home/russtopia/go/src/github.com/goki/gi/examples/widgets/widgets.go:23 +0x2d

**Comment by rcoreilly** [comment]
Hmm.. it does look like we get past the previous point of crashing, so that fix "solved" that problem, but now it is having some kind of problem with the texture.. It looks like I'll have to get my VM running wayland and see if there is some possibility of getting it to work under some kind of X11 compatibility mode that it might be using (which is clearly not perfectly aligned with the current x11 driver), assuming that is the situation here.  @Russtopia do you have any way of actually figuring out if you might be running wayland or not?  Unfortunately I have 0 experience with that -- have only used X11..

**Comment by Russtopia** [comment]
..and here I thought *I* was running X11 as well :). I will have to dig and see, I will let you know tomorrow. I guess it's possible I'm not!?  It was quite a long emerge cycle to get KDE plasma fully installed in Funtoo and it was many months ago that I did it...

**Comment by Russtopia** [comment]
Eeks. I'm a bit scared to mess with my machine's 'X' (I thought) setup. Is there some other way to confirm 100% whether I'm using plasma under X rather than Wayland without the steps described at [https://wayland.freedesktop.org/xserver.html](https://wayland.freedesktop.org/xserver.html)?

I know this is devolving into a Linux setup discussion.. I'll go do some research before I bother you again. But if you know of a 'smoking gun' binary or lib that should be present to indicate plasma's using Wayland rather than X that I could check, I'd rather do that than risk breaking my desktop config on the entire machine.

**Comment by xyproto** [comment]
@rcoreilly

Currently I'm unable to compile goki, I get this error message:

```
# github.com/goki/gi/giv
../../giv/textbuf.go:1631:16: tb.PiState.Src.LinesInserted undefined (type lex.File has no field or method LinesInserted)
../../giv/textbuf.go:1661:16: tb.PiState.Src.LinesDeleted undefined (type lex.File has no field or method LinesDeleted)
```

**Comment by rcoreilly** [comment]
@xyproto thanks for checking -- it does seem overall that Sway is running a compatibility X server and that makes sense for how far it gets in starting up.  There is just something else in the x11 driver that is not working with this setup presumably.

and you need to update goki/pi -- that is a new dependency -- go get -u ./... or something to that effect

**Comment by xyproto** [comment]
`go get -u -v` (update + verbose`) and then `make` now worked for building the `widget` example.

The error message when running it is:

```
gi.FontLib: error accessing path "/usr/share/fonts/truetype": lstat /usr/share/fonts/truetype: no such file or directory
2018/12/11 13:16:58 gi.FontLib: error walking the path "/usr/share/fonts/truetype": lstat /usr/share/fonts/truetype: no such file or directory
2018/12/11 13:16:58 open /home/afr/.config/GoGi/win_geom_prefs.json: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0xb90db4]

goroutine 1 [running]:
github.com/goki/gi/oswin/driver/x11driver.(*windowImpl).DeleteTexture(...)
	/home/afr/clones/gi/oswin/driver/x11driver/window.go:461
github.com/goki/gi/oswin/driver/x11driver.(*textureImpl).Release(0xc00002e180)
	/home/afr/clones/gi/oswin/driver/x11driver/texture.go:57 +0x54
github.com/goki/gi/gi.(*Window).Resized(0xc000368d80, 0x0, 0x0)
	/home/afr/clones/gi/gi/window.go:559 +0x3a3
github.com/goki/gi/gi.(*Window).EventLoop(0xc000368d80)
	/home/afr/clones/gi/gi/window.go:1486 +0xcf5
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc000368d80)
	/home/afr/clones/gi/gi/window.go:690 +0x63
main.mainrun()
	/home/afr/clones/gi/examples/widgets/widgets.go:368 +0x3ed9
main.main.func1()
	/home/afr/clones/gi/examples/widgets/widgets.go:24 +0x20
github.com/goki/gi/gimain.Main.func1(0xf82e40, 0xc0006c2000)
	/home/afr/clones/gi/gimain/gimain.go:27 +0x24
github.com/goki/gi/oswin/driver/x11driver.main(0xc000691f60, 0x0, 0x0)
	/home/afr/clones/gi/oswin/driver/x11driver/x11driver.go:65 +0x274
github.com/goki/gi/oswin/driver/x11driver.Main(0xc000691f60)
	/home/afr/clones/gi/oswin/driver/x11driver/x11driver.go:38 +0x2f
github.com/goki/gi/oswin/driver.main(0xc0001bbf60)
	/home/afr/clones/gi/oswin/driver/driver_x11.go:22 +0x2b
github.com/goki/gi/oswin/driver.Main(0xc0001bbf60)
	/home/afr/clones/gi/oswin/driver/driver.go:27 +0x2b
github.com/goki/gi/gimain.Main(0xe10790)
	/home/afr/clones/gi/gimain/gimain.go:26 +0x49
main.main()
	/home/afr/clones/gi/examples/widgets/widgets.go:23 +0x2dF
```

When running the widget example in a virtual X server with `xvfb-run ./widgets`, the error message is the same.

**Comment by nodrygo** [comment]
I am very sad that doesn't work on my  _Linux Mint 19 (based Ubuntu)_ probably _Wayland based_
_gide_ and _widgets_ just open  a black screen
and  _xvfb-run  ./widgets_ end to:
```
2019/04/24 10:28:00 PlatformError: X11: RandR gamma ramp support seems broken
2019/04/24 10:28:00 oswin.glos failed to create hidden share window: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig
```
if somebody have clues  ?

**_goki_** seem very promising thanks to author

**Comment by rcoreilly** [comment]
I have *just now* checked in fixes for linux -- can you git pull and retry on widgets?
it is now using glfw and that should work on wayland, so if you could give it a test, that would be great.
the black screen was due to some issues in the new impl, which should now be fixed..

**Comment by rcoreilly** [comment]
@nodrygo btw try without the xvfb-run.. the fact that you got a black screen is actually promising.. :)

**Comment by nodrygo** [comment]
yeees now widgets work fine
good job thanks a lot

**Comment by xyproto** [comment]
The widget example now appears under Wayland/Sway here as well. Nicely done!
