### ISSUE TITLE
textbuf TextPos positions are in *runes* not bytes!!

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#212]
I'm in the process of fixing this, but we have not been very careful about the fact that textpos positions for TextView and TextBuf MUST be in runes, not bytes!

Should have a test document full of kanji etc and make sure it all works correctly.

**Comment by rcoreilly** [comment]
@rohrlich  : also current code is no longer doing spell checking for regular docs (markdown, latex) -- I'm fixing this now as well as fixing the issue of the comment syntax -- just adding those to TextBufOpts .

**Comment by rohrlich** [comment]
hmmm, was working yesterday but if it is broken now, it is! By fixing comments syntax you mean what, getting comment runes from lang?
