### ISSUE TITLE
add file info option for filenode -- just pulls up edit of info

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#216]
gives you full info about how it is parsing that file type, etc, and file size.  could add various functionality to the toolbar for it etc.

**Comment by rohrlich** [comment]
Take a look and let me know if this is what you wanted - just a struct view dialog of file node.

Did you want this editable? If so I'll add the ok/cancel and if not I'll make it readonly

**Comment by rohrlich** [comment]
I bet you just wanted the info part of the file node. I'll change it.

**Comment by rcoreilly** [comment]
yep that looks good. definitely should be inactive / read only -- editing any of those fields won't change anything and I think we want methods instead so you can do it on multiple selected ones.  e.g., permissions setting would be good to add at some point.. lowpri..

**Comment by rohrlich** [comment]
Done
