### ISSUE TITLE
crash clicking font family button in gide prefs

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#224]
rohrlich@MacBook-Pro-4:gide:> ./gide
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ角ゴシック w9, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ角ゴシック w8, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ角ゴシック w7, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ角ゴシック w6, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ角ゴシック w5, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ角ゴシック w4, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ角ゴシック w3, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ角ゴシック w2, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ角ゴシック w1, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ角ゴシック w0, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ明朝 pron, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font ヒラギノ丸ゴ pron w4, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font zapfino, removed from list
2018/11/25 21:40:36 gi.FontLib: error loading font signpainter, removed from list
fatal error: concurrent map read and map write

goroutine 4 [running]:
runtime.throw(0x4993afd, 0x21)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc00a185b20 sp=0xc00a185af0 pc=0x402dc52
runtime.mapaccess1_faststr(0x48340a0, 0xc00065b8c0, 0xc0075cbb70, 0xc, 0x2)
	/usr/local/go/src/runtime/map_faststr.go:21 +0x418 fp=0xc00a185b90 sp=0xc00a185b20 pc=0x4014818
github.com/goki/gi/gi.(*FontLib).Font(0x56bc860, 0xc0075cbb70, 0xc, 0x1e, 0x0, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/font.go:743 +0xc6 fp=0xc00a185c68 sp=0xc00a185b90 pc=0x44ee046
github.com/goki/gi/gi.(*FontStyle).OpenFont(0xc000288f30, 0xc003888d7c)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/font.go:357 +0xfa fp=0xc00a185cf0 sp=0xc00a185c68 pc=0x44eccfa
github.com/goki/gi/gi.(*TextRender).SetHTMLPre(0xc006c6ea00, 0xc0005ea4ad, 0xaa, 0xaa, 0xc0002881b0, 0xc003888cf8, 0xc003888d7c, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/text.go:1445 +0x1a57 fp=0xc00a186730 sp=0xc00a185cf0 pc=0x4536687
github.com/goki/gi/giv.(*TextView).LayoutLines(0xc003888a00, 0x1, 0xe, 0x0, 0xf)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:600 +0x239 fp=0xc00a1867c0 sp=0xc00a186730 pc=0x465cb49
github.com/goki/gi/giv.(*TextView).LinesInserted(0xc003888a00, 0xc0003cc640)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:331 +0x415 fp=0xc00a186898 sp=0xc00a1867c0 pc=0x465aed5
github.com/goki/gi/giv.TextViewBufSigRecv(0x4b8c5c0, 0xc003888a00, 0x4b8be40, 0xc0004cf180, 0x2, 0x4862ec0, 0xc0003cc640)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:370 +0x17c fp=0xc00a1868d8 sp=0xc00a186898 pc=0x465b59c
github.com/goki/ki.(*Signal).Emit(0xc0004cf458, 0x4b8be40, 0xc0004cf180, 0x2, 0x4862ec0, 0xc0003cc640)
	/Users/rohrlich/go/src/github.com/goki/ki/signal.go:167 +0x1e6 fp=0xc00a1869b0 sp=0xc00a1868d8 pc=0x41da4e6
github.com/goki/gi/giv.(*TextBuf).AppendTextMarkup(0xc0004cf180, 0xc006b4d100, 0x52b, 0x700, 0xc0005ea000, 0x86b, 0xc00, 0x100, 0x86a)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textbuf.go:786 +0x209 fp=0xc00a186a78 sp=0xc00a1869b0 pc=0x464d5f9
github.com/goki/gide/gide.(*Console).MonitorErr(0x56bd8e0)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/console.go:124 +0x936 fp=0xc00a187fd8 sp=0xc00a186a78 pc=0x4746886
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00a187fe0 sp=0xc00a187fd8 pc=0x405b551
created by github.com/goki/gide/gide.(*Console).Init
	/Users/rohrlich/go/src/github.com/goki/gide/gide/console.go:50 +0x188

**Comment by rohrlich** [comment]
Got this again when I clicked on the font family button in gide prefs.

rohrlich@MacBook-Pro-4:gide:> ./gide
2018/11/27 10:25:08 gi.FontLib: error loading font ヒラギノ角ゴシック w9, removed from list
fatal error: concurrent map read and map write

goroutine 25 [running]:
runtime.throw(0x49939fd, 0x21)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc00b1db790 sp=0xc00b1db760 pc=0x402d6c2
runtime.mapaccess2_faststr(0x4834240, 0xc0005e78c0, 0xc00df72f24, 0x2, 0x0, 0x696d756964654d20)
	/usr/local/go/src/runtime/map_faststr.go:110 +0x458 fp=0xc00b1db800 sp=0xc00b1db790 pc=0x40146f8
github.com/goki/gi/gi.(*FontLib).FontAvail(0x56bc880, 0xc00df72f20, 0x2, 0x9)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/font.go:715 +0x51 fp=0xc00b1db840 sp=0xc00b1db800 pc=0x44ed831
github.com/goki/gi/gi.addUniqueFontRobust(0xc00b1db948, 0xc00df72f20, 0x2, 0x2)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/font.go:161 +0x45 fp=0xc00b1db8a8 sp=0xc00b1db840 pc=0x44eb5f5
github.com/goki/gi/gi.FontAlts(0xc00061cb10, 0x9, 0xc017f0b180, 0x0, 0x14, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/font.go:208 +0x1f9 fp=0xc00b1db938 sp=0xc00b1db8a8 pc=0x44ebbb9
github.com/goki/gi/gi.FontFaceName(0xc00061cb10, 0x9, 0x900000000, 0x0, 0x56de4c0, 0xc00b1dba00)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/font.go:265 +0xda fp=0xc00b1dba08 sp=0xc00b1db938 pc=0x44ebf3a
github.com/goki/gi/gi.(*FontStyle).FaceNm(0xc003913470, 0xc003913348, 0x4ba44a0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/font.go:240 +0x4d fp=0xc00b1dba48 sp=0xc00b1dba08 pc=0x44ebe2d
github.com/goki/gi/gi.(*FontStyle).OpenFont(0xc003913470, 0xc00391357c)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/font.go:348 +0x35 fp=0xc00b1dbad0 sp=0xc00b1dba48 pc=0x44ec6a5
github.com/goki/gi/gi.(*Style).SetUnitContext(0xc003913348, 0xc000766000, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/style.go:273 +0xee fp=0xc00b1dbaf0 sp=0xc00b1dbad0 pc=0x452284e
github.com/goki/gi/gi.(*WidgetBase).Style2DWidget(0xc003913200)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/widget.go:166 +0x494 fp=0xc00b1dbbe0 sp=0xc00b1dbaf0 pc=0x45452d4
github.com/goki/gi/gi.(*Label).StyleLabel(0xc003913200)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/label.go:323 +0x42 fp=0xc00b1dbc70 sp=0xc00b1dbbe0 pc=0x44f91b2
github.com/goki/gi/gi.(*Label).Style2D(0xc003913200)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/label.go:348 +0x2b fp=0xc00b1dbc90 sp=0xc00b1dbc70 pc=0x44f966b
github.com/goki/gi/gi.(*Node2DBase).Style2DTree.func1(0x4b7e7a0, 0xc003913200, 0x0, 0x4906e00, 0xc003913200, 0xc00032eb01)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:560 +0x51 fp=0xc00b1dbcc8 sp=0xc00b1dbc90 pc=0x45629d1
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc003913200, 0x0, 0x4906e00, 0xc003913200, 0x49d77c8, 0x4ba4901)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1039 +0x98 fp=0xc00b1dbd40 sp=0xc00b1dbcc8 pc=0x41d0578
github.com/goki/gi/gi.(*Node2DBase).Style2DTree(0xc003913200)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:555 +0xb2 fp=0xc00b1dbd88 sp=0xc00b1dbd40 pc=0x4509902
github.com/goki/gi/gi.(*WidgetBase).ReRender2DTree(0xc003913200)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/widget.go:393 +0x184 fp=0xc00b1dbe68 sp=0xc00b1dbd88 pc=0x4546e24
github.com/goki/gi/gi.(*WidgetBase).FullReRenderIfNeeded(0xc003913200, 0x4ba44a0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/widget.go:318 +0xd9 fp=0xc00b1dbee8 sp=0xc00b1dbe68 pc=0x45466e9
github.com/goki/gi/gi.(*Label).Render2D(0xc003913200)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/label.go:383 +0x31 fp=0xc00b1dbf28 sp=0xc00b1dbee8 pc=0x44f9a21
github.com/goki/gi/gi.(*Layout).Render2DChildren(0xc0024d5738)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1287 +0x111 fp=0xc00b1dbf80 sp=0xc00b1dbf28 pc=0x4500401
github.com/goki/gi/gi.(*Layout).Render2D(0xc0024d5738)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1896 +0xd0 fp=0xc00b1dbfb8 sp=0xc00b1dbf80 pc=0x4502bf0
github.com/goki/gi/gi.(*Node2DBase).Render2DTree(0xc0024d5738)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:632 +0xb2 fp=0xc00b1dbff8 sp=0xc00b1dbfb8 pc=0x4509eb2
github.com/goki/gi/gi.(*PartsWidgetBase).Render2DParts(0xc0024d5300)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/widget.go:788 +0x33 fp=0xc00b1dc010 sp=0xc00b1dbff8 pc=0x4549dd3
github.com/goki/gi/gi.(*ButtonBase).Render2D(0xc0024d5300)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:617 +0x10f fp=0xc00b1dc050 sp=0xc00b1dc010 pc=0x44d666f
github.com/goki/gi/gi.(*Layout).Render2DChildren(0xc000330100)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1287 +0x111 fp=0xc00b1dc0a8 sp=0xc00b1dc050 pc=0x4500401
github.com/goki/gi/gi.(*Frame).Render2D(0xc000330100)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/frame.go:151 +0xce fp=0xc00b1dc0e0 sp=0xc00b1dc0a8 pc=0x44f168e
github.com/goki/gi/gi.(*Layout).Render2DChildren(0xc00023d180)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1287 +0x111 fp=0xc00b1dc138 sp=0xc00b1dc0e0 pc=0x4500401
github.com/goki/gi/gi.(*TabView).Render2D(0xc00023d180)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/tabview.go:437 +0xc0 fp=0xc00b1dc170 sp=0xc00b1dc138 pc=0x4529ec0
github.com/goki/gi/gi.(*Node2DBase).Render2DTree(0xc00023d180)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:632 +0xb2 fp=0xc00b1dc1b0 sp=0xc00b1dc170 pc=0x4509eb2
github.com/goki/gi/gi.(*Viewport2D).ReRender2DNode(0xc000766000, 0x8e778e8, 0xc00023d180)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/viewport2d.go:240 +0xea fp=0xc00b1dc268 sp=0xc00b1dc1b0 pc=0x4541b5a
github.com/goki/gi/gi.SignalViewport2D(0x4b82ee0, 0xc000766000, 0x4b823a0, 0xc00023d180, 0x1, 0x48024c0, 0xc017d33f88)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/viewport2d.go:574 +0x292 fp=0xc00b1dc458 sp=0xc00b1dc268 pc=0x4543682
github.com/goki/ki.(*Signal).Emit(0xc00023d1d8, 0x4b823a0, 0xc00023d180, 0x1, 0x48024c0, 0xc017d33f88)
	/Users/rohrlich/go/src/github.com/goki/ki/signal.go:167 +0x1e6 fp=0xc00b1dc530 sp=0xc00b1dc458 pc=0x41d9f56
github.com/goki/ki.(*Node).UpdateEnd(0xc00023d180, 0xc00395d401)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1178 +0x206 fp=0xc00b1dc5a8 sp=0xc00b1dc530 pc=0x41d11e6
github.com/goki/gi/gi.(*TabView).SelectTabIndex(0xc00023d180, 0x0, 0x7, 0x4ba4900, 0xc00395d400)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/tabview.go:181 +0x174 fp=0xc00b1dc618 sp=0xc00b1dc5a8 pc=0x4527ca4
github.com/goki/gide/gide.(*Gide).SelectMainTabByName(0xc00014fb00, 0x49484aa, 0x7, 0x4b90c20, 0xc00014fb00, 0x568c320, 0xc003936c30)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/gide.go:1133 +0xc5 fp=0xc00b1dc688 sp=0xc00b1dc618 pc=0x4752af5
github.com/goki/gide/gide.(*Gide).OpenConsoleTab.func1(0x4b90c20, 0xc00014fb00, 0x4b8bd60, 0xc0002a1c00, 0x1, 0x47f9720, 0x56de4c0)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/gide.go:1447 +0x7d fp=0xc00b1dc6d0 sp=0xc00b1dc688 pc=0x477130d
github.com/goki/ki.(*Signal).Emit(0xc0002a1ed8, 0x4b8bd60, 0xc0002a1c00, 0x1, 0x47f9720, 0x56de4c0)
	/Users/rohrlich/go/src/github.com/goki/ki/signal.go:167 +0x1e6 fp=0xc00b1dc7a8 sp=0xc00b1dc6d0 pc=0x41d9f56
github.com/goki/gi/giv.(*TextBuf).Refresh(0xc0002a1c00)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textbuf.go:368 +0xa6 fp=0xc00b1dc7f8 sp=0xc00b1dc7a8 pc=0x464a506
github.com/goki/gi/giv.(*TextBuf).New(0xc0002a1c00, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textbuf.go:402 +0x38c fp=0xc00b1dc848 sp=0xc00b1dc7f8 pc=0x464a8bc
github.com/goki/gi/giv.(*TextBuf).InsertText(0xc0002a1c00, 0x0, 0x0, 0xc0098b6230, 0x6b, 0x70, 0x0, 0xaa)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textbuf.go:1406 +0x1158 fp=0xc00b1dc9b0 sp=0xc00b1dc848 pc=0x4651f88
github.com/goki/gi/giv.(*TextBuf).AppendTextMarkup(0xc0002a1c00, 0xc0098b6230, 0x6b, 0x70, 0xc011212370, 0xab, 0xb0, 0x100, 0xb0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textbuf.go:772 +0x9a fp=0xc00b1dca78 sp=0xc00b1dc9b0 pc=0x464cfba
github.com/goki/gide/gide.(*Console).MonitorErr(0x56bd900)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/console.go:124 +0x936 fp=0xc00b1ddfd8 sp=0xc00b1dca78 pc=0x4746786
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00b1ddfe0 sp=0xc00b1ddfd8 pc=0x405afc1
created by github.com/goki/gide/gide.(*Console).Init
	/Users/rohrlich/go/src/github.com/goki/gide/gide/console.go:50 +0x188

goroutine 1 [syscall, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver._Cfunc_startDriver()
	_cgo_gotypes.go:727 +0x41
github.com/goki/gi/oswin/driver/macdriver.startDriver()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:107 +0x3b
github.com/goki/gi/oswin/driver/macdriver.Main(0xc000586b70)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/macdriver.go:27 +0x35
github.com/goki/gi/oswin/driver.main(0xc000586b70)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver_darwin.go:20 +0x2b
github.com/goki/gi/oswin/driver.Main(0xc000586b70)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver.go:27 +0x2b
github.com/goki/gi/gimain.Main(0x49d86f0)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:26 +0x57
main.main()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:20 +0x2d

goroutine 37 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0x56dda08)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0x56dda00)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
main.mainrun()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:86 +0x20c
main.main.func1()
	/Users/rohrlich/go/src/github.com/goki/gide/cmd/gide/gide.go:21 +0x20
github.com/goki/gi/gimain.Main.func1(0x4b4e080, 0x568c000)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:27 +0x24
github.com/goki/gi/oswin/driver/macdriver.driverStarted.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:190 +0x40
created by github.com/goki/gi/oswin/driver/macdriver.driverStarted
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:189 +0x5f

goroutine 24 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x8e51750, 0x72, 0xc0006d88e8)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00064d4b8, 0x72, 0xffffffffffffff01, 0x4b23200, 0x5421e98)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00064d4b8, 0xc00068a001, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00064d4a0, 0xc00068a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1d6
os.(*File).read(0xc0004f13a8, 0xc00068a000, 0x1000, 0x1000, 0x0, 0x0, 0xc0006d89f0)
	/usr/local/go/src/os/file_unix.go:249 +0x4e
os.(*File).Read(0xc0004f13a8, 0xc00068a000, 0x1000, 0x1000, 0x1000, 0x1000, 0x405c830)
	/usr/local/go/src/os/file.go:108 +0x69
bufio.(*Scanner).Scan(0xc0006d8c88, 0x54ff8a1)
	/usr/local/go/src/bufio/scan.go:213 +0xa6
github.com/goki/gide/gide.(*Console).MonitorOut(0x56bd900)
	/Users/rohrlich/go/src/github.com/goki/gide/gide/console.go:61 +0x1cb
created by github.com/goki/gide/gide.(*Console).Init
	/Users/rohrlich/go/src/github.com/goki/gide/gide/console.go:49 +0x166

goroutine 26 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc0004a4600, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:237 +0x220
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:180 +0xe8

goroutine 4 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0004a46a0, 0x367)
	/usr/local/go/src/runtime/sema.go:510 +0xeb
sync.(*Cond).Wait(0xc0004a4690)
	/usr/local/go/src/sync/cond.go:56 +0x92
github.com/goki/gi/oswin/driver/internal/event.(*Deque).NextEvent(0xc0004a4688, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/internal/event/event.go:55 +0x77
github.com/goki/gi/oswin/driver/macdriver.(*windowImpl).NextEvent(0xc0004a4600, 0xc000000005, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/window.go:103 +0x33
github.com/goki/gi/gi.(*Window).EventLoop(0xc00034ed80)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1217 +0x1a6
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:699 +0x94

goroutine 41 [chan receive]:
github.com/goki/gi/gi.TextFieldBlink()
	/Users/rohrlich/go/src/github.com/goki/gi/gi/textfield.go:753 +0x6b
created by github.com/goki/gi/gi.(*TextField).StartCursor
	/Users/rohrlich/go/src/github.com/goki/gi/gi/textfield.go:801 +0x19c

goroutine 6 [chan receive]:
github.com/goki/gi/giv.TextViewBlink()
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:2821 +0x6b
created by github.com/goki/gi/giv.(*TextView).StartCursor
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:2869 +0x19c

goroutine 30 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc0004e7980, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:237 +0x220
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:180 +0xe8

goroutine 31 [runnable]:
unicode.ToLower(0xc000003099, 0x24)
	/usr/local/go/src/unicode/letter.go:264 +0x68
strings.Map(0x49d8db0, 0xc000674e16, 0x24, 0xc0182b1e60, 0x1a)
	/usr/local/go/src/strings/strings.go:474 +0x83
strings.ToLower(0xc000674e16, 0x24, 0xc0182b1e60, 0x1a)
	/usr/local/go/src/strings/strings.go:612 +0x74
github.com/goki/gi/gi.(*FontLib).DeleteFont(0x56bc880, 0xc014195e00, 0x24)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/font.go:773 +0x107
github.com/goki/gi/gi.(*FontLib).Font(0x56bc880, 0xc014195e00, 0x24, 0x18, 0x0, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/font.go:755 +0x3d7
github.com/goki/gi/gi.(*FontLib).OpenAllFonts(0x56bc880, 0x18)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/font.go:788 +0xb5
github.com/goki/gi/giv.FontChooserDialog(0xc015c72a80, 0x496c5f6, 0xd, 0x47df6d0, 0x21, 0x0, 0x0, 0x0, 0x0, 0x4b86720, ...)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/dialogs.go:256 +0x8d
github.com/goki/gi/giv.(*FontValueView).Activate(0xc005545ce0, 0xc015c72a80, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/fontvalueview.go:64 +0x1b5
github.com/goki/gi/giv.(*FontValueView).ConfigWidget.func1(0x4b86720, 0xc005545ce0, 0x4b7be60, 0xc00b630c80, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/fontvalueview.go:49 +0xa3
github.com/goki/ki.(*Signal).Emit(0xc00b632550, 0x4b7be60, 0xc00b630c80, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/signal.go:167 +0x1e6
github.com/goki/gi/gi.(*Action).ButtonRelease(0xc00b630c80)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/action.go:210 +0x10f
github.com/goki/gi/gi.(*ButtonBase).MouseEvent.func1(0x4b7be60, 0xc00b630c80, 0x4b83660, 0xc00034fb00, 0x0, 0x48abf40, 0xc013b87f00)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:414 +0xcb
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc000603b98, 0x4b83660, 0xc00034fb00, 0x0, 0x48abf40, 0xc013b87f00)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1707 +0x6d
github.com/goki/gi/gi.(*Window).SendEventSignal(0xc00034fb00, 0x4b31380, 0xc013b87f00, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1851 +0x527
github.com/goki/gi/gi.(*Window).EventLoop(0xc00034fb00)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1574 +0x153a
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:699 +0x94
rohrlich@MacBook-Pro-4:gide:>

**Comment by rcoreilly** [comment]
see latest checkin -- I think that should cover it but you might want to double-check -- I only looked at FontsAvail access which was not properly guarded with mutexes, but there might be other unprotected maps etc that I didn't check..

**Comment by rohrlich** [comment]
I didn't see anything missed
