### ISSUE TITLE
Cursor should disappear and be re-rendered on scroll

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#225]
Has it always been like this? Is this a side-effect of my scope matching code? Can you reproduce?

**Comment by rohrlich** [comment]
So, only happens when I use the scroll bar which I rarely do. Normally 2 fingers on track pad.

**Comment by rohrlich** [comment]
The cursor position is not getting moved. The problem is that the visible cursor is not getting redrawn so   it looks like the logical one is in the wrong location.

A side problem is that the highlight on scopes is disappearing in the redraw so scrolling to see the matching brace, etc. is futile! I'll look to see what is causing this latter problem and fix that.

**Comment by rohrlich** [comment]
problem with scope highlighting disappearing on scroll is now fixed

**Comment by rcoreilly** [comment]
seems to be fixed now -- can't replicate.
