### ISSUE TITLE
himarkup crash

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#227]
I've gotten this twice now -- stared at the code but can't find the issue..  likely a missing mutex.

oreilly@shadow:~/goki/gide/cmd/gide/ > panic: runtime error: slice bounds out of range

goroutine 1887 [running]:
github.com/goki/gi/giv.(*HiMarkup).MarkupLine(0xc020a5a890, 0xc017742f40, 0x8, 0x8, 0xc033c96f30, 0x1, 0x1, 0xc0204f4050, 0x2, 0x2, ...)
	/Users/oreilly/go/src/github.com/goki/gi/giv/himarkup.go:287 +0x1498
github.com/goki/gi/giv.(*TextBuf).MarkupLines(0xc020a5a700, 0xa, 0xc, 0xc007d380c0)
	/Users/oreilly/go/src/github.com/goki/gi/giv/textbuf.go:1818 +0x2a2
github.com/goki/gi/giv.(*TextBuf).LinesInserted(0xc020a5a700, 0xc03ee80320)
	/Users/oreilly/go/src/github.com/goki/gi/giv/textbuf.go:1687 +0xd60
github.com/goki/gi/giv.(*TextBuf).InsertText(0xc020a5a700, 0xa, 0x0, 0xc033c96e10, 0x24, 0x30, 0x101, 0xc0339c45a0)
	/Users/oreilly/go/src/github.com/goki/gi/giv/textbuf.go:1554 +0x84e
github.com/goki/gi/giv.(*TextView).InsertAtCursor(0xc0400db500, 0xc033c96e10, 0x24, 0x30)
	/Users/oreilly/go/src/github.com/goki/gi/giv/textview.go:2337 +0x155
github.com/goki/gi/giv.(*TextView).Paste(0xc0400db500)
	/Users/oreilly/go/src/github.com/goki/gi/giv/textview.go:2324 +0x1bf
github.com/goki/gi/giv.(*TextView).KeyInput(0xc0400db500, 0xc037926930)
	/Users/oreilly/go/src/github.com/goki/gi/giv/textview.go:3799 +0x109d
github.com/goki/gi/giv.(*TextView).TextViewEvents.func4(0x4b8c3a0, 0xc0400db500, 0x4b83520, 0xc009322000, 0x7, 0x48ad8a0, 0xc037926930)
	/Users/oreilly/go/src/github.com/goki/gi/giv/textview.go:4105 +0x8a
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc01aaabb98, 0x4b83520, 0xc009322000, 0x7, 0x48ad8a0, 0xc037926930)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1707 +0x6d
github.com/goki/gi/gi.(*Window).SendEventSignal(0xc009322000, 0x4b31060, 0xc037926930, 0x1)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1851 +0x527
github.com/goki/gi/gi.(*Window).EventLoop(0xc009322000)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1574 +0x153a
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:699 +0x94

**Comment by rohrlich** [comment]
Tips on reproducing?

**Comment by rcoreilly** [comment]
random and rare.. pasting the last time...  will be changing all this soon anyway..

**Comment by rcoreilly** [comment]
I'm pretty sure I found the issue and fixed this -- was not all under mutex.
