### ISSUE TITLE
textview: open file, make changes, save, undo all, then save

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#229]
it reverts back to your first saved file!  changed flag gets turned off but incorrectly..

**Comment by rcoreilly** [comment]
more general issue: do want to keep undo even after saving, so you can undo saved changes when you reconsider them, but somehow need to flag point in undo stack where the save occured?  that would seem to solve the problem.

**Comment by rohrlich** [comment]
I think the question is whether save is to protect you from loss in case of crash, etc or if save is about versioning. I use save as the former and want to be able to undo past a save.

**Comment by rcoreilly** [comment]
yes keeping undo past save.  and finally fixed this bugaboo.  EditDone() was only operating if Changed() flag was true, but that logic is not correct -- it must always get current state regardless of changed flag.    actually, now that I think of it, the problem is the changed flag -- it should not register as unchanged if you undo all the way *after a save*.

now I see my previous comments above to this effect -- once we have that record in the undo map, then we can fix the changed flag properly.  in the meantime, proximal bug is fixed.
