### ISSUE TITLE
If you delete keymap prefs app will not run 

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#231]
Possibly because *viewport is nil at this point

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x452d5db]

goroutine 8 [running]:
github.com/goki/gi/gi.(*TextRender).LayoutStdLR(0xc0000c3df0, 0xc0000c34f8, 0xc0000c3470, 0xc0000c357c, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/text.go:1823 +0xdb
github.com/goki/gi/gi.(*Label).SetText(0xc0000c3200, 0x48bb533, 0x2)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/label.go:147 +0x1ba
github.com/goki/gi/gi.(*PartsWidgetBase).ConfigPartsSetIconLabel(0xc0000f4600, 0x0, 0x0, 0x48bb533, 0x2, 0xffffffffffffffff, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/widget.go:836 +0x1ef
github.com/goki/gi/gi.(*ButtonBase).ConfigParts(0xc0000f4600)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:545 +0x2b4
github.com/goki/gi/gi.(*ButtonBase).SetText(0xc0000f4600, 0x48bb533, 0x2)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:177 +0xff
github.com/goki/gi/gi.(*Dialog).StdButtonConnect(0xc0005b8000, 0xc000570001, 0xc0005c8a00)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:392 +0x1d3
github.com/goki/gi/gi.(*Dialog).StdDialog(0xc0005b8000, 0x48ed3b0, 0xe, 0xc0001620a0, 0x50, 0xc000700001)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:426 +0x126
github.com/goki/gi/gi.NewStdDialog(0x48ed3b0, 0xe, 0xc0001620a0, 0x50, 0x0, 0x1, 0xc0001620a0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:455 +0x12a
github.com/goki/gi/gi.PromptDialog(0x0, 0x48ed3b0, 0xe, 0xc0001620a0, 0x50, 0x0, 0xc000540001, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/dialogs.go:479 +0x5b
github.com/goki/gi/gi.(*KeyMaps).OpenJSON(0x558bd80, 0xc0000a82d0, 0x30, 0xc0000a82d0, 0x30)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/keyfun.go:318 +0x15f
github.com/goki/gi/gi.(*KeyMaps).OpenPrefs(0x558bd80, 0x73b, 0x93b)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/keyfun.go:345 +0xbb
github.com/goki/gi/gi.(*Preferences).Open(0x558e960, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/prefs.go:167 +0x198
github.com/goki/gi/gi.Init()
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:667 +0xce
github.com/goki/gi/gi.NewWindow2D(0x48f9f0f, 0x12, 0x48f8d57, 0x12, 0x400, 0x300, 0x1, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:282 +0x26
main.mainrun()
	/Users/rohrlich/go/src/github.com/goki/gi/examples/textview/textview.go:41 +0xd7
main.main.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/examples/textview/textview.go:28 +0x20
github.com/goki/gi/gimain.Main.func1(0x4ab4a20, 0x555d0e0)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:27 +0x24
github.com/goki/gi/oswin/driver/macdriver.driverStarted.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:190 +0x40
created by github.com/goki/gi/oswin/driver/macdriver.driverStarted
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:189 +0x5f

**Comment by rcoreilly** [comment]
hasn't come up again presumably / not sure if still an issue. reopen with instructions to replicate if so (just removing prefs.json doesn't cause the crash).
