### ISSUE TITLE
FileTreeView missing drop menu that TreeView has

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#241]

**Comment by rohrlich** [comment]
Also, shift drop is unreliable in getting move - often does copy

**Comment by rcoreilly** [comment]
look at giv/filetree.go:1229 -- Drop and subsequent PasteMime methods - and compare with comparable methods from TreeView -- could easily add a drop popup but do we want to?  seems like the desired action is clear from shortcuts.

also I've been having reliable move / copy behavior in my tests -- can you replicate now?
