### ISSUE TITLE
FileNode: checking for vers ctrl on each node seems very laggy

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#242]
the highlighting of nodes that are not under VC is very cool, but opening the tree view seems very laggy, especially in larger projects (e.g., when I opened the golang std library tree which I often do).

probably need to have a separate process that does the checking, only once?  UpdateNode is called frequently, so not great to have it there.  Also you definitely want to cache the result of "UsesGit" in the root instead of searching every time!!  that would speed things up a lot.

also I just looked at this code for the first time - would be better to have a more generalized framework that isn't just git or svn -- there are various other VCS's that people use.. we may not support immediately but want to have a generalizable framework..

Ideally make an interface that does all the relevant VC functions, and define that for the relevant instances, and then cache the relevant instance once you figure out (one time only, in the root node) which vc it is using.  Then you just call those interface methods and it is very nice :)

I just did a quick search and there is a similar approach here: https://github.com/Masterminds/vcs -- not sure if it has all the relevant functions but if not, maybe better to add to it and see if they'll take a PR and if not, fork from there..

they also reference: https://godoc.org/golang.org/x/tools/go/vcs which might be relevant.

**Comment by rohrlich** [comment]
Mastermind has a lot of api for high level vcs stuff that we don't have and it has a generic function for executing a command that is similar to what I wrote for doing add, delete, move etc. I think a separate interface for those actions along with the interface from mastermind will work well and I'll cache the vcs type in root. Not sure why they didn't include the basic add, delete, move in the api and went with the general exec.cmd but I think that is fine and you need the general function anyway. Thanks for reviewing the code.

**Comment by rohrlich** [comment]
The new implementation sets the flag on the file node when the directory is opened. After that the flag is simply checked. If you call Add on the repo the flag is also set then and if you do a remove from repo while keeping a local copy of file the flag is set to false. Seems to be pretty quick.

I threw away all of the prior vcs code and rewrote using mastermind vcs and an interface that includes funcs for add, remove, move, etc that we can continue to add to. I've only implemented the Git calls but adding svn or any other is a trivial matter now that we have the interface.
