### ISSUE TITLE
spell check not correcting sometimes: just always check!

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#248]
I'm occasionally getting some stray cases of correctly-spelled words remaining marked as incorrect.  I think we should probably just always update spell check on every key input.  For sure if you e.g., go down a line after fixing spelling in the middle of a word, it doesn't update, but I've also had issues when just correcting and going forward, though it is not easily replicable..  I'll fix this..

**Comment by rohrlich** [comment]
Yes, seeing this also.

**Comment by rcoreilly** [comment]
added full line update on up / down arrow -- seems fixed now.
