### ISSUE TITLE
filetree dnd issues

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#250]
I just did a move drag of a file into a new folder, and it copied (did not move) the *wrong* file!  it was the first file in the source dir but not the one I had dragged.

**Comment by rcoreilly** [comment]
also I think it did not add it to vcs -- was red..

**Comment by rcoreilly** [comment]
likely specific to folder being (a) New or (b) empty  or (c) Closed -- tried again with a diff file and it got the right file, but didn't delete the original, and definitely did not do add.

looks like some more debugging and bugfixing in this is needed.

**Comment by rohrlich** [comment]
I haven't tried dnd since your last updates to it but I'll take a look and fix. We had decided not to add to vcs on copy so what you saw is by design.

**Comment by rcoreilly** [comment]
I added code (which apparently doesn't work) to add to vcs if the source was in vcs... so we didn't want a dialog but that "auto add" approach seems reasonable..

**Comment by rohrlich** [comment]
ok

**Comment by rcoreilly** [comment]
another thing to test / fix is the gide buffers connected to files that are renamed / deleted.  recent experience suggests these are not getting properly updated..  E.g., I just renamed a file that had an open buffer and the textview still said it was editing the old file name.  And I think in one earlier case a deleted buffer didn't close, but I'm not 100% sure about that -- during cleanup of DND move that didn't work..

**Comment by rohrlich** [comment]
What application were you using when first reporting the bug, gide or pie? I'm finding with gide that I get  a "could not find filenode at path:" and thus no copy or move. I'm going to start by tracking down this problem which I don't get with filetree example. Might be related to files in/out of git.

**Comment by rcoreilly** [comment]
gide.  pie doesn't use filetree..  is this the same as #251 ?

**Comment by rohrlich** [comment]
The original bug is intermittently reproducible. Here I have captured key information. In the first image you can see that fooFive was dragged from temp/ to temp2/ and copied. You should be able to see the ghost of fooFive.go. Now look at the second image, where the delete of the src occurs, and you will see that path is /temp/fooFour.go (look above the dark blue line showing the line being executed). This narrows the problem and hopefully I can track down the cause.

![screen shot 2019-01-15 at 10 30 35 am](https://user-images.githubusercontent.com/22350787/51198680-33929300-18b2-11e9-8b85-bf586a2aea9a.png)

![screen shot 2019-01-15 at 10 30 46 am](https://user-images.githubusercontent.com/22350787/51198661-24abe080-18b2-11e9-9b7c-0852bab62d9b.png)

**Comment by rohrlich** [comment]
Looks like the problem is that when the second event, the DropFmSource event is generated (first event is DropOnTarget) we aren't finding the correct node because now the tree has been updated with the insertion of the copy.

**Comment by rohrlich** [comment]
Well now I think the problem is more basic as sometimes Dragged() is never reached, that is, the delete part of the move is never called.

**Comment by rcoreilly** [comment]
all of this has been extensively reworked and should be fixed now.  there were numerous issues :)
