### ISSUE TITLE
from Kai O: rename KiT -> T

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#252]
@kplat1 -- given that you have to type KiT a fair amount in constructing new gui elements, it would be a lot easier if it was just T_ -- it would of course break all existing code but is just one big easy rename to fix.. thoughts anyone?

**Comment by rohrlich** [comment]
Given that I can type "var K" (or whatever) and invoke completion I have no problem. If it were just T I would type "var T" and invoke completion.

**Comment by rcoreilly** [comment]
After further consideration, someone MIGHT use T_ for something else, and KiT tells you very clearly that this is the Ki type registry, and it's just 3 letters, so let's just keep it as-is..
