### ISSUE TITLE
Completion not giving correct completion based on seed

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#258]
Seems very broken - hard to know what to give as an example (* means complete)

Sometimes it gives the correct completions for something like tv.* or strings.* but doesn't use the seed which follows but sometimes it gives completions for the wrong string entirely, e.g. if I previously typed tv.* and now I type strings.* I get the completions for tv.*

**Comment by rohrlich** [comment]
Yes, sure.

**Comment by rohrlich** [comment]
Working now that I am trying to debug but this makes 3 mysterious problems. The other two are the depth coloring coming on and your parse errors that shouldn't be appearing.

**Comment by rcoreilly** [comment]
ok, new tickets filed under gide.
