### ISSUE TITLE
Material Design Components & Responsive Design

### ISSUE THREAD

**Issue by hubyhuby** [goki/gi#260]
1)
It would be nice to have a modern look user interface such as Material Design.
While starting a new GUI it could make sens to focus on the latest GUI trends.

2) Responsive Design :
Most users are now consuming GUIs from smartphones and tabletes.
A modern GUI shall adapt aswell to those devices easily to be adopted. 
Developping using a  GUI framework , even if you aim at desktop, will bring you at some point to port it to a smartphone or tablet (most of the time)

Example of other frame work following material design & responsive design : https://vuetifyjs.com/en/

**Comment by rcoreilly** [comment]
This is not something that I will have time to do, so unless someone else picks this up, it will not happen :). the mobile issues are major but the framework should work in principle, but it is not my need or expertise.

**Comment by kkoreilly** [comment]
All of these things have been implemented in v2, which is still under development.
