### ISSUE TITLE
completion - unsaved code not getting parsed

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#261]
I think this is a gi bug - the parse should be on the current text

**Comment by rohrlich** [comment]
Here is an example
foo := pf.Editor (where pf is Preferences and pf.Editor is of type EditorPrefs)
foo.* (where asterisk indicates complete this...)

even with saving this doesn't complete but that is due to a pi bug I will now file

**Comment by rcoreilly** [comment]
out of date.. new tickets filed under gide.
