### ISSUE TITLE
How to change button font size

### ISSUE THREAD

**Issue by moon004** [goki/gi#264]
As the title said, i tried to change the font size via SetProp for both the layout and the button, but it only width and height of button has change but not the text. There is also no font-size property on the var ButtonProps = ki.Props{ props here } in the file buttons.go (line 661). What is there proper way to change font size, or any button text font style? Im sorry if it seems elementary for you.

i'm sorry if this issue already existed and sorry for my bad english 😅

**Comment by rcoreilly** [comment]
SetProp(“font-size”, “24pt”) on the button object should work - you can just google css font size and that is the same property name - uses all those same standards.

**Comment by moon004** [comment]
I'm sorry, i tried that one but it's still not working. Maybe it must be some other props that caused it not to be big. Anyway it's okay now i came up with a different workaround for my problem. I'll close this issue for now.

**Comment by rcoreilly** [comment]
I was able to reproduce this issue and have just pushed a fix -- font-size was somehow missing from inherited font properties!  now it should work.  thanks for reporting this bug!

**Comment by moon004** [comment]
I see, haha, no wonder, i was troubleshooting so hard and yet couldn't find out the problem, hahaha, thanks buddy, goki is an awesome project! All the best @rcoreilly !
