### ISSUE TITLE
Slice visualization missing slice name

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#276]
I looked at this a long time ago and I didn't see how to get conveniently get the name.

**Comment by rcoreilly** [comment]
slices don't generally have names?  not sure what exactly the use-case is?

**Comment by rohrlich** [comment]
Well one use case is viewing a tables columns. I get a "Slice of float32:... Values" but I don't know which column I'm viewing. I guess this case will be a non-issue when we have a table view but the general case is looking at the values of an etensor and the name of the variable (e.g. MelPtsMel or MelPtsHz) is missing.

**Comment by rcoreilly** [comment]
similar issue reported by Tom Hazy in emer params -- can try following valueview path upwards to get full path of how we got to a given window.  to avoid having dangling pointers, just have a string field that accumulates the path whenever a child valueview is opened.

**Comment by rohrlich** [comment]
That sounds like a good idea.

**Comment by rcoreilly** [comment]
I think this is now sufficient.  open special cases where not..
