### ISSUE TITLE
Install on Linux 16.04 fails

### ISSUE THREAD

**Issue by davmaz** [goki/gi#287]
Following the directions in the package, this occurs:
go get -u ./...
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring ../../go.mod;
	see 'go help modules'
# github.com/go-gl/glfw/v3.2/glfw
In file included from ./glfw/src/internal.h:169:0,
                 from ./glfw/src/context.c:28,
                 from ../../../../go-gl/glfw/v3.2/glfw/c_glfw.go:4:
./glfw/src/x11_platform.h:39:33: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
compilation terminated.

**Comment by rcoreilly** [comment]
A bit down on the Install page is this key line for linux:

sudo apt-get install libgl1-mesa-dev xorg-dev

that will get you those includes :)
