### ISSUE TITLE
separator is broken and the last file in filetree may not be displayed

### ISSUE THREAD

**Issue by wiryls** [goki/gi#288]
I just build and run the examples and find something wrong. Part of those bugs are already reported in other issues. And there are still some.

After run `go run .\examples\widgets\`, I clicked `Open GoGiEditor`. And then moved cursor to the 
dots on the vertical separator, and scrolled it via a trackpad.

This picture shows what happends when scrolling:

![3](https://user-images.githubusercontent.com/7984500/62228658-b1526200-b3f0-11e9-8644-cc0c8f202ec3.png)

And also, I found the last element in filetree may not displayed. After I clicked `Open` and tried to find the `widgets` folder in `GOPATH\src\github.com\goki\gi\examples`, I failed.

![1](https://user-images.githubusercontent.com/7984500/62229079-84eb1580-b3f1-11e9-84d9-953e636429fb.png)

But if I resized the windows, it appeared.

![2](https://user-images.githubusercontent.com/7984500/62229153-ab10b580-b3f1-11e9-8156-292e21c373f3.png)

Then disappeared again if I scrolled this list.

By the way, I'm using Windows 10 (1903) with go version `go version go1.12.7 windows/amd64`

**Comment by rcoreilly** [comment]
Thanks for the reports.  That separator issue definitely doesn't happen on mac or linux -- windows is our least-well-tested platform so appreciate the bug report there.  That scrolling issue also appears to be platform-specific -- there is a known issue for very large lists, but this is a short list so it shouldn't happen here, and I definitely haven't seen that on Mac (though I'll have to test your specific example just to be sure).  Currently moving so it might be a few days.

**Comment by wiryls** [comment]
@rcoreilly Thanks for your answer! Hope my report helps.

And sorry, I've made some mistakes. Those two bugs happen when I run `.\examples\widgets\` but not `.\examples\filetree`. And also, it's not "separator" but "splitter".

**Comment by rcoreilly** [comment]
I have now seen the issue with the fileview chooser, repeatably, on my mac, so I can now fix that, soon!   also will be booting up windows soon so will fix the splitter issue as well.

**Comment by rcoreilly** [comment]
I have a quick fix for the rounding errors that were causing this scrolling bug, but the larger issue for #280 will require some more work, when I have more time..

**Comment by rcoreilly** [comment]
I'm not replicating the splitter issue now on windows -- closing this ticket.
