### ISSUE TITLE
Windows 10 - Installation issues

### ISSUE THREAD

**Issue by locojuhi** [goki/gi#290]
I've just follow up the docs to install this library but when I just want to try a basic examples it's says that some packages were not found. 

So It would be helpfull to understand how does this works to improove the installation docs.
I think it can be better.

Could you please at least update the installation on windows to get this working?

**Comment by rcoreilly** [comment]
If you could add more specific error messages that would be good.  I just tested on my virtual machine and it seemed to work fine for me.

**Comment by rcoreilly** [comment]
closing in the absence of more info at this point.

**Comment by ddkwork** [comment]
windows 11 hass error :

GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\Admin\go #gosetup
"C:\Program Files\Go\bin\go.exe" build -o C:\Users\Admin\AppData\Local\Temp\GoLand\___go_build_github_com_goki_gide_cmd_pie.exe github.com/goki/gide/cmd/pie #gosetup
C:\Users\Admin\AppData\Local\Temp\GoLand\___go_build_github_com_goki_gide_cmd_pie.exe
2022/08/18 21:10:00 vulkan warning: missing 1 required instance extensions during Config
panic: vulkan error: vulkan error: incompatible driver (-9) on C:/Users/Admin/go/pkg/mod/github.com/goki/vgpu@v1.0.5/vgpu/errors.go:23 (0x7ff79e72003e)
        NewError: pc, _, _, ok := runtime.Caller(0)


goroutine 1 [running, locked to thread]:
github.com/goki/vgpu/vgpu.IfPanic(...)
        C:/Users/Admin/go/pkg/mod/github.com/goki/vgpu@v1.0.5/vgpu/errors.go:40
github.com/goki/vgpu/vgpu.(*GPU).Config(0xc00047a400, {0x7ff79f58fb71?, 0x7ff79f5c1710?})
        C:/Users/Admin/go/pkg/mod/github.com/goki/vgpu@v1.0.5/vgpu/gpu.go:172 +0xbb5
github.com/goki/gi/oswin/driver/vkos.(*appImpl).initVk(0x7ff79f2e0020)
        C:/Users/Admin/go/pkg/mod/github.com/goki/gi@v1.3.7/oswin/driver/vkos/app.go:195 +0x413
github.com/goki/gi/oswin/driver/vkos.Main(0x7ff79ee1a4e0?)
        C:/Users/Admin/go/pkg/mod/github.com/goki/gi@v1.3.7/oswin/driver/vkos/app.go:74 +0x45
github.com/goki/gi/oswin/driver.driverMain(...)
        C:/Users/Admin/go/pkg/mod/github.com/goki/gi@v1.3.7/oswin/driver/driver_vkos.go:18
github.com/goki/gi/oswin/driver.Main(...)
        C:/Users/Admin/go/pkg/mod/github.com/goki/gi@v1.3.7/oswin/driver/driver.go:27
github.com/goki/gi/gimain.Main(0x7ff79f6857a8?)
        C:/Users/Admin/go/pkg/mod/github.com/goki/gi@v1.3.7/gimain/gimain.go:31 +0x57
main.main()
        C:/Users/Admin/Downloads/gi/gide/cmd/pie/pie.go:17 +0x25

Process finished with the exit code 2

**Comment by rcoreilly** [comment]
This is the relevant bit:
```
2022/08/18 21:10:00 vulkan warning: missing 1 required instance extensions during Config
panic: vulkan error: vulkan error: incompatible driver (-9) on 
```
Can you update your graphics drivers?  or google vulkan and the name of your GPU setup?
