### ISSUE TITLE
Be able to have mouse not move but still have mouse movement detected.

### ISSUE THREAD

**Issue by kplat1** [goki/gi#295]

**Comment by rcoreilly** [comment]
glfw was finally updated: https://www.glfw.org/docs/latest/news.html#wait_events_33

Support for raw mouse motion
GLFW now supports raw (unscaled and unaccelerated) mouse motion in disabled cursor mode with the GLFW_RAW_MOUSE_MOTION input mode. **Raw mouse motion input is not yet implemented on macOS.** Call glfwRawMouseMotionSupported to check if GLFW can provide raw mouse motion on the current system.

For more information see Raw mouse motion.

this will help!

**Comment by rcoreilly** [comment]
This is now supported via `oswin.Window.SetCursorEnabled` method -- works on everything except crostini (of course..)
