### ISSUE TITLE
Panic displaying grid when value is NAN

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#297]
Here is the stack trace - 

github.com/goki/gi/giv.(*ColorMap).Map(0xc000441740, 0x7ffc000000000000, 0x4f1)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/colormap.go:46 +0x2a9
github.com/emer/etable/etview.(*TensorGrid).Color(0xc0003bc500, 0x7ffc000000000000, 0x449e389e451d3200, 0x1)
	/Users/rohrlich/go/src/github.com/emer/etable/etview/tensorgrid.go:260 +0x59
github.com/emer/etable/etview.(*TensorGrid).RenderTensor(0xc0003bc500)
	/Users/rohrlich/go/src/github.com/emer/etable/etview/tensorgrid.go:354 +0xae9
github.com/emer/etable/etview.(*TensorGrid).Render2D(0xc0003bc500)
	/Users/rohrlich/go/src/github.com/emer/etable/etview/tensorgrid.go:366 +0xa8

**Comment by rohrlich** [comment]
For some values of Mel parameters you can get Mel values that are NaN. Also happens in C++ emergent but the display handles it.

**Comment by rcoreilly** [comment]
ps. not tested on actual nan values so reopen if it doesn't work!
