### ISSUE TITLE
add mutex's for all view updates?

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#299]
StructView, TreeView etc.  make them robust to parallel update triggers.

example case:  StructView usually does not explicitly update its fields (UpdateFields) b/c they are updated by user interaction or signals directly to the fields.  But if you have something changing from a parallel goroutine and want to trigger an update, then the call to UpdateFields can collide with other updates..  John has example of this.

**Comment by rohrlich** [comment]
example stack trace:
runtime.fatalpanic at panic.go:847
runtime.gopanic at panic.go:722
runtime.panicdottypeE at iface.go:255
runtime.panicdottypeI at iface.go:265
github.com/goki/gi/giv.(*FloatValueView).ConfigWidget at basicviews.go:642
github.com/goki/gi/giv.(*SliceViewInline).ConfigParts at sliceviewinline.go:110
github.com/goki/gi/giv.(*SliceViewInline).Render2D at sliceviewinline.go:216
github.com/goki/gi/gi.(*Layout).Render2DChildren at layout.go:1142
github.com/goki/gi/gi.(*Layout).Render2D at layout.go:1774
github.com/goki/gi/gi.(*Node2DBase).Render2DTree at node2d.go:711
github.com/goki/gi/gi.(*Viewport2D).ReRender2DNode at viewport.go:258
github.com/goki/gi/gi.(*Viewport2D).UpdateNode at viewport.go:701
github.com/goki/gi/gi.(*Viewport2D).UpdateNodes at viewport.go:682
github.com/goki/gi/gi.(*Viewport2D).NodeUpdated at viewport.go:581
github.com/goki/gi/gi.SignalViewport2D at viewport.go:535
github.com/goki/ki/ki.(*Signal).Emit at signal.go:162
github.com/goki/ki/ki.(*Node).UpdateEnd at node.go:1912
github.com/goki/gi/giv.(*StructView).UpdateField at structview.go:96
main.(*Sim).TrainTrial at audonly.go:672

**Comment by rcoreilly** [comment]
Viewport2D keeps a stack of nodes to update, with a mutex, and is thus generally robust for random UpdateStart / End updates. 

This trace indicates it is going through that path: UpdateNodes operates on the stacked nodes.

so it is not clear why this is not working.  I've pushed it pretty hard in standard Netview updates and also the new gi3d demo with animation, with no issues.  So somehow this is hitting a different path or something different is happening..

**Comment by rohrlich** [comment]
Perhaps this trace will be more helpful - Occurred with netview visible/running and mouse click on tree item to display sliceview. (trace has 2 goroutines)
panic: interface conversion: gi.Node2D is *gi.Action, not *gi.SpinBox

goroutine 25 [running]:
github.com/goki/gi/giv.(*FloatValueView).ConfigWidget(0xc060d936c0, 0x54b5820, 0xc026b7a000)
        /Users/rohrlich/go/src/github.com/goki/gi/giv/basicviews.go:655 +0x411
github.com/goki/gi/giv.(*SliceViewInline).ConfigParts(0xc026b70a80)
        /Users/rohrlich/go/src/github.com/goki/gi/giv/sliceviewinline.go:110 +0x948
github.com/goki/gi/giv.(*SliceViewInline).Render2D(0xc026b70a80)
        /Users/rohrlich/go/src/github.com/goki/gi/giv/sliceviewinline.go:216 +0x65
github.com/goki/gi/gi.(*Layout).Render2DChildren(0xc01cefaed0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1143 +0xb9
github.com/goki/gi/gi.(*Layout).Render2D(0xc01cefaed0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1778 +0xc3
github.com/goki/gi/gi.(*Node2DBase).Render2DTree(0xc01cefaed0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:803 +0x78
github.com/goki/gi/gi.(*PartsWidgetBase).Render2DParts(...)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/widget.go:787
github.com/goki/gi/giv.(*SliceViewInline).Render2D(0xc01cefaa80)
        /Users/rohrlich/go/src/github.com/goki/gi/giv/sliceviewinline.go:217 +0x7b
github.com/goki/gi/gi.(*Layout).Render2DChildren(0xc000992000)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1143 +0xb9
github.com/goki/gi/gi.(*Frame).Render2D(0xc000992000)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/frame.go:171 +0xc4
github.com/goki/gi/gi.(*Node2DBase).Render2DTree(0xc000992000)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:803 +0x78
github.com/goki/gi/gi.(*Viewport2D).ReRender2DNode(0xc0001c3500, 0x54b6c20, 0xc000992000)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:367 +0xbd
github.com/goki/gi/gi.(*Layout).SetScroll.func1(0x54877e0, 0xc000992000, 0x54895a0, 0xc053427b00, 0x0, 0x4ef5e60, 0xc061395348)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:991 +0xcd
github.com/goki/ki/ki.(*Signal).Emit(0xc0534295b8, 0x54895a0, 0xc053427b00, 0x0, 0x4ef5e60, 0xc061395348)
        /Users/rohrlich/go/src/github.com/goki/ki/ki/signal.go:162 +0x1a5
github.com/goki/gi/gi.(*SliderBase).SetValueAction(0xc053427b00, 0x44430000)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/sliders.go:314 +0xc5
github.com/goki/gi/gi.(*Layout).ScrollDelta(0xc000992000, 0xc05ee055e0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1096 +0x169
github.com/goki/gi/gi.(*Layout).LayoutScrollEvents.func1(0x54877e0, 0xc000992000, 0x548d9a0, 0xc000932000, 0x3, 0x5084ec0, 0xc05ee055e0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1622 +0x8e
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc05a87bcf8, 0x548d9a0, 0xc000932000, 0x3, 0x5084ec0, 0xc05ee055e0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc000932190, 0x541f000, 0xc05ee055e0, 0x1)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:237 +0x54f
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc000932000, 0x541f000, 0xc05ee055e0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1508 +0x8ec
github.com/goki/gi/gi.(*Window).EventLoop(0xc000932000)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1445 +0x36
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc000932000)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:851 +0x6d
main.guirun()
        /Users/rohrlich/go/src/github.com/ccnlab/babbling/sims/audonly/audonly.go:62 +0x4b
main.main.func1()
        /Users/rohrlich/go/src/github.com/ccnlab/babbling/sims/audonly/audonly.go:54 +0x20
github.com/goki/gi/gimain.Main.func1(0x544df80, 0x660f5a0)
        /Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:31 +0x24
github.com/goki/gi/oswin/driver/glos.Main.func1()
        /Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/glos/app.go:88 +0x40
created by github.com/goki/gi/oswin/driver/glos.Main
        /Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/glos/app.go:87 +0x87
panic: interface conversion: gi.Node2D is *gi.Action, not *gi.SpinBox

goroutine 52 [running]:
github.com/goki/gi/giv.(*FloatValueView).ConfigWidget(0xc060d936c0, 0x54b5820, 0xc026b7a000)
        /Users/rohrlich/go/src/github.com/goki/gi/giv/basicviews.go:655 +0x411
github.com/goki/gi/giv.(*SliceViewInline).ConfigParts(0xc026b70a80)
        /Users/rohrlich/go/src/github.com/goki/gi/giv/sliceviewinline.go:110 +0x948
github.com/goki/gi/giv.(*SliceViewInline).Render2D(0xc026b70a80)
        /Users/rohrlich/go/src/github.com/goki/gi/giv/sliceviewinline.go:216 +0x65
github.com/goki/gi/gi.(*Layout).Render2DChildren(0xc01cefaed0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1143 +0xb9
github.com/goki/gi/gi.(*Layout).Render2D(0xc01cefaed0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/layout.go:1778 +0xc3
github.com/goki/gi/gi.(*Node2DBase).Render2DTree(0xc01cefaed0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/node2d.go:803 +0x78
github.com/goki/gi/gi.(*Viewport2D).ReRender2DNode(0xc0001c3500, 0x54b8020, 0xc01cefaed0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:367 +0xbd
github.com/goki/gi/gi.(*Viewport2D).UpdateNode(0xc0001c3500, 0x54b8020, 0xc01cefaed0)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:816 +0x1cf
github.com/goki/gi/gi.(*Viewport2D).UpdateNodes(0xc0001c3500)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:797 +0x1c4
github.com/goki/gi/gi.(*Viewport2D).NodeUpdated(0xc0001c3500, 0x54b7b20, 0xc01cef1200, 0x1, 0x4f028a0, 0xc06155d0d8)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:696 +0x166
github.com/goki/gi/gi.SignalViewport2D(0x548d120, 0xc0001c3500, 0x54884a0, 0xc01cef1200, 0x1, 0x4f028a0, 0xc06155d0d8)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/viewport.go:650 +0x134
github.com/goki/ki/ki.(*Signal).Emit(0xc01cef1258, 0x54884a0, 0xc01cef1200, 0x1, 0x4f028a0, 0xc06155d0d8)
        /Users/rohrlich/go/src/github.com/goki/ki/ki/signal.go:162 +0x1a5
github.com/goki/ki/ki.(*Node).UpdateEnd(0xc01cef1200, 0xc01cef1501)
        /Users/rohrlich/go/src/github.com/goki/ki/ki/node.go:1912 +0x20a
github.com/goki/gi/gi.(*Label).SetText(0xc01cef1200, 0xc06155d0a0, 0x5)
        /Users/rohrlich/go/src/github.com/goki/gi/gi/label.go:139 +0x1cc
github.com/emer/emergent/netview.(*NetView).UpdateRecNo(0xc021c4c700)
        /Users/rohrlich/go/src/github.com/emer/emergent/netview/netview.go:283 +0x13c
github.com/emer/emergent/netview.(*NetView).UpdateImpl(0xc021c4c700)
        /Users/rohrlich/go/src/github.com/emer/emergent/netview/netview.go:184 +0x163
github.com/emer/emergent/netview.(*NetView).GoUpdate(0xc021c4c700)
        /Users/rohrlich/go/src/github.com/emer/emergent/netview/netview.go:115 +0xb4
main.(*Sim).UpdateView(0x6652920, 0xc000689900)
        /Users/rohrlich/go/src/github.com/ccnlab/babbling/sims/audonly/audonly.go:673 +0x94
main.(*Sim).AlphaCyc(0x6652920, 0x5423400)
        /Users/rohrlich/go/src/github.com/ccnlab/babbling/sims/audonly/audonly.go:712 +0x1b2
main.(*Sim).TestTrial(0x6652920, 0x1)
        /Users/rohrlich/go/src/github.com/ccnlab/babbling/sims/audonly/audonly.go:1260 +0x11f
main.(*Sim).TestAll(0x6652920)
        /Users/rohrlich/go/src/github.com/ccnlab/babbling/sims/audonly/audonly.go:1285 +0xd1
created by main.(*Sim).ConfigGui.func8
        /Users/rohrlich/go/src/github.com/ccnlab/babbling/sims/audonly/audonly.go:2045 +0x47

**Comment by rcoreilly** [comment]
@rohrlich -- I was just updating this page: https://github.com/goki/gi/wiki/Updating

and noticed the "multiple goroutines" section there -- can you try adding `[Un]BlockUpdates` around your `UpdateField` call?  I also noticed that I had commented out the actual effect of `[Un]BlockUpdates` but will check those in now as working again.

**Comment by rohrlich** [comment]
Well, my simulation doesn't run so I need to fix that first. I haven't touched it or run it in a few weeks.

**Comment by rohrlich** [comment]
See issue #50 in emer/emergent

**Comment by rcoreilly** [comment]
I just checked in a better version of [Un]BlockUpdates -- give that a try!

**Comment by rohrlich** [comment]
I don't see the push

**Comment by rcoreilly** [comment]
it was in gi -- I just double-checked: https://github.com/goki/gi/commit/5ee150f6a8dd0b1b41333297b682d0a1bcb524f0

**Comment by rohrlich** [comment]
Ok, got it. Maybe there is a delay showing up in zulip. Anyway netview updates so that is good :)
I'll check on my update issue, if not tonight, tomorrow.

**Comment by rohrlich** [comment]
Quite solid, took a while to find a way to crash on update but here is a reproducible crash. I was running my babbling/sims/audonly sim.
- Start training with netview visible
- Wait for some trials to be logged for the epoch and then open the TrnTrlLog
- Click Update View in the log display, might crash on first click or might take a few or a bunch
- I reproduced this multiple times

**Comment by rohrlich** [comment]
Here is the stack

panic: runtime error: index out of range [1] with length 1

goroutine 40 [running]:
github.com/emer/etable/etensor.(*Int64).FloatVal1D(0xc000632d00, 0x1, 0xc0aa9d86a0)
	/Users/rohrlich/go/src/github.com/emer/etable/etensor/numeric.gen.go:125 +0x46
github.com/emer/etable/etview.(*TableView).UpdateSliceGrid(0xc0aa9d8000)
	/Users/rohrlich/go/src/github.com/emer/etable/etview/tableview.go:584 +0xe5b
github.com/goki/gi/giv.(*SliceViewBase).Update(0xc0aa9d8000)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/sliceviewbase.go:212 +0xff
github.com/emer/etable/etview.(*TableView).ConfigToolbar.func1(0x54f67e0, 0xc0aa9d8000, 0x54f7d20, 0xc0ab292000, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/emer/etable/etview/tableview.go:850 +0x71
github.com/goki/ki/ki.(*Signal).Emit(0xc0ab293890, 0x54f7d20, 0xc0ab292000, 0x0, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/ki/signal.go:162 +0x1a5
github.com/goki/gi/gi.(*Action).ButtonRelease(0xc0ab292000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/action.go:222 +0x112
github.com/goki/gi/gi.(*ButtonBase).MouseEvent.func1(0x54f7d20, 0xc0ab292000, 0x5500520, 0xc0ab2ac000, 0x0, 0x50e5220, 0xc0acdec780)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/buttons.go:446 +0xcd
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc080c37d88, 0x5500520, 0xc0ab2ac000, 0x0, 0x50e5220, 0xc0acdec780)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc0ab2ac190, 0x54aadc0, 0xc0acdec780, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:237 +0x54f
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc0ab2ac000, 0x54aadc0, 0xc0acdec780)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1513 +0x79e
github.com/goki/gi/gi.(*Window).EventLoop(0xc0ab2ac000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1448 +0x36
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:863 +0xa6

**Comment by rcoreilly** [comment]
fixing this last case would require a mutex on the table itself -- that everyone would have to use in accessing the table.  I am reluctant to add that level of overhead / complexity for everything. in many cases people can add their own mutex to guard against known multiple access points.

maybe we can give the view a separate optional mutex pointer (or an interface or something) that, if present, is used around any updates.  That sounds pretty reasonable -- will add a separate ticket, and close this one.
