### ISSUE TITLE
Find dialog and bring to front rather than open a new one

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#300]
If I try to open a second configuration dialog (for example the config dialog for a tensorgrid display) just bring the already open one to front. Having 2 is confusing and unnecessary and besides they don't both update when you change values in one.

**Comment by rcoreilly** [comment]
It can be tricky to make sure an existing window is really already open -- probably depends on ensuring that window name is sufficiently unique -- will take a look at some point.

**Comment by rcoreilly** [comment]
plan: add a `Data` field to Window as `interface{}` -- set to main "item" that a given window is "about" -- only for dialogs etc which are about a specific object -- then an overall method that is FindOrOpen which is passed the Data -- if non-nil, looks for any window on that same data with same name..

**Comment by rohrlich** [comment]
Yep, that works. A nice improvement!

**Comment by rohrlich** [comment]
Does not work for all dialogs, for example, opening a var window when debugging, lookup window when editing, etc.

**Comment by rcoreilly** [comment]
This works only when there is a consistent "object" that can be associated with a window.  For the var, even if it has the same name, it can be quite different on each step, so there really isn't something consistent that we can use without incorrectly showing an old value.

For lookup, we could use the lookup string -- I will make the additions necessary to support strings -- I think that needs to be a special case for identity comparisons.

**Comment by rohrlich** [comment]
That's fine, the extra windows are not big deal.

**Comment by rcoreilly** [comment]
turns out interface{} of string works just fine for == operator.  added Data option for DialogOpts so TextViewDialog can use it optionally, and lookup now does use it.  if you find another case, file another ticket (can't do for var for reasons above).
