### ISSUE TITLE
Mac system main menu bar not always working correctly

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#301]
If my main window is open and 2 others, in my case a simat display and the simat display options dialogs, the menu only works to bring one forward.

1 - Open both the display and the options
2 - Bring main window to front so the other 2 are hidden
3 - Select one from window menu - no problem
4 - Selecting the other from the window menu does nothing

**Comment by rohrlich** [comment]
Only a problem with the Mac menubar window menu. The app menubar works as expected.

**Comment by rcoreilly** [comment]
yeah there is some updating lag in the mac menubar, since the move to glfw -- need to look back into that.

**Comment by rcoreilly** [comment]
in general the main system menu on Mac is hereby "deprecated"!  it is often far away.  added notes in the Platform section of wiki.  not worth messing with it.
