### ISSUE TITLE
Crash moving graph in plotview

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#302]
gi.text SetRenders() line 286 .Face was nil

github.com/goki/gi/gi.(*SpanRender).SetRenders at text.go:286
github.com/goki/gi/gi.(*SpanRender).SetString at text.go:329
github.com/goki/gi/gi.(*TextRender).SetString at text.go:1129
github.com/goki/gi/svg.(*Text).Render2D at text.go:86
github.com/goki/gi/gi.(*Node2DBase).Render2DChildren at node2d.go:749
github.com/goki/gi/svg.(*Group).Render2D at group.go:62
github.com/goki/gi/gi.(*Node2DBase).Render2DChildren at node2d.go:749
github.com/goki/gi/svg.(*Editor).Render2D at editor.go:144
github.com/goki/gi/gi.(*Node2DBase).Render2DTree at node2d.go:710
github.com/goki/gi/gi.(*WidgetBase).ReRender2DTree at widget.go:424
github.com/goki/gi/gi.(*Viewport2D).UpdateNodes at viewport.go:655
github.com/goki/gi/gi.(*Viewport2D).SetNeedsFullRender at viewport.go:617
github.com/goki/gi/gi.(*Viewport2D).Init2D.func1 at viewport.go:316
github.com/goki/ki/ki.(*Signal).Emit at signal.go:162
github.com/goki/ki/ki.(*Node).UpdateSig at node.go:1949
github.com/goki/gi/svg.(*Editor).EditorEvents.func1 at editor.go:58
github.com/goki/gi/gi.(*WinEventRecv).Call at window.go:1996
github.com/goki/gi/gi.(*Window).SendEventSignal at window.go:2142
github.com/goki/gi/gi.(*Window).ProcessEvent at window.go:1519
github.com/goki/gi/gi.(*Window).EventLoop at window.go:1446
github.com/goki/gi/gi.(*Window).StartEventLoop at window.go:806
main.mainrun at audonly.go:1801
main.main.func1 at audonly.go:48
github.com/goki/gi/gimain.Main.func1 at gimain.go:30
github.com/goki/gi/oswin/driver/glos.Main.func1 at app.go:87
runtime.goexit at asm_amd64.s:1357
 - Async stack trace
github.com/goki/gi/oswin/driver/glos.Main at app.go:86

**Comment by rcoreilly** [comment]
added a nil guard / workaround -- reopen if happens again.
