### ISSUE TITLE
index out of range (-1) when selecting directory in fileview

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#303]
runtime.fatalpanic at panic.go:847
runtime.gopanic at panic.go:722
runtime.goPanicIndex at panic.go:75
github.com/goki/gi/giv.(*TableView).SortSlice at tableview.go:699
github.com/goki/gi/giv.(*FileView).UpdateFiles at fileview.go:543
github.com/goki/gi/giv.(*FileView).UpdateFilesAction at fileview.go:456
github.com/goki/gi/giv.(*FileView).SelectFile at fileview.go:115
github.com/goki/gi/giv.(*FileView).ConfigFilesRow.func3 at fileview.go:359
github.com/goki/ki/ki.(*Signal).Emit at signal.go:162
github.com/goki/gi/giv.(*SliceViewBase).SliceViewBaseEvents.func3 at sliceviewbase.go:1957
github.com/goki/gi/gi.(*WinEventRecv).Call at window.go:2006
github.com/goki/gi/gi.(*Window).SendEventSignal at window.go:2152
github.com/goki/gi/gi.(*Window).ProcessEvent at window.go:1529
github.com/goki/gi/gi.(*Window).EventLoop at window.go:1456
runtime.goexit at asm_amd64.s:1357
 - Async stack trace
github.com/goki/gi/gi.(*Window).GoStartEventLoop at window.go:825

**Comment by rcoreilly** [comment]
if you can reproduce conditions for this, please try now and close if fixed..

**Comment by rohrlich** [comment]
No problem now.
