### ISSUE TITLE
Zoom on open/close problems

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#304]
With the latest build my window opens with one font and then goes through a couple of dpi/zoom changes and then goes black. At first I wasn't looking and I thought it went directly to black. Resizing the screen eventually got the window back to normal but again it cycled a bit before it looked correct. Then clicking the close box led to similar behavior.

Got a bunch of duplicate error messages, only copied one set.

OpenGL version 4.1 ATI-2.11.20
Saving epoch log to: Aud_Base_epc.csv
2019/11/26 17:19:58 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
	501 = INVALID_VALUE: Given when a value parameter is not a legal value for that function. This is only given for local problems; if the spec allows the value in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.
2019/11/26 17:19:58 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
	502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
glgpu gpu.Framebuffer:  not complete -- this usually means you need to set your GoGi prefs to Smooth3D = off, and restart
2019/11/26 17:19:58 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:

**Comment by rohrlich** [comment]
After reading your email to emergent-users I tried launching my simulation without an external monitor and it opened without problem. I then plugged in my external monitor and the window moved to the external again without issue. 

I tried again to launch with external monitor connected and the problem was back. And saving zoom for "current screen only" doesn't help.

**Comment by rcoreilly** [comment]
post your gogi/preferences screen info here -- i think it is something about the screen info

**Comment by rohrlich** [comment]
Will do tonight.  Celebrating thanksgiving today because my son works tomorrow.

John - From my phone

On Nov 27, 2019, at 12:22 PM, rcoreilly <notifications@github.com> wrote:

﻿

post your gogi/preferences screen info here -- i think it is something about the screen info

**Comment by rohrlich** [comment]
The screen giving me grief is the LG UltraFine.

<img width="985" alt="Screen Shot 2019-11-27 at 6 53 59 PM" src="https://user-images.githubusercontent.com/22350787/69773381-93e79780-1147-11ea-90f5-83699e712b23.png">

**Comment by rohrlich** [comment]
Here is what I get from the ScreenInfo button (other was from prefs) - not double entries

Screen number: 0 name: LG UltraFine
<br>    geom: (0,0)-(5120,2880), depth: 24, logical DPI: 1236, physical DPI: 217.10852, logical DPI scale: 5.6930056, physical size: (599,340)
<br>    device pixel ratio: 2, refresh rate: 59
<br>    orientation: OrientationUnknown, native orientation: OrientationUnknown, primary orientation: OrientationUnknown
<br><br>
Screen number: 1 name: Color LCD
<br>    geom: (369,1440)-(3729,3540), depth: 24, logical DPI: 144, physical DPI: 258.6182, logical DPI scale: 0.5568054, physical size: (330,206)
<br>    device pixel ratio: 2, refresh rate: 60
<br>    orientation: OrientationUnknown, native orientation: OrientationUnknown, primary orientation: OrientationUnknown
<br><br>
Screen number: 2 name: LG UltraFine
<br>    geom: (0,0)-(5120,2880), depth: 24, logical DPI: 1236, physical DPI: 217.10852, logical DPI scale: 5.6930056, physical size: (599,340)
<br>    device pixel ratio: 2, refresh rate: 59
<br>    orientation: OrientationUnknown, native orientation: OrientationUnknown, primary orientation: OrientationUnknown
<br><br>
Screen number: 3 name: Color LCD
<br>    geom: (369,1440)-(3729,3540), depth: 24, logical DPI: 144, physical DPI: 258.6182, logical DPI scale: 0.5568054, physical size: (330,206)
<br>    device pixel ratio: 2, refresh rate: 60
<br>    orientation: OrientationUnknown, native orientation: OrientationUnknown, primary orientation: OrientationUnknown

**Comment by rcoreilly** [comment]
I don't know why it is doing multiple screen entries.  but the main problem is that your logical DPI scale is 5.6 -- should be more like .56.  can you try editing the ~/Library/GoGi/prefs file and change that to .56.  then try opening something on that screen.

**Comment by rohrlich** [comment]
- I changed the 5.6 to .56 -- screen still went through 3 font/zoom changes but didn't go black so that was good.
- Tried update/save of zoom - some pretty strange behavior on update but no change on relaunching the app
- Tried moving aside the prefs.json file -- back to getting the black screen after the font/zoom changes
- Tried moving aside my win_geom_prefs -- no change

**Comment by rohrlich** [comment]
also still getting these errors
    506 = INVALID_FRAMEBUFFER_OPERATION: Given when doing anything that would attempt to read from or write/render to a framebuffer that is not complete.
2019/11/27 21:54:45 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
        501 = INVALID_VALUE: Given when a value parameter is not a legal value for that function. This is only given for local problems; if the spec allows the value in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.
2019/11/27 21:54:46 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:

**Comment by rcoreilly** [comment]
so does it actually display something or not?  what does the window look like?

The framebuffer errors are certainly concerning.  can you try a regular goki/gi/examples/widgets run -- I don't know if those framebuffer errors are 3d related or not

**Comment by rcoreilly** [comment]
@rohrlich and @StephenJRead -- I just pushed some significant updates in robustness for this code, so go to gok/gi and do a git pull.  and please test using gi/examples/widgets for the time being just to make it easier.

Overall, the key issue is that your external monitor has a "DevicePixelRatio" of 2, and we didn't properly have that information previously, so all the scaling was off by a factor of 2.  this means all the windows you've previously opened have this incorrect size saved.  @StephenJRead It may be worth moving `~/Library/GoGi/win_geom_prefs` to another name and giving a try as @rohrlich tried.

Please report behavior with latest changes and no win_geom_prefs, and a reasonable logical DPI scale value.

**Comment by rohrlich** [comment]
Well done! Works perfectly now. Tried on widgets example and my own sims.

**Comment by StephenJRead** [comment]
Will try after thanksgiving. Family here all day.

Sent from my iPhone

On Nov 28, 2019, at 8:49 AM, John Rohrlich <notifications@github.com> wrote:

﻿

Well done! Works perfectly now. Tried on widgets example and my own sims.

**Comment by StephenJRead** [comment]
Just did a go get update and rebuilt the widget example.  Everything is working fine.  Also did a go get update on ra25 and rebuilt the ra25 example and that worked fine.  I do notice that when the window opens it opens on my laptop screen. Before it typically opened on the external monitor.  I did move the win_geom_prefs to another name before doing all this.

**Comment by rcoreilly** [comment]
Great!  the windows will open on the "primary monitor" which is the one with the menubar and dock.
