### ISSUE TITLE
make manipulatable 3d scene is too difficult

### ISSUE THREAD

**Issue by runsys** [goki/gi#308]
make manipulatable 3d scene is too difficult

**Comment by rcoreilly** [comment]
We do not have any manipulators implemented yet (e.g., a box transformer etc).  This is in the plans but not on the immediate todo list.  The robust event structure should make it reasonably straightforward however, and there are examples in our https://github.com/emer/emergent netview code for basic mouse-click level interaction with 3D shapes, so the geometry and bounding box logic is all in place, and that provides a good starting point for future reference.

**Comment by runsys** [comment]
OK, It's very helpful. Thank you very much.

**Comment by rcoreilly** [comment]
I just pushed some basic manipulation support -- see the `examples/gi3d` example and README.me.
