### ISSUE TITLE
When trying to build any go files with gogi, error returned

### ISSUE THREAD

**Issue by kplat1** [goki/gi#309]
This is the error returned (on Linux)

# github.com/goki/gi/giv
../../../goki/gi/giv/himarkup.go:103:43: too many arguments in call to "github.com/alecthomas/chroma/formatters/html".WithClasses
	have (bool)
	want ()

**Comment by kplat1** [comment]
github.com/goki/gi/giv
../../../goki/gi/giv/himarkup.go:103:43: too many arguments in call to "github.com/alecthomas/chroma/formatters/html".WithClasses
	have (bool)
	want ()

**Comment by rcoreilly** [comment]
go get -u ./...

that package (alecthomas/chroma) was updated with this new arg -- you need to update!
