### ISSUE TITLE
scale update not correct if entering scale value by typing rather than increment

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#319]
I see this problem in my sim plots. If I type a value for scale into the spinbox the scale might change to smaller when I actually increased the scale. No problem with scale change when using the increment/decrement of the spinbox.

**Comment by rcoreilly** [comment]
This is truly bizarre.  I have traced through and it is definitely setting the new scale and calling the same Update method correctly in both cases.  I can't see any diff.  If you just twiddle something else in the config it displays properly -- seems like a second pass of updating is happening with the incr / decr but I can't find it..

**Comment by rcoreilly** [comment]
should be fixed now.
