### ISSUE TITLE
Add the ability to import 3d files

### ISSUE THREAD

**Issue by kplat1** [goki/gi#323]

**Comment by rcoreilly** [comment]
.obj working well now -- need to use triangles option for SketchUp.  blender quads work fine.

infrastructure should handle other types -- should be able to steal code from g3n and slot it in, but won't be able to get to this for a while.  g3n supports collada and one other.

**Comment by kplat1** [comment]
The new file types will not be added now, and a separate ticket will be filed for other file types. OBJ is working great.

**Comment by kplat1** [comment]
More file types for importing will be added later. The more file types ticket is issue #329
