### ISSUE TITLE
Wierdness updating text field when text is longer than field (minor issue)

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#333]
Here is a text field from my simulation
<img width="656" alt="Screen Shot 2020-01-13 at 10 30 15 AM" src="https://user-images.githubusercontent.com/22350787/72281850-31abfe80-35f0-11ea-8041-a2088b463855.png">
After "Step Trial"
<img width="674" alt="Screen Shot 2020-01-13 at 10 29 16 AM" src="https://user-images.githubusercontent.com/22350787/72281879-4c7e7300-35f0-11ea-9392-7b1571de7d15.png">
During Step trial you see a piece of the missing text appear and then disappear
Here is the field after mouse click in field
<img width="664" alt="Screen Shot 2020-01-13 at 10 30 44 AM" src="https://user-images.githubusercontent.com/22350787/72281947-7899f400-35f0-11ea-8e85-9237ad4cd9e9.png">
Here it is after a second mouse click
<img width="656" alt="Screen Shot 2020-01-13 at 10 30 55 AM" src="https://user-images.githubusercontent.com/22350787/72281974-8c455a80-35f0-11ea-8c91-ac16779ebc0b.png">
After 4 mouse clicks the full text is shown

**Comment by rcoreilly** [comment]
this case should not happen with new rendering framework.  if see again, file a new ticket with reproducible example.
