### ISSUE TITLE
build errors at rev cfe1b631612c73e67dc19e05cdbb32b452169e2c

### ISSUE THREAD

**Issue by mewmew** [goki/gi#340]
I cloned the latest revision of GoGi (cfe1b631612c73e67dc19e05cdbb32b452169e2c) and got a few errors when compiling (using Go 1.14). As `gi` is using Go modules, I'd expect that the `go.mod` file is simply out of date?

```
$ git clone https://github.com/goki/gi
$ cd gi
$ go install -v ./...
...
github.com/goki/gi/vci
# github.com/goki/gi/vci
vci/svn.go:47:16: undefined: dirs.AllFiles
vci/vcs.go:85:5: undefined: dirs.HasFile
vci/vcs.go:88:5: undefined: dirs.HasFile
...
github.com/goki/gi/gi
# github.com/goki/gi/gi
gi/action.go:270:48: undefined: ki.NonUniqueNames
gi/action.go:289:48: undefined: ki.NonUniqueNames
gi/bars.go:158:36: undefined: ki.NonUniqueNames
gi/buttonbox.go:174:27: undefined: ki.DestroyKids
gi/buttonbox.go:181:48: undefined: ki.NonUniqueNames
gi/buttons.go:568:43: undefined: ki.NoInherit
gi/buttons.go:568:57: undefined: ki.TypeProps
gi/buttons.go:572:38: undefined: ki.NoInherit
gi/complete.go:34:14: undefined: complete.LookupFunc
gi/complete.go:240:80: undefined: complete.Edit
gi/buttons.go:572:38: too many errors
...
```

**Edit:** Note, version v0.9.10 of GoGi compiles without any errors.

**Comment by rcoreilly** [comment]
yeah I'm doing a major push to get to 1.0 and not updating go.mod until I make a new tagged release which will be the "rc".

**Comment by drjosephliu** [comment]
Also getting a similar error for latest revision of GoGi:

```
[widgets (master)]$ go get ./...
# github.com/goki/gi/vci
../../vci/svn.go:47:16: undefined: dirs.AllFiles
../../vci/vcs.go:85:5: undefined: dirs.HasFile
../../vci/vcs.go:88:5: undefined: dirs.HasFile
# github.com/goki/gi/gi
../../gi/complete.go:34:14: undefined: complete.LookupFunc

```

Running  go version go1.13.7 darwin/amd64 and Mac OS Catalina 10.15.3

**Comment by mewmew** [comment]
@drjosephliu, I think this is an expected error, as only tagged versions have the correct `go.mod` info.

@rcoreilly, you may want to consider including the working state of `go.mod` with each commit. This guarantees that others working on `goki/gi` sees the exact same state as you do, and any issues encountered with a specific revision of `goki/gi` are reproducible.

As it is now, it's difficult for outside contributors to work on the latest revision of the project. For this reason, contributors wanting to actively participate may instead become passive as they can't build the same view of the project as you.

While including `go.mod` contents in Git commits does pollute each commit a little bit, it also adds value where the project and its dependencies are in a know good state at each commit. And, as mentioned above, it becomes easier for people other than yourself to start getting more involved with the project.

Best wishes,
Robin

**Comment by rcoreilly** [comment]
yep, the temp solution is to set GO111MODULES=off but I'll work on a better way to keep the go.mod's up-to-date.  The problem is that so far it seems like a multi-step process to get the multiple libraries all updated on go.mod, and I'm not using it for development so it is definitely a separate step.  But this is what Makefiles etc are for.

**Comment by mewmew** [comment]
> yep, the temp solution is to set GO111MODULES=off but I'll work on a better way to keep the go.mod's up-to-date. The problem is that so far it seems like a multi-step process to get the multiple libraries all updated on go.mod, and I'm not using it for development so it is definitely a separate step. But this is what Makefiles etc are for.

Makes sense. I know, it takes time to make the switch. I made to switch to using Go modules also for development 6 or so months ago, and it was a bit rough in the beginning. But once you get used to it, it's much preferable as each commit produces a reproducible build.

In essence, I only rely on the `go` command with `GO111MODULES=on`. To update dependencies use `go get`, optionally specifying tag, branch name or commit; e.g. `go get github.com/goki/gi@master`. And then just run `go mod tidy` before you do a `git commit`.

**Comment by rcoreilly** [comment]
Ok I made some Makefile targets to keep all the goki stuff updated, so hopefully this will not be a problem anymore.  Also I'm almost done with the v1 release and then it should be much more stable :). Also gide now has full toggle-able modules support so it is easy to go back and forth and make sure everything's working.
