### ISSUE TITLE
dirty rectangle of text cursor not redrawn after DPI scale change

### ISSUE THREAD

**Issue by mewmew** [goki/gi#341]
When entering the GoGi Preferences menu and editing the LogicalDPIScale from `1.0` to `1.1` by typing `[backspace]` (to remove the `0` from `1.0`) and the typing `1` and pressing `[enter]` results in a change of the DPI, but leaves the black rectangle used as text cursor as a visible artefact on screen. See screenshot below:

![screenshot_2020-02-01_21:48:09](https://user-images.githubusercontent.com/1414531/73598822-2851ea00-453d-11ea-9c75-cdee3c5c82ff.png)

Forcing a full refresh (by e.g. fullscreening the Preferences menu) fixes the rendering issue, so this does seem to be a dirty rectangle that needs to be redrawn but isn't. The logical state is correct (but not the state drawn to screen).

This was run on version v0.9.10 of GoGi (opening the Preferences menu from the `colors` example program).

**Comment by rcoreilly** [comment]
This is directly changing the scaling without calling the appropriate update, probably.

**Comment by rcoreilly** [comment]
fixed :)
