### ISSUE TITLE
examples/marbles: colours of marbles not rendered after pressing reset

### ISSUE THREAD

**Issue by mewmew** [goki/gi#343]
When launching the marbles example, the marbles each have a unique colour. However, after pressing reset, each marble is rendered as black, and get rendered in their unique colour only after pressing Run or Step to start or single step the animation.

Screenshot after hitting Reset:
![screenshot_2020-02-01_22:14:06](https://user-images.githubusercontent.com/1414531/73599146-8f24d280-4540-11ea-858b-0da42e30c3e1.png)

Screenshot after hitting Step (thus giving colour to the black marbles of the above screenshot):
![screenshot_2020-02-01_22:14:15](https://user-images.githubusercontent.com/1414531/73599152-a06ddf00-4540-11ea-9f59-f980a6262159.png)

**Edit:** obviously this is a low-priority issue ^^

**Comment by rcoreilly** [comment]
now fixed and major improvement to marbles itself: you can actually see 100 or 1000 marbles now with Width > 0!
