### ISSUE TITLE
filetree: rename of empty dir fails

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#345]
fatal: source directory is empty, source=debug, destination=gidebug

seems likely to be a git error. need to detect empty dir and use os. rename instead.

**Comment by rohrlich** [comment]
The specific bug is fixed but the rename will fail if the directory has children and none of the kids is stored. I think a good solution would be to have the directory state reflect the kids state, stored vs untracked. Empty directories would always be untracked.

**Comment by rohrlich** [comment]
Might be a real hassle to keep the directory state up to date so could just check the children if some action is requested on the directory or File Info is invoked.

**Comment by rcoreilly** [comment]
I think it should be fine as is -- not that practical / necessary to check children.  if u have a dir within a repo and you're renaming it, it likely will have checked-in-items or be empty..  very rare case, for which a terminal is available :). at least, for now I think this is reasonable. the super polish round of updates later can address this level of detail.
