### ISSUE TITLE
vcs commands not enabled in filetree context menu

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#347]

**Comment by rcoreilly** [comment]
are you sure?  this has always been correct for me. if something is "Stored" then it only has delete avail.  also Info now shows the vcs status.

**Comment by rohrlich** [comment]
None of the menu items are enabled and now that you told me that the file info has the status I checked and all of them say "Stored", even a file I just created.

**Comment by rcoreilly** [comment]
well it is probably not finding your .git then.  also I'm assuming you're definitely updated to latest code and not getting some kind of weird GO111MODULE issue?  i.e., make sure you've got that turned off.

**Comment by rohrlich** [comment]
so, yes it is not finding my .git because the gide project is only is the subdirectory and at the repository level! I'll create a new project.
Yes - very latest code and yes GO111MODULE is off
- thanks

**Comment by rohrlich** [comment]
Working now!
