### ISSUE TITLE
Filetree - deleting directories not working - file not found and may crash

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#349]
I tried to delete a directory that had subdirs and then I tried deleting one of the subdirs - both failed.

Then I created an empty directory and tried to delete it. That failed and then the panic.

Aside: None of the files in the directories are "stored" but I notice the directories themselves always display as "stored".

fatal: pathspec &#39;sims/temp&#39; did not match any files
2020/02/04 21:20:17 fatal: pathspec &#39;sims/temp&#39; did not match any files

2020/02/04 21:22:29 fatal: pathspec &#39;sims/temp/axFiles&#39; did not match any files
fatal: pathspec &#39;sims/temp/axFiles&#39; did not match any files

2020/02/04 21:23:45 fatal: pathspec &#39;fooFolder&#39; did not match any files
fatal: pathspec &#39;fooFolder&#39; did not match any files

panic: runtime error: index out of range [-1]

goroutine 872 [running]:
github.com/goki/gi/gi.(*TextLink).Bounds(0xc01181bb58, 0xc02a5b5340, 0x4438bd334537c1dc, 0xd, 0x2b, 0xc01181bb80, 0xc01181bb40)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/text.go:754 +0x1a6
github.com/goki/gi/giv.(*TextView).MouseMoveEvent.func1(0x517d640, 0xc024804000, 0x516f940, 0xc01563e000, 0x1, 0x4ddb340, 0xc075a170e0)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/textview.go:4379 +0x298
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc01181bd88, 0x516f940, 0xc01563e000, 0x1, 0x4ddb340, 0xc075a170e0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc01563e190, 0x5106cc0, 0xc075a170e0, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/events.go:237 +0x54f
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc01563e000, 0x5106cc0, 0xc075a170e0)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1508 +0x8ec
github.com/goki/gi/gi.(*Window).EventLoop(0xc01563e000)
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:1445 +0x36
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/gi/window.go:860 +0xa6

**Comment by rohrlich** [comment]
I pushed pretty hard on the filetree with add/delete/duplicate/rename etc and also some pushing on git commands and so far only found this one bug.

**Comment by rcoreilly** [comment]
great!  yep I probably didn't test deleting dirs..  I will take a look at this.

Btw, in git, directories themselves are never literally stored in the repository -- only implicitly if their children are.

**Comment by rohrlich** [comment]
Yes, knew that :)

Fixed - don't try to delete dirs from repo.
