### ISSUE TITLE
missing fonts cause crash displaying prompt dialog

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#351]
Originally gide bug #126.

If curf.Face is nil the code shown below fails (line 1646 of text.go) 
curSp.AppendString(unestr, curf.Face.Face, curf.Color, curf.BgColor.ColorOrNil(), curf.Deco, font, ctxt)

It will be nil if fonts are missing - The segment violation was preceded by:
2020/02/05 20:06:50 gi.FontLib: no font paths -- need to add some
2020/02/05 20:06:50 gi.FontLib: Font named: go not found in list of available fonts, try adding to FontPaths in gi.FontLibrary, searched paths: []

**Comment by rohrlich** [comment]
My prefs show FontPaths null and FontFamily "Go"

What is the path to the Go font?

**Comment by rcoreilly** [comment]
Go is builtin :). it is a package.  I'll take a look with the debugger soon :)

**Comment by rcoreilly** [comment]
It should be fixed by removing prompt dialog call that is happening way too early during startup.  I fixed this in various other places but missed the Gide-specific keycap.

**Comment by rcoreilly** [comment]
John said it's fixed now :)
