### ISSUE TITLE
KeyMap sorting not alphabetical

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#361]
Assuming it is an alphabetic sort.

**Comment by rohrlich** [comment]
I can look at this if you let me know the intention when toggling the sort. Is the toggle between sorted key chords and sorted functions?

**Comment by rcoreilly** [comment]
it is sorting based on numerical value of the KeyFun, which is NOT alpha.  it is quasi-functional order (up / down etc first the more complex stuff later -- maybe not ideal but at least not random!

**Comment by rohrlich** [comment]
I changed the title. It is a map so I expect it would be easy to fix but it can certainly wait or I can close if you prefer.

**Comment by rcoreilly** [comment]
the only fixes would be to manually re-order the "enums" in alpha order in gi/keyfun.go or change the sorting logic for this map relative to any others (e.g., introduce a type property or something), or always use alpha sorting for all maps instead of "value" sort.. IMO not worth it...

**Comment by rohrlich** [comment]
Closing - and we have the issue history if we want to revisit.
