### ISSUE TITLE
Cannot set background color of gi.Label

### ISSUE THREAD

**Issue by kplat1** [goki/gi#365]
Code builds and runs without errors but fails to set the background color of the text. Text color works fine, just background color doesn't work. This issue exists when I run on Chrome OS Linux (Crostini); it may be specific to this platform.

**Comment by kplat1** [comment]
The problem is not just a problem with Linux; it also exists on macOS. After some investigation, it seems to be a bug.

**Comment by rcoreilly** [comment]
this seems to be working fine -- any new repercussions can be filed as new issues
