### ISSUE TITLE
marbles is not updating incrementally anymore

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#368]
some change to svn updating at some point?  single step mode works but now just does full update at end. thought it was due to latest update to glfw 3.2 but verified that it predates that.

**Comment by rcoreilly** [comment]
if you change Run to not use `go RunMarbles` then it does update.  so being in the separate goroutine causing it.

**Comment by kplat1** [comment]
This problem also exists in an app I have written on Linux -- used to update every step but now just updates once at the end.

**Comment by kplat1** [comment]
The problem in my app was a code error completely unrelated to this that I have now fixed. This is probably some other problem.

**Comment by rcoreilly** [comment]
repainting SVG viewport requires calling `SetNeedsFullRender()` to redraw..  wasn't true before but removed an automatic call that was resulting in redundant updates.
