### ISSUE TITLE
failed with trying examples

### ISSUE THREAD

**Issue by younlok** [goki/gi#373]
error : 
`oswin.glos failed to create hidden share window -- this usually means that the OpenGL version is not sufficient (should be at least: 3.3): VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig
exit status 1

`

i think because i have a low graphics card and low opengl version 
but i have worked before with some opengl libraries like sdl and some games like minecraft 

is there a fix for this 
thank you  
also iam using itas a module

**Comment by rcoreilly** [comment]
What platform are you on?  If it is windows, often you can get better drivers from the graphics card manufacturer's website or something.  And Minecraft likely runs under directX on that platform.

**Comment by younlok** [comment]
no i run on linux 
also i tried before  gxui from google which works with glfw but i am here because the docs arevery good but its working 
also even with gopath it's not working

**Comment by rcoreilly** [comment]
this issue won't be affected by GOPATH.  try running glxinfo to see how your graphics card is configured and which versions are supported.

**Comment by younlok** [comment]
yeah i already did it 
and my opengl is 2. stuff
my question is can i get it to workwith low opengl version

**Comment by rcoreilly** [comment]
no it only supports 3.3, which is already 10+ years old!  there are major differences in older versions that make it impractical to support them.
