### ISSUE TITLE
UI Suggestion (would help me :) ) - confirm dialog for replace "all" when find is multi-file

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#377]
Twice now I've clicked "All" by accident when I thought I was setting the find scope to be "no top" which is a similar concept.

I was searching for "key" and it took several minutes minutes for all of the replacements, 21 files were edited!! Screen after screen of find/replace went by!!

LOL

**Comment by rcoreilly** [comment]
yeah I agree -- easy to add and shouldn't be that obtrusive to the user as the All option is relatively rarely used.

**Comment by rcoreilly** [comment]
ps should be a gide issue..  done.
