### ISSUE TITLE
could be less lazy and just code the scrollbar into the TextView instead of relying on Layout wrapper

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#387]
would be cleaner overall.

**Comment by rohrlich** [comment]
Not totally sure what you mean but I think you intend to add a scroll bar to textview which would mean that for the tabs panel the scrollbar for the text content would always be there. If that is so I totally endorse the plan.

**Comment by rcoreilly** [comment]
In looking into this further, the layout does a *lot* of work by handing both horizontal and vertical scrolling, and the auto adding of scrollbars etc.  Instead, added some functions to create Layout and widget / TextView in one call.
