### ISSUE TITLE
Error building on OSX

### ISSUE THREAD

**Issue by tbayne** [goki/gi#389]
I am sure this is something I am doing wrong, but I have not been able to figure it out.  I did a git clone of the project, then attempted  a build.  When building on OSX I get the following errors:
`
glos_darwin.m:354:44: error: use of undeclared identifier 'NSEventModifierFlagShift'
glos_darwin.m:354:71: error: use of undeclared identifier 'NSEventModifierFlagCommand'
glos_darwin.m:356:44: error: use of undeclared identifier 'NSEventModifierFlagCommand'
glos_darwin.m:360:44: error: use of undeclared identifier 'NSEventModifierFlagShift'
glos_darwin.m:360:71: error: use of undeclared identifier 'NSEventModifierFlagOption'
glos_darwin.m:362:44: error: use of undeclared identifier 'NSEventModifierFlagOption'
glos_darwin.m:366:44: error: use of undeclared identifier 'NSEventModifierFlagShift'
glos_darwin.m:366:71: error: use of undeclared identifier 'NSEventModifierFlagControl'
glos_darwin.m:368:44: error: use of undeclared identifier 'NSEventModifierFlagControl'
`
I attempted to build uisng `make build` in the top level directory, any idea what I've done wrong?

**Comment by rcoreilly** [comment]
Hmm. what OSX version? xcode-select --install worked?
