### ISSUE TITLE
Multiple "sure you want to quit?" dialogs

### ISSUE THREAD

**Issue by thazy** [goki/gi#39]
When MacBook pro tried to go to sleep/auto shutdown goki prevented shutdown (good!), but it opened up many, many dialog windows as shown in the "all desktops" view:
![img_0147](https://user-images.githubusercontent.com/30027010/44468434-6b86fa00-a5e2-11e8-809c-240d3d695ba5.JPG)
![img_0148](https://user-images.githubusercontent.com/30027010/44468435-6c1f9080-a5e2-11e8-925d-e08399944c13.JPG)

**Comment by rcoreilly** [comment]
added logic to widgets app to not show repeated prompts
