### ISSUE TITLE
How to support Chinese fonts

### ISSUE THREAD

**Issue by Aquarian-Age** [goki/gi#397]
This is a demo of 　basic.go
![2020-07-18.png](https://i.loli.net/2020/07/18/ZeEVMS5L4pF7lac.png)

**Comment by rcoreilly** [comment]
You need to choose a font that supports those characters -- click on GoGi/Preferences then click on the font and choose one that renders properly -- some of the Example text contains characters, at the end.

**Comment by Aquarian-Age** [comment]
> You need to choose a font that supports those characters -- click on GoGi/Preferences then click on the font and choose one that renders properly -- some of the Example text contains characters, at the end.

-------
Thank you

**Comment by HDHChris** [comment]
Hi，I solved the problem of displaying Chinese in normal components according to the settings in the upper part. However, when I use the label part, the text contains HTML tags. When Chinese is used in the tags, I try to modify the font setting of prop of the label part, but I find that some HTML tags can be displayed normally in Chinese, but some can't. How to solve it, thank you. Examples are as follows:
<img width="1976" alt="Snipaste_2022-04-26_19-10-35" src="https://user-images.githubusercontent.com/76725654/165287966-c9694a72-54e5-4b7c-826c-cdc9c83ef82d.png">

**Comment by dosgo** [comment]
Is there a current example? It seems different.

**Comment by kkoreilly** [comment]
@dosgo We are currently making international fonts automatically and fully work in #1457. Once that is merged (hopefully within a couple of weeks), then there should be no more issues with this. Thank you for your patience.

**Comment by kkoreilly** [comment]
We merged #1457 (see #1525 for details), so international fonts now work on all platforms. Please let me know if you have any issues.
