### ISSUE TITLE
Different window display behavior depending on application focus

### ISSUE THREAD

**Issue by thazy** [goki/gi#40]
On macbook pro "all desktops" view some windows not displayed if focus is not on goki (widgets.go) app, while are displayed if focus is in goki:

Focus not in goki:
![img_0149](https://user-images.githubusercontent.com/30027010/44469112-fae0dd00-a5e3-11e8-9241-4c6412cd36d9.JPG)

Focus in goki:
![img_0147](https://user-images.githubusercontent.com/30027010/44469151-164be800-a5e4-11e8-8483-24d2d1b87511.JPG)

COMMENT: FWIW, the difference seems to be user-level windows vs. admin-level windows? But I don't believe I have seen than differential display behavior in other applications.

**Comment by rcoreilly** [comment]
this is a "feature" of macOS -- the dialog windows are considered "minor" and hidden unless app is in focus.
