### ISSUE TITLE
Link error for widget build

### ISSUE THREAD

**Issue by andreifoldes** [goki/gi#408]
When running `go build` for `gi/examples/widgets` I get:

(base) C:\Users\folde\gi\examples\widgets>go build
github.com/goki/gi/examples/widgets
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: export ordinal too large: 71939
collect2.exe: error: ld returned 1 exit status

Go version: 

> go version go1.15 windows/amd64

Go env:

> (base) C:\Users\folde\gi\examples\widgets>go env
> set GO111MODULE=
> set GOARCH=amd64
> set GOBIN=
> set GOCACHE=C:\Users\folde\AppData\Local\go-build
> set GOENV=C:\Users\folde\AppData\Roaming\go\env
> set GOEXE=.exe
> set GOFLAGS=
> set GOHOSTARCH=amd64
> set GOHOSTOS=windows
> set GOINSECURE=
> set GOMODCACHE=C:\Users\folde\go\pkg\mod
> set GONOPROXY=
> set GONOSUMDB=
> set GOOS=windows
> set GOPATH=C:\Users\folde\go
> set GOPRIVATE=
> set GOPROXY=https://proxy.golang.org,direct
> set GOROOT=c:\go
> set GOSUMDB=sum.golang.org
> set GOTMPDIR=
> set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
> set GCCGO=gccgo
> set AR=ar
> set CC=gcc
> set CXX=g++
> set CGO_ENABLED=1
> set GOMOD=C:\Users\folde\gi\go.mod
> set CGO_CFLAGS=-g -O2
> set CGO_CPPFLAGS=
> set CGO_CXXFLAGS=-g -O2
> set CGO_FFLAGS=-g -O2
> set CGO_LDFLAGS=-g -O2
> set PKG_CONFIG=pkg-config
> set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\folde\AppData\Local\Temp\go-build310672726=/tmp/go-build -gno-record-gcc-switches

**Comment by rcoreilly** [comment]
I think this means you need to update the TDM-GCC compiler to a more recent version..

**Comment by andreifoldes** [comment]
Thank you for the quick response. I am using the most recent version I believe:
gcc version 9.2.0 (tdm64-1)
what actually fixed it was using:
`go build -buildmode=exe`

**Comment by rcoreilly** [comment]
Hmm, that is strange -- shouldn't buildmode=exe be the default in a main package?  anyway, glad it is fixed!
