### ISSUE TITLE
Column labels don't align with their data fields in font editing window

### ISSUE THREAD

**Issue by thazy** [goki/gi#41]
![img_0152](https://user-images.githubusercontent.com/30027010/44470621-71330e80-a5e7-11e8-967d-400794f7b94a.JPG)

**Comment by rohrlich** [comment]
Have seen this in fileview as well. Resizing window fixes the alignment.

**Comment by rcoreilly** [comment]
yeah, this is a tricky issue as the header is a separate widget, and if it aligns with cols when screen is too small, it gets its own scrollbar, which is not good...   then I just remembered the "overflow" property -- setting it to "hidden" works great!
