### ISSUE TITLE
race condition detector complains about data race in StructView.ConfigStructGrid

### ISSUE THREAD

**Issue by rgobbel** [goki/gi#412]
Running the leabra/examples/pvlv model with the race detector enabled gives the following warning:
`WARNING: DATA RACE
Read at 0x00c00aaabac8 by goroutine 23:
  reflect.typedmemmove()
      /usr/local/Cellar/go@1.13/1.13.15/libexec/src/runtime/mbarrier.go:177 +0x0
  reflect.packEface()
      /usr/local/Cellar/go@1.13/1.13.15/libexec/src/reflect/value.go:119 +0x103
  reflect.valueInterface()
      /usr/local/Cellar/go@1.13/1.13.15/libexec/src/reflect/value.go:1040 +0x16f
  github.com/goki/ki/kit.OnePtrUnderlyingValue()
      /usr/local/Cellar/go@1.13/1.13.15/libexec/src/reflect/value.go:1010 +0xc5
  github.com/emer/etable/etview.(*Plot2DValueView).UpdateWidget()
      /Users/gobbel/go/pkg/mod/github.com/emer/etable@v1.0.16/etview/valueviews.go:357 +0x1fb
  github.com/emer/etable/etview.(*Plot2DValueView).ConfigWidget()
      /Users/gobbel/go/pkg/mod/github.com/emer/etable@v1.0.16/etview/valueviews.go:383 +0x489
  github.com/goki/gi/giv.(*StructView).ConfigStructGrid()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/giv/structview.go:303 +0xe2a
  github.com/goki/gi/giv.(*StructView).Config()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/giv/structview.go:131 +0x446
  github.com/goki/gi/giv.(*StructView).Style2D()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/giv/structview.go:336 +0x75
  github.com/goki/gi/gi.(*Node2DBase).Style2DTree.func1()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/node2d.go:790 +0x97
  github.com/goki/ki/ki.(*Node).FuncDownMeFirst()
      /Users/gobbel/go/pkg/mod/github.com/goki/ki@v1.0.4/ki/node.go:1668 +0xc66
  github.com/goki/gi/gi.(*Node2DBase).Style2DTree()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/node2d.go:784 +0x11d
  github.com/goki/gi/gi.(*Node2DBase).FullRender2DTree()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/node2d.go:725 +0x63
  github.com/goki/gi/gi.(*Viewport2D).FullRender2DTree()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/viewport.go:563 +0xc2
  github.com/goki/gi/gi.(*Viewport2D).UpdateNodes()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/viewport.go:837 +0x63e
  github.com/goki/gi/gi.(*Viewport2D).NodeUpdated()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/viewport.go:749 +0x95
  github.com/goki/gi/gi.SignalViewport2D()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/viewport.go:703 +0x24e
  github.com/goki/ki/ki.(*Signal).Emit()
      /Users/gobbel/go/pkg/mod/github.com/goki/ki@v1.0.4/ki/signal.go:173 +0x1ef
  github.com/goki/ki/ki.(*Node).UpdateEnd()
      /Users/gobbel/go/pkg/mod/github.com/goki/ki@v1.0.4/ki/node.go:1935 +0x259
  github.com/goki/gi/gi.(*Action).ButtonRelease()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/action.go:234 +0x10f
  github.com/goki/gi/gi.(*ButtonBase).MouseEvent.func1()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/buttons.go:454 +0x13c
  github.com/goki/gi/gi.(*WinEventRecv).Call()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/events.go:116 +0xe2
  github.com/goki/gi/gi.(*EventMgr).SendEventSignal()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/events.go:225 +0x3ee
  github.com/goki/gi/gi.(*Window).ProcessEvent()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/window.go:1547 +0x984
  github.com/goki/gi/gi.(*Window).EventLoop()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/window.go:1469 +0x66
  github.com/goki/gi/gi.(*Window).StartEventLoop()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gi/window.go:867 +0x7a
  main.guirun()
      /Users/gobbel/go/src/github.com/emer/leabra/examples/pvlv/pvlv.go:59 +0x46
  main.main.func1()
      /Users/gobbel/go/src/github.com/emer/leabra/examples/pvlv/pvlv.go:53 +0x3a
  github.com/goki/gi/gimain.Main.func1()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/gimain/gimain.go:31 +0x3d
  github.com/goki/gi/oswin/driver/glos.Main.func1()
      /Users/gobbel/go/pkg/mod/github.com/goki/gi@v1.0.16/oswin/driver/glos/app.go:87 +0x7b
`

**Comment by rcoreilly** [comment]
shouldn't be relevant anymore -- see #671 for further checks.
