### ISSUE TITLE
"Cannot find package in any of:" When building Goki Example Outside of goki/gi/examples/

### ISSUE THREAD

**Issue by dmogilevsky** [goki/gi#413]
I'm trying to build a 3D viewer using the Goki Library and wanted to build off the gi3dviewer example provided. I copied the entire folder out of examples and into a separate directory outside of github.com/goki and when i try to build it I get a host of errors in the above format.

I was able to fix some of them by cloning their repositories into the correct file paths (e.g cloning ki into github.com/goki/) but I don't understand why I am not getting this error when I build in examples, only outside of examples. How do I fix this?

Here is a full transcript:
>go build
../../../../../../github.com/goki/gi/giv/filetree.go:22:2: cannot find package "github.com/Masterminds/vcs" in any of:
	/usr/local/go/src/github.com/Masterminds/vcs (from $GOROOT)
	/home/dmogilev/code/src/github.com/Masterminds/vcs (from $GOPATH)
../../../../../../github.com/goki/pi/complete/complete.go:15:2: cannot find package "github.com/akutz/sortfold" in any of:
	/usr/local/go/src/github.com/akutz/sortfold (from $GOROOT)
	/home/dmogilev/code/src/github.com/akutz/sortfold (from $GOPATH)
../../../../../../github.com/goki/gi/giv/himarkup.go:12:2: cannot find package "github.com/alecthomas/chroma" in any of:
	/usr/local/go/src/github.com/alecthomas/chroma (from $GOROOT)
	/home/dmogilev/code/src/github.com/alecthomas/chroma (from $GOPATH)
../../../../../../github.com/goki/gi/giv/himarkup.go:13:2: cannot find package "github.com/alecthomas/chroma/formatters/html" in any of:
	/usr/local/go/src/github.com/alecthomas/chroma/formatters/html (from $GOROOT)
	/home/dmogilev/code/src/github.com/alecthomas/chroma/formatters/html (from $GOPATH)
../../../../../../github.com/goki/pi/filecat/mimetype.go:13:2: cannot find package "github.com/alecthomas/chroma/lexers" in any of:
	/usr/local/go/src/github.com/alecthomas/chroma/lexers (from $GOROOT)
	/home/dmogilev/code/src/github.com/alecthomas/chroma/lexers (from $GOPATH)
../../../../../../github.com/goki/gi/gi/bitmap.go:17:2: cannot find package "github.com/anthonynsimon/bild/transform" in any of:
	/usr/local/go/src/github.com/anthonynsimon/bild/transform (from $GOROOT)
	/home/dmogilev/code/src/github.com/anthonynsimon/bild/transform (from $GOPATH)
../../../../../../github.com/goki/gi/gi/css.go:10:2: cannot find package "github.com/aymerick/douceur/css" in any of:
	/usr/local/go/src/github.com/aymerick/douceur/css (from $GOROOT)
	/home/dmogilev/code/src/github.com/aymerick/douceur/css (from $GOPATH)
../../../../../../github.com/goki/gi/gi/css.go:11:2: cannot find package "github.com/aymerick/douceur/parser" in any of:
	/usr/local/go/src/github.com/aymerick/douceur/parser (from $GOROOT)
	/home/dmogilev/code/src/github.com/aymerick/douceur/parser (from $GOPATH)
../../../../../../github.com/goki/gi/giv/fileinfo.go:18:2: cannot find package "github.com/c2h5oh/datasize" in any of:
	/usr/local/go/src/github.com/c2h5oh/datasize (from $GOROOT)
	/home/dmogilev/code/src/github.com/c2h5oh/datasize (from $GOPATH)
../../../../../../github.com/goki/gi/gi/color.go:15:2: cannot find package "github.com/chewxy/math32" in any of:
	/usr/local/go/src/github.com/chewxy/math32 (from $GOROOT)
	/home/dmogilev/code/src/github.com/chewxy/math32 (from $GOPATH)
../../../../../../github.com/goki/gi/gi/fontstyles.go:14:2: cannot find package "github.com/fatih/camelcase" in any of:
	/usr/local/go/src/github.com/fatih/camelcase (from $GOROOT)
	/home/dmogilev/code/src/github.com/fatih/camelcase (from $GOPATH)
../../../../../../github.com/goki/pi/filecat/mimetype.go:14:2: cannot find package "github.com/gabriel-vasile/mimetype" in any of:
	/usr/local/go/src/github.com/gabriel-vasile/mimetype (from $GOROOT)
	/home/dmogilev/code/src/github.com/gabriel-vasile/mimetype (from $GOPATH)
../../../../../../github.com/goki/gi/oswin/driver/glos/app.go:22:2: cannot find package "github.com/go-gl/gl/v3.3-core/gl" in any of:
	/usr/local/go/src/github.com/go-gl/gl/v3.3-core/gl (from $GOROOT)
	/home/dmogilev/code/src/github.com/go-gl/gl/v3.3-core/gl (from $GOPATH)
../../../../../../github.com/goki/gi/gi/geom3d.go:8:2: cannot find package "github.com/go-gl/mathgl/mgl32" in any of:
	/usr/local/go/src/github.com/go-gl/mathgl/mgl32 (from $GOROOT)
	/home/dmogilev/code/src/github.com/go-gl/mathgl/mgl32 (from $GOPATH)
../../../../../../github.com/goki/gi/gi/font.go:18:2: cannot find package "github.com/goki/freetype/truetype" in any of:
	/usr/local/go/src/github.com/goki/freetype/truetype (from $GOROOT)
	/home/dmogilev/code/src/github.com/goki/freetype/truetype (from $GOPATH)
../../../../../../github.com/goki/gi/oswin/texture.go:17:2: cannot find package "github.com/goki/mat32" in any of:
	/usr/local/go/src/github.com/goki/mat32 (from $GOROOT)
	/home/dmogilev/code/src/github.com/goki/mat32 (from $GOPATH)
../../../../../../github.com/goki/gi/gi/node2d.go:17:2: cannot find package "github.com/goki/prof" in any of:
	/usr/local/go/src/github.com/goki/prof (from $GOROOT)
	/home/dmogilev/code/src/github.com/goki/prof (from $GOPATH)
../../../../../../github.com/goki/gi/giv/diffview.go:22:2: cannot find package "github.com/goki/vci" in any of:
	/usr/local/go/src/github.com/goki/vci (from $GOROOT)
	/home/dmogilev/code/src/github.com/goki/vci (from $GOPATH)
../../../../../../github.com/goki/pi/filecat/mimetype.go:15:2: cannot find package "github.com/h2non/filetype" in any of:
	/usr/local/go/src/github.com/h2non/filetype (from $GOROOT)
	/home/dmogilev/code/src/github.com/h2non/filetype (from $GOPATH)
../../../../../../github.com/goki/gi/giv/textbuf/diff.go:12:2: cannot find package "github.com/ianbruene/go-difflib/difflib" in any of:
	/usr/local/go/src/github.com/ianbruene/go-difflib/difflib (from $GOROOT)
	/home/dmogilev/code/src/github.com/ianbruene/go-difflib/difflib (from $GOPATH)
../../../../../../github.com/goki/gi/gi/dialogs.go:13:2: cannot find package "github.com/iancoleman/strcase" in any of:
	/usr/local/go/src/github.com/iancoleman/strcase (from $GOROOT)
	/home/dmogilev/code/src/github.com/iancoleman/strcase (from $GOPATH)
../../../../../../github.com/goki/ki/ki/node.go:31:2: cannot find package "github.com/jinzhu/copier" in any of:
	/usr/local/go/src/github.com/jinzhu/copier (from $GOROOT)
	/home/dmogilev/code/src/github.com/jinzhu/copier (from $GOPATH)
../../../../../../github.com/goki/gi/giv/fileview.go:25:2: cannot find package "github.com/mitchellh/go-homedir" in any of:
	/usr/local/go/src/github.com/mitchellh/go-homedir (from $GOROOT)
	/home/dmogilev/code/src/github.com/mitchellh/go-homedir (from $GOPATH)
../../../../../../github.com/goki/gi/gi/color.go:19:2: cannot find package "github.com/srwiley/rasterx" in any of:
	/usr/local/go/src/github.com/srwiley/rasterx (from $GOROOT)
	/home/dmogilev/code/src/github.com/srwiley/rasterx (from $GOPATH)
../../../../../../github.com/goki/gi/gi/paint.go:21:2: cannot find package "github.com/srwiley/scanx" in any of:
	/usr/local/go/src/github.com/srwiley/scanx (from $GOROOT)
	/home/dmogilev/code/src/github.com/srwiley/scanx (from $GOPATH)

**Comment by rcoreilly** [comment]
are you using go.mod modules?  that is recommended.  e.g., do `go mod init`

**Comment by dmogilevsky** [comment]
That fixed it. You're an absolute God. Thank you
