### ISSUE TITLE
how to drag a View to The Finder ,get filepath in Finder 

### ISSUE THREAD

**Issue by bing050802** [goki/gi#415]
I want to be cloud,drap a file in cloud to Finder(or window explorer) ，can get path ,and download cloud file

**Comment by rcoreilly** [comment]
I couldn't understand this question -- need more context etc. maybe you could open on new Discussions tool and I'll close this as an issue just to keep this cleaner.

**Comment by bing050802** [comment]
just like this: https://www.electronjs.org/docs/tutorial/native-file-drag-drop
