### ISSUE TITLE
Pulldown menu: mouse selection fails for lower items

### ISSUE THREAD

**Issue by rgobbel** [goki/gi#416]
In the PVLV model, the "Grain" menu fails to enter the selection, if you try to select anything lower on the menu than "AlphaCycle". I suspect this may be related to the fact that the menu overlies the NetView, but changing the parent widget when creating the menu so far has not helped. It is possible to select by using the up and down cursor keys, followed by Enter.

**Comment by rcoreilly** [comment]
fixed in gogi.  new mod versions forthcoming.
