### ISSUE TITLE
Clicking Prefs override box causes it to disappear

### ISSUE THREAD

**Issue by thazy** [goki/gi#42]
![img_0153](https://user-images.githubusercontent.com/30027010/44474998-2ddd9d80-a5f1-11e8-923f-bc488c55f7b7.JPG)

**Comment by rcoreilly** [comment]
can you replicate? I can't..

**Comment by thazy** [comment]
Yes, I tried clicking it on, then hitting 'Update' and then clicking in the box again - and it disappeared again.  Seems likely that's what I had done the first time also.

**Comment by rcoreilly** [comment]
btw I can now reproduce and will fix at some point.

**Comment by rcoreilly** [comment]
finally got this one fixed!
