### ISSUE TITLE
windows opengl errors invalid operation

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#430]
from @dmogilevsky in #429 discussions

Hello, I am getting three different glos gl errors while running my Goki 3D viewer (based off the example gi3dviewer) and can't figure out what is causing them. While they don't break the viewer, I output important information to the terminal and sometimes I get these errors in such quantities it hides the information I am trying to print.

I get the following errors:

glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
glos gl error in context: sld render:
These errors are all followed by:

502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.

I get these often when opening a new window, and sometimes when trying to rotate or interact with my rendered model. They are consistent when opening new windows I've created, for example when opening up a dialog window with checkboxes, I always get the following in the terminal:

2020/12/30 15:44:54 glos gl error in context: Uniform SetValue: AmbLights type: {Float32 3 0}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2020/12/30 15:44:54 glos gl error in context: sld render:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2020/12/30 15:44:54 glos gl error in context: sld render:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2020/12/30 15:44:54 glos gl error in context: sld render:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2020/12/30 15:44:54 glos gl error in context: sld render:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2020/12/30 15:44:54 glos gl error in context: sld render:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2020/12/30 15:44:54 glos gl error in context: sld render:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2020/12/30 15:44:54 glos gl error in context: sld render:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.
2020/12/30 15:44:54 glos gl error in context: Uniform SetValue: mvp type: {Float32 0 3}:
502 = INVALID_OPERATION: Given when the set of state for a command is not legal for the parameters given to that command. It is also given for commands where combinations of parameters define what the legal parameters are.

Sometimes when opening the file select window which came with the gi3dviewer example, I also get one of these errors.

Any advice is appreciated.

Thanks,
Daniel

**Comment by rcoreilly** [comment]
I'm pretty sure the cause of this bug in the first place is printing to the console!  It was happening to me because I had left a debug print statement in the code, and when I removed that, it was very hard to trigger.  Then I went to gogi preferences and turned on debug logging of various events, and it happened quickly.  Somehow, when a golang thread prints to stdout, it is losing its opengl context or something to that effect.

And the fact that the error itself prints to the console likely causes it to perpetuate.

I'll experiment with some potential fixes, but an immediate work-around would be to try writing output to a file instead of to stdout.

**Comment by rcoreilly** [comment]
this seems to be working for me -- if Daniel can provide a confirmation that would be great -- releasing new version in any case

**Comment by dmogilevsky** [comment]
I just tried it again and am still having issues. I am building this on a remote Linux system. I tried removing all of my printing to terminal, and I verified that I received the update by checking version.go. I am getting the errors exactly as before :/

**Comment by rcoreilly** [comment]
it seems strange that it would still print the errors because those specific cases of "Uniform SetValue" errors should not print out anymore.  I looked for other paths where they might be printed -- it is possible but I couldn't see any.  If you have your own package with a go.mod that specifies gi version, did you double check to update that?  that is what determines what is used during build under go modules -- i've made that mistake several times.

also, a remote linux system might introduce some lags in the rendering that could produce a similar issue, even without the printing -- but again I would have expected the update to stop printing those messages.

if you can set a breakpoint in goki/gi/oswin/driver/glos/gpu.go:112 (in your IDE or dlv), that is where the "gl glos err in context" error is generated, so sending the back trace from that point could give some clues as to the source of it.

**Comment by dmogilevsky** [comment]
You were right, I didn't do the update correctly. Now that I have applied the update correctly, those error messages are gone.

Thanks again for the help, I greatly appreciate it!
