### ISSUE TITLE
go get command for bindata may need -u flag

### ISSUE THREAD

**Issue by StephenJRead** [goki/gi#444]
I tried installing bindata using the go get command in the web page, but it didn't work. I went to the bindata github page and they had the -u flag in the command.

go get -u github.com/shuLhan/go-bindata/...

**Comment by rcoreilly** [comment]
updated wiki.  i have no idea why that would be the case but whatever works!

**Comment by StephenJRead** [comment]
although I see that the new version of go with the embed command is now  out.

Sent from my iPhone

On Feb 17, 2021, at 1:02 AM, rcoreilly <notifications@github.com> wrote:

﻿

updated wiki. i have no idea why that would be the case but whatever works!
