### ISSUE TITLE
add optional Icons list to ComboBox -- list of IconNames to show for each item

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#445]
along with option to either only show icon or icon + name

**Comment by rcoreilly** [comment]
better yet: added IconName list -- just display the icons.  If you need text, add to icon?

**Comment by kkoreilly** [comment]
This does not solve the common use case in which you want text options with supplemental icons. An optional slice of icons should be added to support this.

**Comment by rcoreilly** [comment]
done!
