### ISSUE TITLE
x86_64-w64-mingw32/bin/ld.exe: error: export ordinal too large: 66622

### ISSUE THREAD

**Issue by naowang** [goki/gi#449]
M:/work/tool/go1.15.8.windows-amd64/bin/go.exe build [M:/work/code/go/src/github.com/goki/gi/examples/basic]
# github.com/goki/gi/examples/basic
M:\work\tool\go1.15.8.windows-amd64\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
M:/work/tool/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: export ordinal too large: 66622
collect2.exe: error: ld returned 1 exit status

**Comment by rcoreilly** [comment]
On Windows you need to do `$ go build -buildmode exe`  if it doesn't work with just plain go build -- this will be fixed at some point but not sure when: https://github.com/golang/go/issues/40795

**Comment by naowang** [comment]
now it's ok. thanks.
