### ISSUE TITLE
Choosing Value type for CSS style setting caused crash

### ISSUE THREAD

**Issue by thazy** [goki/gi#45]
In WinVP, adding new style setting (?), then changing type (fm string) to Value caused crash:

thazy@macbookpro ~/go/src/github.com/goki/gi/examples/widgets$ ./widgets
Received button signal: ButtonPressed from button: button2
Received button signal: ButtonReleased from button: button2
Received button signal: ButtonClicked from button: button2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x42def9d]

goroutine 115 [running]:
image.(*RGBA).Bounds(...)
	/usr/local/Cellar/go/1.10.3/libexec/src/image/image.go:72
github.com/goki/gi.(*Viewport2D).ComputeBBox2D(0xc4202e7000, 0x0, 0x0, 0x0, 0x0, 0xfffffffffffffc60, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/viewport2d.go:316 +0x2d
github.com/goki/gi.(*WidgetBase).Move2DBase(0xc4202e7000, 0xfffffffffffffc60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/widget.go:372 +0xf1
github.com/goki/gi.(*Viewport2D).Move2D(0xc4202e7000, 0xfffffffffffffc60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/viewport2d.go:390 +0x6d
github.com/goki/gi.(*Node2DBase).Move2DChildren(0xc42b9cc900, 0xfffffffffffffc60, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:555 +0x152
github.com/goki/gi.(*WidgetBase).Move2D(0xc42b9cc900, 0xfffffffffffffc60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/widget.go:377 +0x8f
github.com/goki/gi.(*Node2DBase).Move2DChildren(0xc42fafdd88, 0xfffffffffffffc60, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:555 +0x152
github.com/goki/gi.(*Layout).Move2D(0xc42fafdd88, 0xfffffffffffffc60, 0x0, 0x20, 0x211, 0x533, 0x25e)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1538 +0xd3
github.com/goki/gi.(*PartsWidgetBase).Move2D(0xc42fafd980, 0xfffffffffffffc60, 0x0, 0x20, 0x211, 0x533, 0x25e)
	/Users/thazy/go/src/github.com/goki/gi/widget.go:749 +0xed
github.com/goki/gi.(*Node2DBase).Move2DChildren(0xc42e806408, 0xfffffffffffffc60, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:555 +0x152
github.com/goki/gi.(*Layout).Move2D(0xc42e806408, 0xfffffffffffffc60, 0x0, 0x20, 0x7d, 0x760, 0x539)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1538 +0xd3
github.com/goki/gi.(*PartsWidgetBase).Move2D(0xc42e806000, 0xfffffffffffffc60, 0x0, 0x20, 0x7d, 0x760, 0x539)
	/Users/thazy/go/src/github.com/goki/gi/widget.go:749 +0xed
github.com/goki/gi.(*Node2DBase).Move2DChildren(0xc42b89c500, 0xfffffffffffffc60, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:555 +0x152
github.com/goki/gi.(*Layout).Move2D(0xc42b89c500, 0x0, 0x0, 0x10, 0x6d, 0x770, 0x5f6)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1538 +0xd3
github.com/goki/gi.(*WidgetBase).Move2DTree(0xc42b89c500)
	/Users/thazy/go/src/github.com/goki/gi/widget.go:393 +0x185
github.com/goki/gi.(*Layout).SetScroll.func1(0x461ad40, 0xc42b89c500, 0x461ca40, 0xc429000000, 0x0, 0x44bb8e0, 0xc42b92dd18)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1097 +0x8c
github.com/goki/ki.(*Signal).Emit(0xc429001af8, 0x461ca40, 0xc429000000, 0x0, 0x44bb8e0, 0xc42b92dd18)
	/Users/thazy/go/src/github.com/goki/ki/signal.go:157 +0x1b6
github.com/goki/gi.(*SliderBase).SetValueAction(0xc429000000, 0x44680e00)
	/Users/thazy/go/src/github.com/goki/gi/sliders.go:269 +0xd6
github.com/goki/gi.(*Layout).ScrollDelta(0xc42b89c500, 0xfffffffffffffffe, 0x1, 0x461bbc0)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1175 +0x84
github.com/goki/gi.(*Layout).LayoutScrollEvents.func1(0x461ad40, 0xc42b89c500, 0x461f960, 0xc4201ff600, 0x3, 0x4543440, 0xc42919ce40)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1407 +0x9b
github.com/goki/gi.(*WinEventRecv).Call(0xc428f19dd0, 0x461f960, 0xc4201ff600, 0x3, 0x4543440, 0xc42919ce40)
	/Users/thazy/go/src/github.com/goki/gi/window.go:1081 +0x6d
github.com/goki/gi.(*Window).SendEventSignal(0xc4201ff600, 0x4614b40, 0xc42919ce40, 0x1d50a501)
	/Users/thazy/go/src/github.com/goki/gi/window.go:1195 +0xc65
github.com/goki/gi.(*Window).EventLoop(0xc4201ff600)
	/Users/thazy/go/src/github.com/goki/gi/window.go:960 +0xd5a
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/thazy/go/src/github.com/goki/gi/window.go:438 +0x3f
thazy@macbookpro ~/go/src/github.com/goki/gi/examples/widgets$

**Comment by rcoreilly** [comment]
most of your crash reports have the same stack trace -- if there is any way you can reproduce these, I would love to get a debugger on it and find out what is going on!  or maybe, hopefully, it was fixed already??  please re-open if you get it again, hopefully replicably (I couldn't replicate).
