### ISSUE TITLE
some unicode can not correct showing

### ISSUE THREAD

**Issue by runsys** [goki/gi#454]
I use the unicode font unifont-14.0.ttf,  gi is the latest. os windows 11.  but it can not full support showing.
And  the edit ct l + v reaction has some low speed when I use the Hot virtual keyboard.
![gi some unicode can not correct showing](https://user-images.githubusercontent.com/35724927/152663497-354ad085-ffb1-4331-aa52-138bd26584d1.png)

**Comment by rcoreilly** [comment]
textview uses monospaced font - unifont-14 is not..

**Comment by rcoreilly** [comment]
This will be fixed as part of this: #568

**Comment by kkoreilly** [comment]
Closing as part of the more general #568.
