### ISSUE TITLE
SetInactive doesn't work as expected on SliceView (haven't checked other views)

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#459]
Setting the sliceview to inactive doesn't stop me from editing the values.

**Comment by rcoreilly** [comment]
That def works in some form - used as selector

**Comment by rcoreilly** [comment]
See select* in giv/ dialogs for examples

**Comment by rohrlich** [comment]
Nothing different in that code than mine but I did observe something interesting! As soon as I scrolled the string fields went readonly but the float fields didn't.

**Comment by rcoreilly** [comment]
u need to set inactive before setslice / config
