### ISSUE TITLE
Clicking Update with cursor still in text editing field in GoGi editor erases text

### ISSUE THREAD

**Issue by thazy** [goki/gi#46]
...my expected behavior seems that it would save, then Update/Apply.  If I go ahead and leave the text editing field then it gets temp-saved that can be presumably Updated, etc.

**Comment by rcoreilly** [comment]
Yep, clearly needs fixed -- I have a good plan I think..  related to #37 -- textfield will have a "FocusActive" flag, and window will send a notification to focus object whenever someone clicks somewhere else -- textfield will apply changes, but still have focus but not be "active"..

**Comment by rcoreilly** [comment]
see #37 for further discussion.
