### ISSUE TITLE
SliceView layout is altered by using NoAdd, NoDelete or SetInactiveState

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#460]
Completely unexpected behavior. Without the NoAdd or NoDelete or SetInactiveState the sliceview has one element per row. But with NoAdd or NoDelete I get 4 elements per row and with SetInactiveState() I get 2 elements per row.

**Comment by rohrlich** [comment]
1 - How the slice should look
2 + 3 - How the slice shouldn't look
<img width="673" alt="Screen Shot 2022-03-27 at 9 42 41 PM" src="https://user-images.githubusercontent.com/22350787/160330970-da108279-7108-44bd-90b9-ce9b83712b40.png">
<img width="339" alt="Screen Shot 2022-03-27 at 9 43 15 PM" src="https://user-images.githubusercontent.com/22350787/160330976-30a1fb9b-d13d-46f0-ab57-4bc29e287768.png">
<img width="358" alt="Screen Shot 2022-03-27 at 9 44 38 PM" src="https://user-images.githubusercontent.com/22350787/160330977-0a0a3873-9292-494c-9737-326240a23e6f.png">

**Comment by rcoreilly** [comment]
this should be a tableview if slice el is struct

also timing issues of setting those opts / flags are key per prior comments

**Comment by rcoreilly** [comment]
it was the timing: must be in place prior to setslice which configs
