### ISSUE TITLE
How can I get the camera picture and microphone sound of the local machine?

### ISSUE THREAD

**Issue by dht-hedaihua** [goki/gi#464]
Hi，In my project, if I need the client to access the camera and microphone of this machine, how can I use GI to realize it? thank you.

**Comment by rcoreilly** [comment]
Sorry no support for that -- you'd have to find other go packages that provide support.  we're using glfw for cross-platform back-end support and I don't think it covers those things.  There are some decent sound playing packages.

It would be good to add a Video widget at some point -- has been on my mental list for a while.

**Comment by rcoreilly** [comment]
closed with #516 as main ticket for this.
