### ISSUE TITLE
Suggestions and questions about getting started quickly

### ISSUE THREAD

**Issue by dht-hedaihua** [goki/gi#465]
Hi，In the process of using “goki/gi”, I found that there is a serious lack of systematic API documents and friendly tutorials. I can only explore and ponder one by one through various annotation methods or demo projects. Can there be a relatively complete API documentation system and a relatively friendly tutorial website for various components and capabilities? thank you.

**Comment by rcoreilly** [comment]
Yeah mainly it is the examples and then the go-generated docs, and whatever your IDE provides.. examples should provide a lot of the basics.  writing tutorials is probably a bit beyond my capacity limits at this time unfortunately..

**Comment by rcoreilly** [comment]
closed with #491 as main ticket for this.
