### ISSUE TITLE
Building widgets example fails

### ISSUE THREAD

**Issue by Delta-VII** [goki/gi#469]
Hi, I am on OpenSuse Tumbleweed and try to build the widget example.

The process fails with the following output:

> kai@localhost:~/go/gi/examples/widgets> make
> go build -v
> github.com/go-gl/glfw/v3.3/glfw
> In Datei, eingebunden von ../../../pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220516021902- eb3e265c7661/c_glfw_lin.go:20:
../../../pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220516021902-eb3e265c7661/glfw/src/x11_window.c:30: Warnung: »_GNU_SOURCE« redefiniert
   30 | #define _GNU_SOURCE
      | 
<Kommandozeile>: Anmerkung: dies ist die Stelle der vorherigen Definition
github.com/goki/vgpu/vgpu
> github.com/goki/vgpu/vgpu
> ../../../pkg/mod/github.com/goki/vgpu@v0.0.0-20220523102422-0483af84b12d/vgpu/gpu.go:253:13: undefined: kit.StringJSON
make: *** [Makefile:13: build] Fehler 2

**Comment by rcoreilly** [comment]
Thanks for the report -- currently rewriting things to use vulkan - check out prior tagged release if you want something reliable.  I'll be updating go.mod versions and making a new release soon -- haven't tried anything on other platforms yet!

**Comment by rcoreilly** [comment]
I just pushed an update that should build now.  3D forthcoming..
