### ISSUE TITLE
Compile example error

### ISSUE THREAD

**Issue by Dorbmon** [goki/gi#470]
```
main.go imports
        github.com/goki/gi/gimain imports
        github.com/goki/gi/giv imports
        github.com/goki/gi/giv/textbuf imports
        github.com/ianbruene/go-difflib/difflib tested by
        github.com/ianbruene/go-difflib/difflib.test imports
        ./tester: "./tester" is relative, but relative import paths are not supported in module mode
```
This occurs on go1.8.2.
Maybe should consider fixing the bug by fork "go-difflib" if the owner doesn't have the time to fix it. It is just a one-line work to do.

**Comment by rcoreilly** [comment]
I have fixed it in master but not quite ready for release.  see goki/go-difflib

**Comment by Dorbmon** [comment]
> I have fixed it in master but not quite ready for release. see goki/go-difflib

Any help needed?

**Comment by rcoreilly** [comment]
fixed in release..
