### ISSUE TITLE
library not found for -lMoltenVK

### ISSUE THREAD

**Issue by Wsyspringsun** [goki/gi#479]
I have installed VulkanSDK to  ~/VulkanSDK/1.3.216.0,but when go build under /examples/widgets failed with error "library not found for -lMoltenVK" .how to fix it

**Comment by rcoreilly** [comment]
Linux or mac?  in any case, maybe you need to update your LD_LIBRARY_PATH?  On the mac it installed into /usr/local/lib which you can add to your path -- just google LD_LIBRARY_PATH if you don't know it..
