### ISSUE TITLE
Time delay for tooltip text to display (GoGi Editor) is longer than I'm used to

### ISSUE THREAD

**Issue by thazy** [goki/gi#48]
...I'd say significantly so.

**Comment by rcoreilly** [comment]
Here's some discussion:
https://ux.stackexchange.com/questions/358/how-long-should-the-delay-be-before-a-tooltip-pops-up

looks like 500-1000 msec is suggested.  I personally like it slower so they don't get in my way, as suggested by one of the commentators.

It was set to 1500 so I reduced to 1000.

Also It is now configurable in detailed params, so you can set it faster if you want (HoverStartMSec)
