### ISSUE TITLE
Problem with vgpu when installing GoGi and building widgets

### ISSUE THREAD

**Issue by StephenJRead** [goki/gi#481]
Just tried to install gogi and build widgets.  Latest version of macOS BigSur and go1.19.  Got the following error.

[github.com/goki/gi/gimain](http://github.com/goki/gi/gimain)
[github.com/goki/gi/examples/widgets](http://github.com/goki/gi/examples/widgets)
reads-Mac-mini:widgets read$ ./widgets
panic: vulkan error: vulkan error: incompatible driver (-9) on /Users/read/go/pkg/mod/[github.com/goki/vgpu@v1.0.5/vgpu/errors.go:23](http://github.com/goki/vgpu@v1.0.5/vgpu/errors.go:23) (0x459d1be)
	NewError: pc, _, _, ok := runtime.Caller(0)

goroutine 1 [running, locked to thread]:
[github.com/goki/vgpu/vgpu.IfPanic](http://github.com/goki/vgpu/vgpu.IfPanic)(...)
	/Users/read/go/pkg/mod/[github.com/goki/vgpu@v1.0.5/vgpu/errors.go:40](http://github.com/goki/vgpu@v1.0.5/vgpu/errors.go:40)
[github.com/goki/vgpu/vgpu](http://github.com/goki/vgpu/vgpu).(*GPU).Config(0xc00043b000, {0x4e12151?, 0x4e42ef3?})
	/Users/read/go/pkg/mod/[github.com/goki/vgpu@v1.0.5/vgpu/gpu.go:172](http://github.com/goki/vgpu@v1.0.5/vgpu/gpu.go:172) +0xbb5
[github.com/goki/gi/oswin/driver/vkos](http://github.com/goki/gi/oswin/driver/vkos).(*appImpl).initVk(0x5f0db80)
	/Users/read/go/gi/oswin/driver/vkos/app.go:195 +0x22a
[github.com/goki/gi/oswin/driver/vkos.Main](http://github.com/goki/gi/oswin/driver/vkos.Main)(0x4bba0a0?)
	/Users/read/go/gi/oswin/driver/vkos/app.go:74 +0x45
[github.com/goki/gi/oswin/driver.driverMain](http://github.com/goki/gi/oswin/driver.driverMain)(...)
	/Users/read/go/gi/oswin/driver/driver_vkos.go:18
[github.com/goki/gi/oswin/driver.Main](http://github.com/goki/gi/oswin/driver.Main)(...)
	/Users/read/go/gi/oswin/driver/driver.go:27
[github.com/goki/gi/gimain.Main](http://github.com/goki/gi/gimain.Main)(0x4efe160?)
	/Users/read/go/gi/gimain/gimain.go:31 +0x57
main.main()
	/Users/read/go/gi/examples/widgets/widgets.go:24 +0x25
reads-Mac-mini:widgets read$

**Comment by rcoreilly** [comment]
did you do this new step:

> As of June 2022, the new Vulkan-based version 1.3.0+ requires the vulkan sdk to be installed: https://vulkan.lunarg.com/sdk/home

from the install wiki?

**Comment by rcoreilly** [comment]
I just tried the latest 1.3.216.0 version and it seems to fail entirely -- I don't even get as far as you!  I didn't uninstall the previous one so perhaps that was my error.  In any case, use the previous 1.3.211.0 version for now!

**Comment by StephenJRead** [comment]
Okay thanks. I did do the vulkan step with the latest version of vulkan. Will try previous version

Sent from my iPhone

On Aug 19, 2022, at 11:52 PM, rcoreilly ***@***.***> wrote:

﻿

I just tried the latest 1.3.216.0 version and it seems to fail entirely -- I don't even get as far as you! I didn't uninstall the previous one so perhaps that was my error. In any case, use the previous 1.3.211.0 version for now!

**Comment by StephenJRead** [comment]
I just installed the April version and reinstalled goki, just to be safe and widgets now builds and runs fine.  Later tonight I will move onto installing emergent.


Stephen J. Read, Mendel B. Silberberg Professor of Social Psychology
3620 McClintock Ave, 821 SGM
University of Southern California
Los Angeles, CA 90089-1061
***@***.******@***.***>

On Aug 19, 2022, at 11:52 PM, rcoreilly ***@***.******@***.***>> wrote:



I just tried the latest 1.3.216.0 version and it seems to fail entirely -- I don't even get as far as you! I didn't uninstall the previous one so perhaps that was my error. In any case, use the previous 1.3.211.0 version for now!

**Comment by rcoreilly** [comment]
looks like this is fixed.
