### ISSUE TITLE
Character display error

### ISSUE THREAD

**Issue by ligaolin** [goki/gi#484]
![image](https://user-images.githubusercontent.com/73518955/206903137-2e0d0892-7753-42e2-b2e6-a1987d36038b.png)

**Comment by rcoreilly** [comment]
You need to select a font that supports more of unicode -- click on the gogi preferences and then on the font selector to see which ones render properly.

**Comment by DukeHuangWP** [comment]
Not working for □ ■  〄 ♂ ♀ ♫ ♪ ♩ ❤ ♥ ღ ❥ ✧ ★ ☆ ✰ ✪ ✡
by [Noto Sans Traditional Chinese](https://fonts.google.com/noto/specimen/Noto+Sans+TC)

![未命名](https://user-images.githubusercontent.com/50649793/224465937-ddb864c6-32cf-4f83-bcf3-51d354844391.png)

**Comment by rcoreilly** [comment]
It will potentially work better now with the latest 1.3.17 release -- update here if you get a chance.

**Comment by DukeHuangWP** [comment]
1.3.17 batter but not good enough in terms of Unicode support.  
![未命名](https://user-images.githubusercontent.com/50649793/228725560-10c1659d-6e93-4521-a09b-a7c90b8e4245.png)

**Comment by rcoreilly** [comment]
see #486 for a potential solution. If you have access to a Mac, you might give a try there -- should be better.  In any case, if you happen to know about standard unicode fonts on linux or windows, please update that issue.

**Comment by kkoreilly** [comment]
Closing in favor of the more general #568.
