### ISSUE TITLE
Add Mobile Support

### ISSUE THREAD

**Issue by kkoreilly** [goki/gi#488]
Currently planning to implement mobile and web support by writing a Go wrapper of [brackeen/glfm](https://github.com/brackeen/glfm)

**Comment by kkoreilly** [comment]
Will implement mobile support through a fork of [golang/mobile](https://github.com/golang/mobile) (at [goki/mobile](https://github.com/goki/mobile)), and web support will be separate (likely through GopherJS).

**Comment by ddkwork** [comment]
> Will implement mobile support through a fork of [golang/mobile](https://github.com/golang/mobile) (at [goki/mobile](https://github.com/goki/mobile)), and web support will be separate (likely through GopherJS).

Hello, I searched through the doc, issue and readme and couldn't find the command to build the apk, can you elaborate on that? What should I do after the SDK and NDK are added to the PATH?

**Comment by kkoreilly** [comment]
Apologies for the missing documentation; it will be improved very soon for the v2 release, but we have been focusing on developing the framework first. You need to install the goki tool (`go install goki.dev/goki@latest`) and then you can run `goki build -t android` to build the apk (it will be put at `.goki/bin/build/appname.apk`). You can also run `goki install -t android` or `goki run -t android` to install the app to the device or install and run it in addition to building it, respectively.

**Comment by kkoreilly** [comment]
Also, for web, you can use `goki build -t js` and `goki run -t js`.

**Comment by kkoreilly** [comment]
(And for ios you can use the same commands as android but with `ios` instead of `android`. Also, if your os architecture is different from that of the target mobile device, you may need to add the architecture of the target device; eg: `goki run -t ios/arm64`).

**Comment by ddkwork** [comment]
> Apologies for the missing documentation; it will be improved very soon for the v2 release, but we have been focusing on developing the framework first. You need to install the goki tool (`go install goki.dev/goki@latest`) and then you can run `goki build -t android` to build the apk (it will be put at `.goki/bin/build/appname.apk`). You can also run `goki install -t android` or `goki run -t android` to install the app to the device or install and run it in addition to building it, respectively.

very nice，i will try, thx you.

**Comment by kkoreilly** [comment]
If you install the latest version of the core tool (`go install cogentcore.org/core/core@main`), I have updated the commands so that you no longer need to use `-t` (eg: `core run android` instead of `core run -t android`).
