### ISSUE TITLE
In GoGi Editor -> CSS map dialog, color bleeds outside 'Add' button

### ISSUE THREAD

**Issue by thazy** [goki/gi#51]
![img_0156](https://user-images.githubusercontent.com/30027010/44594060-5c3eb280-a782-11e8-91e1-28c2fccf7f50.JPG)

**Comment by rcoreilly** [comment]
that is actually the proper styling for a button in a toolbar -- just not very clear that it is a toolbar with just one button.  added stretch to all toolbars so it is clearer that they are bars and not just buttons.
