### ISSUE TITLE
Use specific and direct style declarations

### ISSUE THREAD

**Issue by kkoreilly** [goki/gi#517]
Example: Instead of
```go
label.SetProp("background-color", "blue")
```
Do:
```go
label.Style.Background.Color = colors.Blue
```
This will allow for setting styles with editor autocompletion support, documentation, and error checking. With the current situation, you have no idea what properties there are, what they do, and what values they support. If you spell something incorrectly, set a property to an incompatible value, or use the wrong property for a task, you will have no idea of the error until you compile, run, and test the app. Even worse, it is impossible to easily discover what properties can even be set; we only support a subset of CSS, so CSS documentation is not definitive. 
The setting of styles through CSS / SetProp would be neither deprecated nor removed, as CSS is a widely used and helpful tool that people may be already used to using, but the specific and direct assignment would be the recommended approach.

**Comment by rohrlich** [comment]
Yes!

**Comment by kkoreilly** [comment]
Prop and CSS-based styling will be removed from Gi with this change. This is because it makes sense to only have one idiomatic way to do something and not multiple conflicting ways. The existing prop-based styling codebase is a nightmare, and supporting it would take a lot of time with little to no benefit. Instead, support for CSS styling will be moved to [goki/glide](https://github.com/goki/glide), which is where it is actually needed. This will make the core Gi codebase cleaner and clearly separate it from the implementation of web support.

**Comment by kkoreilly** [comment]
This has been implemented.
