### ISSUE TITLE
For slider1 changing step size to 0.5 froze the position fm which I couldn't move it.

### ISSUE THREAD

**Issue by thazy** [goki/gi#52]
Even when changed back to 0.1 I still couldn't make the slider position budge.

![img_0157](https://user-images.githubusercontent.com/30027010/44594765-58ac2b00-a784-11e8-88b9-fff39a227599.JPG)
![img_0158](https://user-images.githubusercontent.com/30027010/44594767-5944c180-a784-11e8-88ea-7a8ea4eb382c.JPG)

**Comment by rcoreilly** [comment]
reopen if reproducible.
