### ISSUE TITLE
Consider removing constant Update and UpdateView buttons everywhere

### ISSUE THREAD

**Issue by kkoreilly** [goki/gi#527]
It looks very unprofessional, takes up space, and should not be necessary. It should be possible and easy to create UIs in which everything automatically updates when it needs to.

**Comment by rohrlich** [comment]
Agree, and it can be confusing as to which view/content is being updated. I do know that it can be tricky to catch everything that should generate an update so having a manual update that isn't so prominent might be helpful.

**Comment by kkoreilly** [comment]
An app/window-wide update button under the window main menu could work. This still does not solve the problem in dialog windows, so that would need to be figured out. Also, F5 already works to update on Windows and maybe other operating systems, but this should be confirmed and clearly documented.
