### ISSUE TITLE
Cannot re-enter a text editing field.

### ISSUE THREAD

**Issue by thazy** [goki/gi#55]
In the edit1 text edit field I entered some text then looked at edit1 node of the WinVp tree to watch the text field updating.  However, when I went back to the widgets window I couldn't get the focus to re-enter that field to continue entering text. FYI, I could enter text in the actual editor's text field, then exit that field by clicking in a different field, then click 'Update' to update the text in the widgets window edit1 text field. FYI, clicking Update before exiting the editor text field still clears the new entries (instead of "taking" and then updating the widgets window. 

ALSO, using the <- or -> arrows sometimes made the cursor jump to the next edit field (integers; named 'spin' in the WinVp tree).

![img_0159](https://user-images.githubusercontent.com/30027010/44602708-9c5f5e80-a79d-11e8-8251-919d6f2fd97b.JPG)
g

**Comment by rohrlich** [comment]
Related or same as #43

**Comment by rcoreilly** [comment]
should be fixed -- please pound hard on this stuff to make sure! :)
