### ISSUE TITLE
undefined...

### ISSUE THREAD

**Issue by lnhks** [goki/gi#556]
# github.com/goki/vulkan
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\errors.go:8:19: undefined: Result
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:11:16: undefined: Semaphore
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:13:12: undefined: Fence
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:15:19: undefined: DeviceMemory
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:17:13: undefined: Buffer
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:19:12: undefined: Image
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:21:12: undefined: Event
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:23:16: undefined: QueryPool
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:25:17: undefined: BufferView
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:27:16: undefined: ImageView
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:27:16: too many errors

**Comment by kkoreilly** [comment]
What code are you building and on what platform?

**Comment by lnhks** [comment]
It works on Windows, and Mingw-w64 GCC is included
I follow the steps below
>cd gitest
>go mod init gitest
>go get github.com/goki/gi@v1.3.21
go: added github.com/goki/gi v1.3.21
then I copy the example from "https://goki.dev/docs/gi/gettingstarted/helloworld/#make-a-simple-app" to main.go
>go mod tidy
go: finding module for package github.com/goki/gi/gimain
go: finding module for package github.com/goki/gi/gi
go: found github.com/goki/gi/gi in github.com/goki/gi v1.3.21
go: found github.com/goki/gi/gimain in github.com/goki/gi v1.3.21
>go run main.go
# github.com/goki/vulkan
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\errors.go:8:19: undefined: Result
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:11:16: undefined: Semaphore
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:13:12: undefined: Fence
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:15:19: undefined: DeviceMemory
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:17:13: undefined: Buffer
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:19:12: undefined: Image
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:21:12: undefined: Event
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:23:16: undefined: QueryPool
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:25:17: undefined: BufferView
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:27:16: undefined: ImageView
..\..\..\go\pkg\mod\github.com\goki\vulkan@v1.0.6\vk_null64.go:27:16: too many errors


and the auto genfile go.mod:

module gitest
go 1.20
require github.com/goki/gi v1.3.21
require (
	github.com/BurntSushi/freetype-go v0.0.0-20160129220410-b763ddbfe298 // indirect
	github.com/BurntSushi/graphics-go v0.0.0-20160129215708-b43f31a4a966 // indirect
	github.com/BurntSushi/xgb v0.0.0-20210121224620-deaf085860bc // indirect
	github.com/BurntSushi/xgbutil v0.0.0-20190907113008-ad855c713046 // indirect
	github.com/Masterminds/vcs v1.13.3 // indirect
	github.com/akutz/sortfold v0.2.1 // indirect
	github.com/alecthomas/chroma/v2 v2.7.0 // indirect
	github.com/anthonynsimon/bild v0.13.0 // indirect
	github.com/antonmedv/expr v1.12.5 // indirect
	github.com/aymerick/douceur v0.2.0 // indirect
	github.com/c2h5oh/datasize v0.0.0-20220606134207-859f65c6625b // indirect
	github.com/dlclark/regexp2 v1.8.1 // indirect
	github.com/fatih/camelcase v1.0.0 // indirect
	github.com/fsnotify/fsnotify v1.6.0 // indirect
	github.com/gabriel-vasile/mimetype v1.4.2 // indirect
	github.com/go-gl/glfw/v3.3/glfw v0.0.0-20221017161538-93cebf72946b // indirect
	github.com/go-gl/mathgl v1.0.0 // indirect
	github.com/goki/freetype v1.0.1 // indirect
	github.com/goki/go-difflib v1.2.1 // indirect
	github.com/goki/gosl v1.0.13 // indirect
	github.com/goki/ki v1.1.15 // indirect
	github.com/goki/kigen v1.0.2 // indirect
	github.com/goki/mat32 v1.0.15 // indirect
	github.com/goki/pi v1.0.27 // indirect
	github.com/goki/prof v1.0.0 // indirect
	github.com/goki/vci v1.0.1 // indirect
	github.com/goki/vgpu v1.0.33 // indirect
	github.com/goki/vulkan v1.0.6 // indirect
	github.com/gorilla/css v1.0.0 // indirect
	github.com/h2non/filetype v1.1.3 // indirect
	github.com/iancoleman/strcase v0.2.0 // indirect
	github.com/jinzhu/copier v0.3.5 // indirect
	github.com/mitchellh/go-homedir v1.1.0 // indirect
	github.com/srwiley/rasterx v0.0.0-20220730225603-2ab79fcdd4ef // indirect
	github.com/srwiley/scanx v0.0.0-20190309010443-e94503791388 // indirect
	golang.org/x/exp v0.0.0-20230321023759-10a507213a29 // indirect
	golang.org/x/image v0.6.0 // indirect
	golang.org/x/mod v0.9.0 // indirect
	golang.org/x/net v0.8.0 // indirect
	golang.org/x/sys v0.6.0 // indirect
	golang.org/x/text v0.8.0 // indirect
	golang.org/x/tools v0.7.0 // indirect
)

**Comment by kkoreilly** [comment]
You should try using TDM-GCC instead of Mingw-w64 GCC, as linked here: https://goki.dev/docs/gi/gettingstarted/#windows

**Comment by lnhks** [comment]
TDM-GCC is used instead, but the same error occurres :(

**Comment by lnhks** [comment]
I'm sorry to waste your time a lot. It's my fault,  I set the CGO_ENABLED to 0 sometime, it won't use any C Compiler. After CGO_ENABLED=1, everything is OK !
/>go env -w CGO_ENABLED=1
(no in WSL)/>go build -v
gitest.exe 45.6 MB
run a small window  appear

**Comment by kkoreilly** [comment]
No problem, it's great that it works! I will more clearly document that CGO is required and must be enabled.
