### ISSUE TITLE
ConfigParts strategy

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#558]
Currently, ConfigParts is called in Layout2D, because it requires settings from Style2D called before.  This means that Parts don't exist when the global style function is called.  We need to break this cycle.

Kai's suggestion: Anything that affects which parts are created ("structural" / "functional" parameters), must be set as a field / flag parameter on the object _when it is created / initially configured_ by the user's code -- not as style Props which are being demoted anyway.

Then, ConfigParts is moved to Init2D, so everything is available for styling in Style2D.

**Comment by kkoreilly** [comment]
We now call `ConfigWidget` automatically when the scene is shown, and properties are set directly on objects the user.
