### ISSUE TITLE
Crash again with cursor move in GoGi Editor window

### ISSUE THREAD

**Issue by thazy** [goki/gi#56]
After playing with the sliders and scrollbars I went back to GoGi Editor window and sequentially selected slider1, slider2, scrollbar1, etc. in the WinVp tree.  At some point a cursor move in the edit window (on right) caused a crash.  Terminal output below starts with playing with the sliders, etc. in the widgets window.

...
Received slider signal: SliderReleased from slider: slider1 with data: 0.5
Received slider signal: SliderPressed from slider: slider2 with data: 0.59404325
Received slider signal: SliderReleased from slider: slider2 with data: 0.0032639739
Received slider signal: SliderValueChanged from slider: slider2 with data: 0.0032639739
Received scrollbar signal: SliderPressed from scrollbar: scrollbar2 with data: 0.5120658
Received scrollbar signal: SliderReleased from scrollbar: scrollbar2 with data: 0.4564935
Received scrollbar signal: SliderValueChanged from scrollbar: scrollbar2 with data: 0.4564935
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x42dfbad]

goroutine 51 [running]:
image.(*RGBA).Bounds(...)
	/usr/local/Cellar/go/1.10.3/libexec/src/image/image.go:72
github.com/goki/gi.(*Viewport2D).ComputeBBox2D(0xc4375aa000, 0x0, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffffa8)
	/Users/thazy/go/src/github.com/goki/gi/viewport2d.go:316 +0x2d
github.com/goki/gi.(*WidgetBase).Move2DBase(0xc4375aa000, 0x0, 0xffffffffffffffa8, 0x0, 0x0, 0x0, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/widget.go:370 +0xf1
github.com/goki/gi.(*Viewport2D).Move2D(0xc4375aa000, 0x0, 0xffffffffffffffa8, 0x0, 0x0, 0x0, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/viewport2d.go:390 +0x6d
github.com/goki/gi.(*Node2DBase).Move2DChildren(0xc42e64bb00, 0x0, 0xffffffffffffffa8)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:558 +0x152
github.com/goki/gi.(*WidgetBase).Move2D(0xc42e64bb00, 0x0, 0xffffffffffffffa8, 0x0, 0x0, 0x0, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/widget.go:375 +0x8f
github.com/goki/gi.(*Node2DBase).Move2DChildren(0xc42de5aa08, 0x0, 0xffffffffffffffa8)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:558 +0x152
github.com/goki/gi.(*Layout).Move2D(0xc42de5aa08, 0x0, 0xffffffffffffffa8, 0x33e, 0x11a, 0x9de, 0x781)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1619 +0xd3
github.com/goki/gi.(*PartsWidgetBase).Move2D(0xc42de5a600, 0x0, 0xffffffffffffffa8, 0x33e, 0x11a, 0x9de, 0x781)
	/Users/thazy/go/src/github.com/goki/gi/widget.go:755 +0xed
github.com/goki/gi.(*Node2DBase).Move2DChildren(0xc429302500, 0x0, 0xffffffffffffffa8)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:558 +0x152
github.com/goki/gi.(*Layout).Move2D(0xc429302500, 0x0, 0x0, 0x32e, 0xdf, 0xa19, 0x791)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1619 +0xd3
github.com/goki/gi.(*WidgetBase).Move2DTree(0xc429302500)
	/Users/thazy/go/src/github.com/goki/gi/widget.go:391 +0x185
github.com/goki/gi.(*Layout).SetScroll.func1(0x4629220, 0xc429302500, 0x462af20, 0xc42e804000, 0x0, 0x44c64c0, 0xc4289ea3c8)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1097 +0x8c
github.com/goki/ki.(*Signal).Emit(0xc42e805af8, 0x462af20, 0xc42e804000, 0x0, 0x44c64c0, 0xc4289ea3c8)
	/Users/thazy/go/src/github.com/goki/ki/signal.go:157 +0x1b6
github.com/goki/gi.(*SliderBase).SetValueAction(0xc42e804000, 0x42b00000)
	/Users/thazy/go/src/github.com/goki/gi/sliders.go:269 +0xd6
github.com/goki/gi.(*Layout).ScrollDelta(0xc429302500, 0x0, 0xffffffffffffffff, 0x462a0a0)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1167 +0xcd
github.com/goki/gi.(*Layout).LayoutScrollEvents.func1(0x4629220, 0xc429302500, 0x462de40, 0xc420412d80, 0x3, 0x454ea20, 0xc4202e0000)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1488 +0x9b
github.com/goki/gi.(*WinEventRecv).Call(0xc430ee5dd0, 0x462de40, 0xc420412d80, 0x3, 0x454ea20, 0xc4202e0000)
	/Users/thazy/go/src/github.com/goki/gi/window.go:1081 +0x6d
github.com/goki/gi.(*Window).SendEventSignal(0xc420412d80, 0x4622da0, 0xc4202e0000, 0x2600701)
	/Users/thazy/go/src/github.com/goki/gi/window.go:1195 +0xc65
github.com/goki/gi.(*Window).EventLoop(0xc420412d80)
	/Users/thazy/go/src/github.com/goki/gi/window.go:960 +0xd5a
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/thazy/go/src/github.com/goki/gi/window.go:438 +0x3f
thazy@econ1-190-172-dhcp ~/go/src/github.com/goki/gi/examples/widgets$

**Comment by rcoreilly** [comment]
I added a guard -- please re-open if it happens again.
