### ISSUE TITLE
Fix margin and box shadow rendering for popups

### ISSUE THREAD

**Issue by kkoreilly** [goki/gi#571]
Margin must always render as transparent and box shadow must always render, regardless of the circumstances. This does not happen on popups because it is rendering within its own limited container, so it renders the margin as a solid color and doesn't render box shadow if it goes outside of the margin.

**Comment by rcoreilly** [comment]
effective margin = max(box shadow, margin)

**Comment by kkoreilly** [comment]
The same issues with margin affect things like frames that also render within their own area. We somehow need to inherit the background color from the surrounding context inside of the margin if things are not already rendered there by another element.

**Comment by rcoreilly** [comment]
Anything that will have a box shadow in some state-dependent, dynamic style case, _must_ reserve the appropriate space for this box shadow by allocating a margin in its base style.

Also, this margin must actually be available for rendering the box shadow, otherwise, what's the point??
