### ISSUE TITLE
Better tab closing

### ISSUE THREAD

**Issue by kkoreilly** [goki/gi#574]
The close button should be located on the right side of the tab and should be clickable without first navigating to the tab.

**Comment by rcoreilly** [comment]
You at least need to preserve an option for only having close on active tabs -- I really appreciate this feature and have many times been glad it works this way (and upset that other systems don't, when I accidentally close a tab that I was trying to switch to).  Once the tab is selected, it is clear that you only want to delete if you click on the active tab close button.

**Comment by kkoreilly** [comment]
There will be an option in user preferences (OnlyCloseActiveTab), with the default being false.
