### ISSUE TITLE
crash - open multidimensional table

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#59]
Steps -
- open gogi editor
- expand widgets->parts->label
- click on StateStyles

Also happens for other multidim tableviews

Johns-Mac-Pro:~/go/src/github.com/goki/gi/examples/widgets $ go run widgets.go 
Received button signal: ButtonPressed from button: button2
Received button signal: ButtonReleased from button: button2
Received button signal: ButtonClicked from button: button2
GiEditor: Tree changed with signal: NodeSignalUpdated
2018/08/25 08:47:51 TableView requires that you pass a pointer to a slice of struct elements -- ptr doesn't point to a slice: [3]gi.Style
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x439f64c]

goroutine 56 [running]:
github.com/goki/gi/giv.(*TableView).TableViewEvents(0xc429a52000)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/tableview.go:1716 +0xfc
github.com/goki/gi/giv.(*TableView).Render2D(0xc429a52000)
	/Users/rohrlich/go/src/github.com/goki/gi/giv/tableview.go:828 +0x71
github.com/goki/gi.(*Layout).Render2DChildren(0xc429a48a00)
	/Users/rohrlich/go/src/github.com/goki/gi/layout.go:1208 +0x99
github.com/goki/gi.(*Frame).Render2D(0xc429a48a00)
	/Users/rohrlich/go/src/github.com/goki/gi/frame.go:149 +0x89
github.com/goki/gi.(*Node2DBase).Render2DChildren(0xc429a3e000)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:599 +0x8e
github.com/goki/gi.(*Viewport2D).Render2D(0xc429a3e000)
	/Users/rohrlich/go/src/github.com/goki/gi/viewport2d.go:410 +0x6a
github.com/goki/gi.(*Node2DBase).Render2DTree(0xc429a3e000)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:560 +0x82
github.com/goki/gi.(*Node2DBase).FullRender2DTree(0xc429a3e000)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:472 +0x89
github.com/goki/gi.(*Window).FullReRender(0xc429a62000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:501 +0x4f
github.com/goki/gi.(*Window).EventLoop(0xc429a62000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:926 +0x678
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:440 +0x3f
exit status 2

**Comment by rcoreilly** [comment]
now works correctly -- one too many "elem()" in there..
