### ISSUE TITLE
Add Undo package using general-purpose diff records

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#6]
* undo sub-package within gi
* use diff package (prob this: https://github.com/sergi/go-diff) on top of json outputs, as in emergent diffmgr
	+ map of diff records for each top-level entity -- can be many of these in parallel (e.g., textfield vs. ki tree etc)
	+ records themselves are sequential slices of diff records and commands, with same logic as emergent
	+ diffing happens in separate routine..

**Comment by rcoreilly** [comment]
this is the more appropriate lib for this purpose: https://github.com/pmezard/go-difflib/difflib -- using in textbuf

**Comment by kkoreilly** [comment]
@rcoreilly, you have made an undo subpackage in gi and a fork of go-difflib ([goki/go-difflib](https://github.com/goki/go-difflib)), and you use the go-difflib fork but don't seem to use the undo package anywhere. Can this issue be closed and/or the undo subpackage removed?

**Comment by rcoreilly** [comment]
undo is used in grid.
