### ISSUE TITLE
Probably best to only allow one preference window and stack multiple gogi editor windows (see comments)

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#60]
![screen shot 2018-08-25 at 9 15 17 am](https://user-images.githubusercontent.com/22350787/44619642-84dcb000-a847-11e8-9ffa-6af423d322f9.png)

**Comment by rcoreilly** [comment]
can't replicate -- just opened and closed a bunch..

**Comment by rohrlich** [comment]
I didn't realize multiple windows were being opened for prefs because they lay on top of each. The window menu was correct! Suggest that we limit to one pref window and bring to front if someone asks for prefs window. The gogi editor I can see having multiple for different objects but they should cascade or something so you can see that there is more than one.

**Comment by rcoreilly** [comment]
good ideas -- done.
