### ISSUE TITLE
Consider renaming AddNew* functions to New*

### ISSUE THREAD

**Issue by kkoreilly** [goki/gi#601]
For example, `gi.NewButton` instead of `gi.AddNewButton`. They are named this way because they create a new object and add it to a parent. However, I believe that the distinction between the creation and addition of an object is less important than conciseness in this case. This is because these functions are called everywhere and it is plenty clear that the object is also being added, as the parent is passed to the function and the documentation states the object is added. Also, we have almost no functions that create a `ki.Node` and don't add it to a parent, so there shouldn't be much confusion. The question is whether having a nicer name is worth a small decrease in clarity and breaking changes (although we are probably doing v2 anyway, and it would be very easy to write a `goki fix` that fixes the function names).

**Comment by rcoreilly** [comment]
done in v2
