### ISSUE TITLE
Consider changing structure to configure parts once instead of on every render

### ISSUE THREAD

**Issue by kkoreilly** [goki/gi#613]
We could just call the `ConfigParts` method in `AddNew`. If there are ever changes made to the configuration after initialization, whoever does that can call `ConfigParts` manually. This could have large performance benefits. This would require passing an anonymous function to all `AddNew` calls that would do custom configuration at the right time, before `ConfigParts` is called.

**Comment by rcoreilly** [comment]
done in new V2
