### ISSUE TITLE
The gi3d sample crashed

### ISSUE THREAD

**Issue by epowsal** [goki/gi#617]
Exception 0xc0000005 0x0 0x104 0x7fff1cba6f5f
PC=0x7fff1cba6f5f
signal arrived during external code execution

runtime.cgocall(0xe0d640, 0xc000bc5100)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/cgocall.go:157 +0x4a fp=0xc000bc50d8 sp=0xc000bc50a0 pc=0x1752ca
github.com/goki/vulkan._Cfunc_callVkCmdDrawIndexed(0x1b438cf41d0, 0x6, 0x1, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:7746 +0x4e fp=0xc000bc5100 sp=0xc000bc50d8 pc=0x51dc6e
github.com/goki/vulkan.CmdDrawIndexed.func1(0x1b438cf41d0, 0x39211120?, 0x1b4?, 0x13f6bc0?, 0x0?, 0x2301001?)
        M:/work/code/go/src/github.com/goki/vulkan/vulkan.go:1043 +0x85 fp=0xc000bc5148 sp=0xc000bc5100 pc=0x555265
github.com/goki/vulkan.CmdDrawIndexed(0x1b438cf41d0, 0x39211120?, 0x1b4?, 0x2301060?, 0xc0?, 0x4?)
        M:/work/code/go/src/github.com/goki/vulkan/vulkan.go:1043 +0x1e fp=0xc000bc5178 sp=0xc000bc5148 pc=0x55517e
github.com/goki/vgpu/vgpu.(*Pipeline).DrawVertex(0xc0001fce00, 0x5?, 0x1b438d13080?)
        M:/work/code/go/src/github.com/goki/vgpu/vgpu/pipeline.go:426 +0x313 fp=0xc000bc5248 sp=0xc000bc5178 pc=0x596453
github.com/goki/vgpu/vgpu.(*Pipeline).BindDrawVertex(0xc0001fce00, 0xc0036debd0?, 0x15a31d6?)
        M:/work/code/go/src/github.com/goki/vgpu/vgpu/pipeline.go:439 +0x4b fp=0xc000bc5280 sp=0xc000bc5248 pc=0x59650b
github.com/goki/vgpu/vphong.(*Phong).RenderTexture(0xc000383340)
        M:/work/code/go/src/github.com/goki/vgpu/vphong/texture.go:200 +0x1b2 fp=0xc000bc52e0 sp=0xc000bc5280 pc=0x7880f2
github.com/goki/vgpu/vphong.(*Phong).Render(0xc000383340)
        M:/work/code/go/src/github.com/goki/vgpu/vphong/vphong.go:118 +0x93 fp=0xc000bc5310 sp=0xc000bc52e0 pc=0x7884b3
github.com/goki/gi/gi3d.(*Solid).Render3D(0xc0034fed80, 0xc000382a00)
        M:/work/code/go/src/github.com/goki/gi/gi3d/solid.go:209 +0xfe fp=0xc000bc5340 sp=0xc000bc5310 pc=0xcfcf5e
github.com/goki/gi/gi3d.(*Embed2D).Render3D(0x13bbe00?, 0xc0003c78c0?)
        <autogenerated>:1 +0x25 fp=0xc000bc5360 sp=0xc000bc5340 pc=0xd29ae5
github.com/goki/gi/gi3d.(*Scene).Render3D(0xc000382a00, 0x0)
        M:/work/code/go/src/github.com/goki/gi/gi3d/render.go:392 +0x43d fp=0xc000bc5588 sp=0xc000bc5360 pc=0xcf587d
github.com/goki/gi/gi3d.(*Scene).RenderImpl(0xc000382a00, 0xb0?)
        M:/work/code/go/src/github.com/goki/gi/gi3d/render.go:301 +0x74 fp=0xc000bc55b0 sp=0xc000bc5588 pc=0xcf5294
github.com/goki/gi/gi3d.(*Scene).Render(0xc000382a00)
        M:/work/code/go/src/github.com/goki/gi/gi3d/render.go:264 +0x21e fp=0xc000bc58d0 sp=0xc000bc55b0 pc=0xcf4f5e
github.com/goki/gi/gi3d.(*Scene).Render2D(0xc000382a00)
        M:/work/code/go/src/github.com/goki/gi/gi3d/scene.go:403 +0x9b fp=0xc000bc5928 sp=0xc000bc58d0 pc=0xcf75fb
github.com/goki/gi/gi.(*Layout).Render2DChildren(0xc003c43800?)
        M:/work/code/go/src/github.com/goki/gi/gi/layout.go:605 +0x88 fp=0xc000bc5968 sp=0xc000bc5928 pc=0x7b5f28
github.com/goki/gi/gi.(*Layout).Render2D(0xc003c43800)
        M:/work/code/go/src/github.com/goki/gi/gi/layout.go:1299 +0x10a fp=0xc000bc59a0 sp=0xc000bc5968 pc=0x7b8d2a
github.com/goki/gi/gi3d.(*SceneView).Render2D(0x2fda038?)
        <autogenerated>:1 +0x25 fp=0xc000bc59b8 sp=0xc000bc59a0 pc=0xd393e5
github.com/goki/gi/gi.(*Layout).Render2DChildren(0xc003c43100?)
        M:/work/code/go/src/github.com/goki/gi/gi/layout.go:605 +0x88 fp=0xc000bc59f8 sp=0xc000bc59b8 pc=0x7b5f28
github.com/goki/gi/gi.(*Layout).Render2D(0xc003c43100)
        M:/work/code/go/src/github.com/goki/gi/gi/layout.go:1299 +0x10a fp=0xc000bc5a30 sp=0xc000bc59f8 pc=0x7b8d2a
github.com/goki/gi/gi.(*Layout).Render2DChildren(0xc003c41c00?)
        M:/work/code/go/src/github.com/goki/gi/gi/layout.go:605 +0x88 fp=0xc000bc5a70 sp=0xc000bc5a30 pc=0x7b5f28
github.com/goki/gi/gi.(*Frame).Render2D(0xc003c41c00)
        M:/work/code/go/src/github.com/goki/gi/gi/frame.go:133 +0xfc fp=0xc000bc5aa8 sp=0xc000bc5a70 pc=0x7ad01c
github.com/goki/gi/gi.(*Layout).Render2DChildren(0xc003c40700?)
        M:/work/code/go/src/github.com/goki/gi/gi/layout.go:605 +0x88 fp=0xc000bc5ae8 sp=0xc000bc5aa8 pc=0x7b5f28
github.com/goki/gi/gi.(*Layout).Render2D(0xc003c40700)
        M:/work/code/go/src/github.com/goki/gi/gi/layout.go:1299 +0x10a fp=0xc000bc5b20 sp=0xc000bc5ae8 pc=0x7b8d2a
github.com/goki/gi/gi.(*Node2DBase).Render2DChildren(0xc0002ea800?)
        M:/work/code/go/src/github.com/goki/gi/gi/node2d.go:901 +0x71 fp=0xc000bc5b58 sp=0xc000bc5b20 pc=0x7c8d31
github.com/goki/gi/gi.(*Viewport2D).Render2D(0xc0002ea800)
        M:/work/code/go/src/github.com/goki/gi/gi/viewport.go:704 +0x51 fp=0xc000bc5b70 sp=0xc000bc5b58 pc=0x7ef1f1
github.com/goki/gi/gi.(*Node2DBase).Render2DTree(0xc0002ea800?)
        M:/work/code/go/src/github.com/goki/gi/gi/node2d.go:862 +0x67 fp=0xc000bc5ba0 sp=0xc000bc5b70 pc=0x7c89a7
github.com/goki/gi/gi.(*Node2DBase).FullRender2DTree(0xc0002ea800)
        M:/work/code/go/src/github.com/goki/gi/gi/node2d.go:725 +0x5d fp=0xc000bc5bc8 sp=0xc000bc5ba0 pc=0x7c801d
github.com/goki/gi/gi.(*Viewport2D).FullRender2DTree(0xc0002ea800?)
        M:/work/code/go/src/github.com/goki/gi/gi/viewport.go:624 +0xd4 fp=0xc000bc5c28 sp=0xc000bc5bc8 pc=0x7ee9b4
github.com/goki/gi/gi.(*Viewport2D).UpdateNodes(0xc0002ea800)
        M:/work/code/go/src/github.com/goki/gi/gi/viewport.go:898 +0x537 fp=0xc000bc5cd0 sp=0xc000bc5c28 pc=0x7f0777
github.com/goki/gi/gi.(*Viewport2D).NodeUpdated(0xc0002ea800?, {0x2ff58d8?, 0xc000382a00?}, 0xc0049a2380?, {0x13d37e0?, 0xc0021e65a0?})
        M:/work/code/go/src/github.com/goki/gi/gi/viewport.go:810 +0x165 fp=0xc000bc5d78 sp=0xc000bc5cd0 pc=0x7ef8a5
github.com/goki/gi/gi.SignalViewport2D({0x2fd8730?, 0xc0002ea800?}, {0x2fd9d70?, 0xc000382a00?}, 0x0?, {0x13d37e0, 0xc0021e65a0})
        M:/work/code/go/src/github.com/goki/gi/gi/viewport.go:764 +0x288 fp=0xc000bc5e48 sp=0xc000bc5d78 pc=0x7ef6a8
github.com/goki/ki/ki.(*Signal).Emit(0xc000382a48, {0x2fd9d70, 0xc000382a00}, 0x0?, {0x13d37e0, 0xc0021e65a0})
        M:/work/code/go/src/github.com/goki/ki/ki/signal.go:177 +0x1f9 fp=0xc000bc5f18 sp=0xc000bc5e48 pc=0x31b3b9
github.com/goki/ki/ki.(*Node).UpdateEnd(0xc000382a00, 0x70?)
        M:/work/code/go/src/github.com/goki/ki/ki/node.go:1418 +0x133 fp=0xc000bc5f88 sp=0xc000bc5f18 pc=0x316bd3
main.(*Anim).Animate(0xc003790fa0)
        M:/work/code/go/src/github.com/goki/gi/examples/gi3d/gi3d.go:136 +0x1b0 fp=0xc000bc5fc8 sp=0xc000bc5f88 pc=0xe09d90
main.(*Anim).Start.func1()
        M:/work/code/go/src/github.com/goki/gi/examples/gi3d/gi3d.go:80 +0x26 fp=0xc000bc5fe0 sp=0xc000bc5fc8 pc=0xe099e6
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000bc5fe8 sp=0xc000bc5fe0 pc=0x1db741
created by main.(*Anim).Start
        M:/work/code/go/src/github.com/goki/gi/examples/gi3d/gi3d.go:80 +0xc5

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xe255d0, 0xc004309e88)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/cgocall.go:157 +0x4a fp=0xc004309e60 sp=0xc004309e28 pc=0x1752ca
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwWaitEventsTimeout(0x3fc999999999999a)
        _cgo_gotypes.go:2487 +0x4e fp=0xc004309e88 sp=0xc004309e60 pc=0x565fce
github.com/go-gl/glfw/v3.3/glfw.WaitEventsTimeout(0xc004309f00?)
        M:/work/code/go/src/github.com/go-gl/glfw/v3.3/glfw/window.go:994 +0x1e fp=0xc004309eb0 sp=0xc004309e88 pc=0x56f3de
github.com/goki/gi/oswin/driver/vkos.(*appImpl).mainLoop(0x131e360)
        M:/work/code/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:164 +0x12c fp=0xc004309f30 sp=0xc004309eb0 pc=0xd4d8ac
github.com/goki/gi/oswin/driver/vkos.Main(0xe25a20?)
        M:/work/code/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:81 +0x91 fp=0xc004309f48 sp=0xc004309f30 pc=0xd4d391
github.com/goki/gi/oswin/driver.driverMain(...)
        M:/work/code/go/src/github.com/goki/gi/oswin/driver/driver_vkos.go:20
github.com/goki/gi/oswin/driver.Main(...)
        M:/work/code/go/src/github.com/goki/gi/oswin/driver/driver.go:27
github.com/goki/gi/gimain.Main(0x2e24a40)
        M:/work/code/go/src/github.com/goki/gi/gimain/gimain.go:31 +0x57 fp=0xc004309f68 sp=0xc004309f48 pc=0xe09737
main.main()
        M:/work/code/go/src/github.com/goki/gi/examples/gi3d/gi3d.go:27 +0x25 fp=0xc004309f80 sp=0xc004309f68 pc=0xe098a5
runtime.main()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:250 +0x1f7 fp=0xc004309fe0 sp=0xc004309f80 pc=0x1accb7
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc004309fe8 sp=0xc004309fe0 pc=0x1db741

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc00006bfb0 sp=0xc00006bf90 pc=0x1ad0d6
runtime.goparkunlock(...)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:387
runtime.forcegchelper()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:305 +0xb2 fp=0xc00006bfe0 sp=0xc00006bfb0 pc=0x1acef2
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006bfe8 sp=0xc00006bfe0 pc=0x1db741
created by runtime.init.6
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x399ba01?, 0x0?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc00006df80 sp=0xc00006df60 pc=0x1ad0d6
runtime.goparkunlock(...)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgcsweep.go:319 +0xde fp=0xc00006dfc8 sp=0xc00006df80 pc=0x195cbe
runtime.gcenable.func1()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:178 +0x26 fp=0xc00006dfe0 sp=0xc00006dfc8 pc=0x18ae86
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006dfe8 sp=0xc00006dfe0 pc=0x1db741
created by runtime.gcenable
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00003e0e0?, 0x2fafba0?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc00007df70 sp=0xc00007df50 pc=0x1ad0d6
runtime.goparkunlock(...)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x399d720)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc00007dfa0 sp=0xc00007df70 pc=0x193b73
runtime.bgscavenge(0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc00007dfc8 sp=0xc00007dfa0 pc=0x194185
runtime.gcenable.func2()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:179 +0x26 fp=0xc00007dfe0 sp=0xc00007dfc8 pc=0x18ae26
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00007dfe8 sp=0xc00007dfe0 pc=0x1db741
created by runtime.gcenable
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0xc001d88c10?, 0x0?, 0x20?, 0x1000000010?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc00006fe28 sp=0xc00006fe08 pc=0x1ad0d6
runtime.runfinq()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mfinal.go:193 +0x107 fp=0xc00006ffe0 sp=0xc00006fe28 pc=0x189ee7
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00006ffe8 sp=0xc00006ffe0 pc=0x1db741
created by runtime.createfing
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mfinal.go:163 +0x45

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc00007ff50 sp=0xc00007ff30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc00007ffe0 sp=0xc00007ff50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00007ffe8 sp=0xc00007ffe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc000079f50 sp=0xc000079f30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc000079fe0 sp=0xc000079f50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000079fe8 sp=0xc000079fe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc00007bf50 sp=0xc00007bf30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc00007bfe0 sp=0xc00007bf50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00007bfe8 sp=0xc00007bfe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc000489f50 sp=0xc000489f30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc000489fe0 sp=0xc000489f50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000489fe8 sp=0xc000489fe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x687cb198cdaa8?, 0x0?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc000485f50 sp=0xc000485f30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc000485fe0 sp=0xc000485f50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000485fe8 sp=0xc000485fe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x687cb198cdaa8?, 0x0?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc00046ff50 sp=0xc00046ff30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc00046ffe0 sp=0xc00046ff50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00046ffe8 sp=0xc00046ffe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x687cb198954b4?, 0x3?, 0x14?, 0x7?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc00048bf50 sp=0xc00048bf30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc00048bfe0 sp=0xc00048bf50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00048bfe8 sp=0xc00048bfe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x687cb198954b4?, 0x3?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc000471f50 sp=0xc000471f30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc000471fe0 sp=0xc000471f50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000471fe8 sp=0xc000471fe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x687cb16d8d85c?, 0x3?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc000487f50 sp=0xc000487f30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc000487fe0 sp=0xc000487f50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000487fe8 sp=0xc000487fe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x39f5260?, 0x1?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc00046bf50 sp=0xc00046bf30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc00046bfe0 sp=0xc00046bf50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00046bfe8 sp=0xc00046bfe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x687cb199c8ca0?, 0x3?, 0x64?, 0x3c?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc00046df50 sp=0xc00046df30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc00046dfe0 sp=0xc00046df50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00046dfe8 sp=0xc00046dfe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x687cb198954b4?, 0x1?, 0x0?, 0x0?, 0x0?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc000477f50 sp=0xc000477f30 pc=0x1ad0d6
runtime.gcBgMarkWorker()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1275 +0xf1 fp=0xc000477fe0 sp=0xc000477f50 pc=0x18cc31
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000477fe8 sp=0xc000477fe0 pc=0x1db741
created by runtime.gcBgMarkStartWorkers
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/mgc.go:1199 +0x25

goroutine 10 [sync.Cond.Wait]:
runtime.gopark(0xc000000002?, 0x0?, 0x88?, 0xac?, 0x100000000000000?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc000bc9b68 sp=0xc000bc9b48 pc=0x1ad0d6
runtime.goparkunlock(...)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:387
sync.runtime_notifyListWait(0xc0007b4098, 0xd)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/sema.go:527 +0x14f fp=0xc000bc9bb0 sp=0xc000bc9b68 pc=0x1d6baf
sync.(*Cond).Wait(0xc000146788?)
        M:/work/tool/go1.20.5.windows-amd64/src/sync/cond.go:70 +0x8c fp=0xc000bc9be8 sp=0xc000bc9bb0 pc=0x1e684c
github.com/goki/gi/oswin/driver/internal/event.(*Deque).NextEvent(0xc0007b4080)
        M:/work/code/go/src/github.com/goki/gi/oswin/driver/internal/event/event.go:55 +0x74 fp=0xc000bc9c38 sp=0xc000bc9be8 pc=0xd4ca54
github.com/goki/gi/oswin/driver/vkos.(*windowImpl).NextEvent(0xc000146600?)
        M:/work/code/go/src/github.com/goki/gi/oswin/driver/vkos/window.go:154 +0x1f fp=0xc000bc9c50 sp=0xc000bc9c38 pc=0xd532df
github.com/goki/gi/gi.(*Window).EventLoop(0xc000146600)
        M:/work/code/go/src/github.com/goki/gi/gi/window.go:1626 +0x5e fp=0xc000bc9ca8 sp=0xc000bc9c50 pc=0x8015de
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc003790fa0?)
        M:/work/code/go/src/github.com/goki/gi/gi/window.go:995 +0x57 fp=0xc000bc9cc0 sp=0xc000bc9ca8 pc=0x7fce37
main.mainrun()
        M:/work/code/go/src/github.com/goki/gi/examples/gi3d/gi3d.go:414 +0x2cf7 fp=0xc000bc9fb0 sp=0xc000bc9cc0 pc=0xe0cad7
github.com/goki/gi/gimain.Main.func1({0xc000479fa6?, 0xc000479fb8?})
        M:/work/code/go/src/github.com/goki/gi/gimain/gimain.go:32 +0x1b fp=0xc000bc9fc0 sp=0xc000bc9fb0 pc=0xe0977b
github.com/goki/gi/oswin/driver/vkos.Main.func1()
        M:/work/code/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:78 +0x2e fp=0xc000bc9fe0 sp=0xc000bc9fc0 pc=0xd55b2e
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000bc9fe8 sp=0xc000bc9fe0 pc=0x1db741
created by github.com/goki/gi/oswin/driver/vkos.Main
        M:/work/code/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:77 +0x85

goroutine 11 [select]:
runtime.gopark(0xc000475f88?, 0x3?, 0x84?, 0xf4?, 0xc000475f62?)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/proc.go:381 +0xd6 fp=0xc000475de8 sp=0xc000475dc8 pc=0x1ad0d6
runtime.selectgo(0xc000475f88, 0xc000475f5c, 0xc00006ff70?, 0x0, 0xe25a20?, 0x1)
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/select.go:327 +0x7be fp=0xc000475f28 sp=0xc000475de8 pc=0x1bcbfe
github.com/goki/gi/oswin/driver/vkos.(*windowImpl).winLoop(0xc0007b4000)
        M:/work/code/go/src/github.com/goki/gi/oswin/driver/vkos/window.go:163 +0xb2 fp=0xc000475fc8 sp=0xc000475f28 pc=0xd533b2
github.com/goki/gi/oswin/driver/vkos.(*appImpl).NewWindow.func4()
        M:/work/code/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:281 +0x26 fp=0xc000475fe0 sp=0xc000475fc8 pc=0xd4e8c6
runtime.goexit()
        M:/work/tool/go1.20.5.windows-amd64/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000475fe8 sp=0xc000475fe0 pc=0x1db741
created by github.com/goki/gi/oswin/driver/vkos.(*appImpl).NewWindow
        M:/work/code/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:281 +0xa18
rax     0x0
rbx     0x1b438cffaa0
rcx     0x0
rdi     0x1b40ad3de00
rsi     0x4000000000000
rbp     0x2cf67ff640
rsp     0x2cf67ff4b0
r8      0x1b40ad3de00
r9      0x1b438cffd00
r10     0x1b438d023b0
r11     0x1b438cf4e80
r12     0x0
r13     0x0
r14     0x0
r15     0x1b439281190
rip     0x7fff1cba6f5f
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

It crashed from current master version in Windows.

**Comment by kkoreilly** [comment]
Thanks for the bug report; this is a duplicate of #536, which I am currently trying to fix.
