### ISSUE TITLE
Demo page goki.dev/demo shows an error

### ISSUE THREAD

**Issue by dc0d** [goki/gi#645]
The demo page returns this error:

```
ReferenceError: can't access lexical declaration 'wasm' before initialization
```

**Comment by kkoreilly** [comment]
Thanks for reporting this. I can not reproduce it in Chrome 119 on macOS; what browser and operating system are you using? Are there any other error messages in the console? Does your browser [support wasm](https://caniuse.com/wasm)?

**Comment by dc0d** [comment]
It has been some time since I have reported an issue 🙂

```
Firefox
Apple M1 Pro - Ventura 13.6.1
```

**Comment by kkoreilly** [comment]
I can reproduce this issue on the latest version of Firefox on Windows. I will fix it now.

**Comment by kkoreilly** [comment]
This issue should be fixed now (by https://github.com/goki/goki/commit/e85579710d1e4cb501cc2b1091f6854d93f583d4). Please let me know if you have any other issues.
