### ISSUE TITLE
crash opening prefs - font file not found

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#66]
Johns-Mac-Pro:~/go/src/github.com/goki/gi/examples/widgets $ go run widgets.go 
gi.FontLib: error accessing path "dog": lstat dog: no such file or directory
2018/08/25 14:19:41 gi.FontLib: error walking the path "dog": lstat dog: no such file or directory
gi.FontLib: error accessing path "": lstat : no such file or directory
2018/08/25 14:19:41 gi.FontLib: error walking the path "": lstat : no such file or directory
2018-08-25 14:19:46.833 widgets[63278:12064936] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSArrayM: 0x5346220> was mutated while being enumerated.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff41b2566b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff68d67942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff41bb513a __NSFastEnumerationMutationHandler + 298
	3   AppKit                              0x00007fff3efff068 recursivelyCollectMenuItemsNeedingKERegistration + 220
	4   AppKit                              0x00007fff3effef3e +[NSMenu(NSKeyEquivalents) _recursivelyRegisterMenuForKeyEquivalentUniquing:] + 64
	5   AppKit                              0x00007fff3effe374 -[NSMenu _setMenuName:] + 965
	6   widgets                             0x0000000004485d12 -[ScreenGLView windowDidBecomeKey:] + 50
	7   CoreFoundation                      0x00007fff41ab65cc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	8   CoreFoundation                      0x00007fff41ab649a _CFXRegistrationPost + 458
	9   CoreFoundation                      0x00007fff41ab61d1 ___CFXNotificationPost_block_invoke + 225
	10  CoreFoundation                      0x00007fff41a74d22 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	11  CoreFoundation                      0x00007fff41a73db3 _CFXNotificationPost + 659
	12  Foundation                          0x00007fff43b9d8c7 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	13  AppKit                              0x00007fff3f154973 -[NSWindow becomeKeyWindow] + 1488
	14  AppKit                              0x00007fff3f153bcd -[NSWindow _changeKeyAndMainLimitedOK:] + 878
	15  AppKit                              0x00007fff3f20127e -[NSWindow _makeKeyRegardlessOfVisibility] + 108
	16  AppKit                              0x00007fff3f156c0c NSPerformVisuallyAtomicChange + 146
	17  AppKit                              0x00007fff3f2011b5 -[NSWindow makeKeyAndOrderFront:] + 90
	18  libdispatch.dylib                   0x00007fff6994c5fa _dispatch_call_block_and_release + 12
	19  libdispatch.dylib                   0x00007fff69944db8 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x00007fff69950395 _dispatch_main_queue_callback_4CF + 1148
	21  CoreFoundation                      0x00007fff41adee59 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x00007fff41aa166a __CFRunLoopRun + 2586
	23  CoreFoundation                      0x00007fff41aa09b7 CFRunLoopRunSpecific + 487
	24  HIToolbox                           0x00007fff40d80d96 RunCurrentEventLoopInMode + 286
	25  HIToolbox                           0x00007fff40d80b06 ReceiveNextEventCommon + 613
	26  HIToolbox                           0x00007fff40d80884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	27  AppKit                              0x00007fff3f031a73 _DPSNextEvent + 2085
	28  AppKit                              0x00007fff3f7c7e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	29  AppKit                              0x00007fff3f026885 -[NSApplication run] + 764
	30  widgets                             0x0000000004058450 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff69aceb66 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4485250, 0xc42077deb0, 0x0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc42077de80 sp=0xc42077de48 pc=0x4004f24
github.com/goki/gi/oswin/driver/macdriver._Cfunc_startDriver()
	_cgo_gotypes.go:639 +0x41 fp=0xc42077deb0 sp=0xc42077de80 pc=0x440e321
github.com/goki/gi/oswin/driver/macdriver.startDriver()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:99 +0x3b fp=0xc42077df10 sp=0xc42077deb0 pc=0x440f23b
github.com/goki/gi/oswin/driver/macdriver.Main(0xc4202f68d0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/macdriver.go:25 +0x36 fp=0xc42077df20 sp=0xc42077df10 pc=0x4409ed6
github.com/goki/gi/oswin/driver.main(0xc4202f68d0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver_darwin.go:20 +0x2b fp=0xc42077df38 sp=0xc42077df20 pc=0x441442b
github.com/goki/gi/oswin/driver.Main(0xc4202f68d0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/driver.go:27 +0x2b fp=0xc42077df50 sp=0xc42077df38 pc=0x44143eb
github.com/goki/gi/gimain.Main(0x45e5b70)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:24 +0x5c fp=0xc42077df70 sp=0xc42077df50 pc=0x447d67c
main.main()
	/Users/rohrlich/go/src/github.com/goki/gi/examples/widgets/widgets.go:22 +0x2d fp=0xc42077df88 sp=0xc42077df70 pc=0x447d7fd
runtime.main()
	/usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc42077dfe0 sp=0xc42077df88 pc=0x402f192
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42077dfe8 sp=0xc42077dfe0 pc=0x4059781

goroutine 5 [semacquire]:
sync.runtime_notifyListWait(0xc4200843a0, 0xc4000000a3)
	/usr/local/go/src/runtime/sema.go:510 +0x10b
sync.(*Cond).Wait(0xc420084390)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/goki/gi/oswin/driver/internal/event.(*Deque).NextEvent(0xc420084388, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/internal/event/event.go:55 +0x72
github.com/goki/gi/oswin/driver/macdriver.(*windowImpl).NextEvent(0xc420084300, 0x12f53da83, 0x4cf9f00)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/window.go:98 +0x33
github.com/goki/gi.(*Window).EventLoop(0xc42041c000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:701 +0x1d9
github.com/goki/gi.(*Window).StartEventLoop(0xc42041c000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:434 +0x2b
main.mainrun()
	/Users/rohrlich/go/src/github.com/goki/gi/examples/widgets/widgets.go:339 +0x40dc
main.main.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/examples/widgets/widgets.go:23 +0x20
github.com/goki/gi/gimain.Main.func1(0x462d620, 0x4cd8660)
	/Users/rohrlich/go/src/github.com/goki/gi/gimain/gimain.go:25 +0x24
github.com/goki/gi/oswin/driver/macdriver.driverStarted.func1()
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:158 +0x40
created by github.com/goki/gi/oswin/driver/macdriver.driverStarted
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:157 +0x60

goroutine 18 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc420084300, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:202 +0x223
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:148 +0xfa

goroutine 56 [select, locked to thread]:
github.com/goki/gi/oswin/driver/macdriver.drawLoop(0xc42042ef00, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:202 +0x223
created by github.com/goki/gi/oswin/driver/macdriver.preparedOpenGL
	/Users/rohrlich/go/src/github.com/goki/gi/oswin/driver/macdriver/cocoa.go:148 +0xfa

goroutine 57 [runnable]:
reflect.Value.Type(0x452b280, 0xc4203ff180, 0x199, 0x452b280, 0xc4203ff180)
	/usr/local/go/src/reflect/value.go:1710 +0x1b0
github.com/goki/ki.FlatFieldsValueFunc(0x4589ba0, 0xc4203ff180, 0xc4268093b0, 0x4589ba0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:927 +0xac
github.com/goki/ki.FlatFieldsValueFunc(0x45900c0, 0xc4203ff180, 0xc4268093b0, 0x45900c0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:943 +0x411
github.com/goki/ki.FlatFieldsValueFunc(0x4595a00, 0xc4203ff180, 0xc4268093b0, 0x41b1909)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:943 +0x411
github.com/goki/ki.(*Node).SetPtrsFmPaths.func1(0x463e800, 0xc4203ff180, 0x1, 0x45966c0, 0xc420236000, 0x1)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1388 +0x6f
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc4203ff180, 0x1, 0x45966c0, 0xc420236000, 0xc42613d940, 0xc426839700)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:998 +0x6b
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc426858000, 0x1, 0x45966c0, 0xc420236000, 0xc42613d940, 0x463e800)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1007 +0x15c
github.com/goki/ki.(*Node).SetPtrsFmPaths(0xc426858000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1387 +0xbf
github.com/goki/ki.(*Node).CopyFrom(0xc426858000, 0x463e0c0, 0xc420222000, 0x44d0e60, 0x4d1cd00)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1278 +0x4f9
github.com/goki/gi/svg.(*Icon).CopyFromIcon(0xc426858000, 0xc420222000)
	/Users/rohrlich/go/src/github.com/goki/gi/svg/icons.go:57 +0x48
github.com/goki/gi/svg.(*IconMgr).SetIcon(0x4d1c4f8, 0xc426847200, 0x45cf4f5, 0x11, 0x0, 0x0)
	/Users/rohrlich/go/src/github.com/goki/gi/svg/icons.go:158 +0xe2
github.com/goki/gi.(*Icon).SetIcon(0xc426847200, 0x45cf4f5, 0x11, 0xc42613d880, 0x1, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/icon.go:68 +0x87
github.com/goki/gi.(*PartsWidgetBase).ConfigPartsSetIconLabel(0xc426839300, 0x45cf4f5, 0x11, 0x0, 0x0, 0x0, 0xffffffffffffffff)
	/Users/rohrlich/go/src/github.com/goki/gi/widget.go:788 +0x93
github.com/goki/gi.(*Action).ConfigPartsButton(0xc426839300)
	/Users/rohrlich/go/src/github.com/goki/gi/action.go:221 +0x284
github.com/goki/gi.(*Action).ConfigParts(0xc426839300)
	/Users/rohrlich/go/src/github.com/goki/gi/action.go:278 +0x189
github.com/goki/gi.(*Action).Init2D(0xc426839300)
	/Users/rohrlich/go/src/github.com/goki/gi/action.go:193 +0x3b
github.com/goki/gi.(*Node2DBase).Init2DTree.func1(0x46303a0, 0xc426839300, 0x8, 0x45a3520, 0xc4261d2000, 0x1)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:487 +0x51
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc426839300, 0x8, 0x45a3520, 0xc4261d2000, 0x45e5320, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:998 +0x6b
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc426828500, 0x8, 0x45a3520, 0xc4261d2000, 0x45e5320, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1007 +0x15c
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc42646a408, 0x7, 0x45a3520, 0xc4261d2000, 0x45e5320, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1007 +0x15c
github.com/goki/ki.(*Node).FuncDownMeFirst.func1(0x46327e0, 0xc42646a408, 0x6, 0x45a3520, 0xc4261d2000, 0xc42646a000)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1003 +0x59
github.com/goki/ki.(*Node).FuncFields(0xc42646a000, 0x6, 0x45a3520, 0xc4261d2000, 0xc426809b38)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:962 +0xe8
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc42646a000, 0x6, 0x45a3520, 0xc4261d2000, 0x45e5320, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1002 +0xee
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc42645e000, 0x5, 0x45a3520, 0xc4261d2000, 0x45e5320, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1007 +0x15c
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc420203600, 0x4, 0x45a3520, 0xc4261d2000, 0x45e5320, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1007 +0x15c
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc426454f00, 0x3, 0x45a3520, 0xc4261d2000, 0x45e5320, 0x0)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1007 +0x15c
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc426454000, 0x2, 0x45a3520, 0xc4261d2000, 0x45e5320, 0xc426454500)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1007 +0x15c
github.com/goki/ki.(*Node).FuncDownMeFirst(0xc4261d2000, 0x1, 0x45a3520, 0xc4261d2000, 0x45e5320, 0xc426809e01)
	/Users/rohrlich/go/src/github.com/goki/ki/node.go:1007 +0x15c
github.com/goki/gi.(*Node2DBase).Init2DTree(0xc4261d2000)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:482 +0x82
github.com/goki/gi.(*Node2DBase).FullRender2DTree(0xc4261d2000)
	/Users/rohrlich/go/src/github.com/goki/gi/node2d.go:468 +0x48
github.com/goki/gi.(*Window).FullReRender(0xc420236000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:501 +0x4f
github.com/goki/gi.(*Window).EventLoop(0xc420236000)
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:926 +0x678
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/rohrlich/go/src/github.com/goki/gi/window.go:440 +0x3f

rax    0x0
rbx    0x7fffa2165380
rcx    0x7ffeefbfda98
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbfdad0
rsp    0x7ffeefbfda98
r8     0x7ffeefbfd960
r9     0x7ffeefbfdb30
r10    0x0
r11    0x206
r12    0x307
r13    0x30
r14    0x6
r15    0x2d
rip    0x7fff69aceb66
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2
Johns-Mac-Pro:~

**Comment by rcoreilly** [comment]
crash looks like it is due to some kind of menu update taking place during some other kind of window update.  I just added a mutex to protect different windows trying to updating the main menu at the same time, but this may require some other kind of protection.  different windows run on different "routines" so there is a potential for conflict there..

**Comment by rcoreilly** [comment]
found another possible source of this and fixed it -- please open a new ticket if it happens again.  hasn't happened to me yet..
