### ISSUE TITLE
Suggest removing Ic (Icon) header text in fileview

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#67]
- looks wierd
- unncessary
- if you click to sort by icon the header text gets misaligned because column is not wide enough  for triangle button and Ic text
- is anyone going to sort by icon?

**Comment by rcoreilly** [comment]
what would go there instead?  seems like it would be inconsistent with general motif over everything having a header.  and spacing alignment needs *something* there.. don't think this is worth fixing..
