### ISSUE TITLE
Convert all remaining uses of MSec to time.Duration

### ISSUE THREAD

**Issue by kkoreilly** [goki/gi#678]
This makes much more sense and provides a much nicer user and programmer experience.

**Comment by khalil-farashiani** [comment]
Hi, I like to work on it. could you pls assign it to me?

**Comment by kkoreilly** [comment]
You can search the code for `MSec` (with match case on) and convert everything using it to `time.Duration` (and get rid of the MSec at the end of the name). The main occurrences are in `gi/settings.go` and in various places in `texteditor/textbuf`.

**Comment by kkoreilly** [comment]
This was implemented in #746.
