### ISSUE TITLE
fileview - path missing completion

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#69]
The file field has completion but the path field doesn't and should

**Comment by rohrlich** [comment]
Easy - but does suggest we go ahead and add icons to the completion menu items (looks like the code for icons on menu items is already in place) so you can tell a file from a folder/directory. We will want these for code completion anyway. Here are examples from GoLand and Xcode
![screen shot 2018-08-25 at 9 10 12 pm](https://user-images.githubusercontent.com/22350787/44624430-0108df00-a8ac-11e8-9d94-99548b21edeb.png)
![screen shot 2018-08-25 at 9 11 42 pm](https://user-images.githubusercontent.com/22350787/44624431-0108df00-a8ac-11e8-8ee9-40e23238fca1.png)

**Comment by rcoreilly** [comment]
done right?
