### ISSUE TITLE
selection/indexing error in fileview (see photos)

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#70]
This occured after adding some favorites (that will be another bug)

![screen shot 2018-08-25 at 2 40 57 pm](https://user-images.githubusercontent.com/22350787/44622411-20d0e080-a875-11e8-8dc3-ff855c79a1ed.png)
![screen shot 2018-08-25 at 2 41 18 pm](https://user-images.githubusercontent.com/22350787/44622412-20d0e080-a875-11e8-8890-3a074bba5ea1.png)

**Comment by rohrlich** [comment]
Notice that the highlighted file is not the one listed in the File: field

**Comment by rcoreilly** [comment]
reopen if you can replicate!
