### ISSUE TITLE
Consider supporting the selection and copying of tooltips

### ISSUE THREAD

**Issue by kkoreilly** [goki/gi#700]
This could sometimes be helpful when there is a lot of useful information in a tooltip.

**Comment by rcoreilly** [comment]
and the need for this should be very rare.  you can always pop it up again if you forget.  when are you ever going to copy it? where?

**Comment by kkoreilly** [comment]
It doesn't seem like this is a useful feature, so I am closing this. If anyone ever has an actual use case for this, it can be reopened.
