### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by 8uff3r** [goki/gi#744]
On linux when I try to build the examples I get the following error:

```
go build -v
goki.dev/gi/v2/gi
# goki.dev/gi/v2/gi
../../gi/mainstage.go:250:3: unknown field Icon in struct literal of type goosi.NewWindowOptions
```
I can build examples of v1.3.25 but not of current version.

**Comment by kkoreilly** [comment]
Apologies for the issue; it will be fixed when I do the next release cycle, which should happen within the next couple of days, but until then you can just use the latest tagged version as you mentioned. After we finish the current period of unstable development and release v2 within the next few months, the main branch should be stable.
