### ISSUE TITLE
Newly created spin box doesn't reflect editor settings after updating; no sustained scroll; 'Enter' moves the window

### ISSUE THREAD

**Issue by thazy** [goki/gi#76]
I created new spin box at end of trow (visible at left side of the picture).  Set minimum and max values and changed icons, but after clicking update none of these are reflected in the widget.  If I enter an appropriate value (e.g., 11) in the 'value' field in editor it does update; and, then in the widgets window the min and max are indeed enforced using the up/down arrows.  ALSO: holding a click on the up/down arrows doesn't keep updating as is customary.  FINALLY: hitting enter to save a value in the new spin box does save, but the whole window is refreshed with the widgets moving around - in some cases moving the spin box out of the window.  

\![img_0160](https://user-images.githubusercontent.com/30027010/44638105-5a3b4600-a972-11e8-9163-b75cdd12373e.JPG)

**Comment by rcoreilly** [comment]
this is presumably either fixed or not relevant at this point..
