### ISSUE TITLE
Crash after hitting 'Update' in GoGi Editor trying to add a 'Scrollbar' widget

### ISSUE THREAD

**Issue by thazy** [goki/gi#78]
In GoGi editor, trying to Add Child under trow; select type Scrollbar; then clicked Update to see what got created in widgets window; crashed.

###

thazy@macbookpro ~/go/src/github.com/goki/gi/examples/widgets$ ./widgets 
Received button signal: ButtonPressed from button: button2
Received button signal: ButtonReleased from button: button2
Received button signal: ButtonClicked from button: button2
GiEditor: Tree changed with signal: NodeSignalUpdated
panic: runtime error: index out of range

goroutine 8 [running]:
github.com/srwiley/scanFT.(*ScannerFT).findCell(0xc420793000, 0xffffffffffffffff)
	/Users/thazy/go/src/github.com/srwiley/scanFT/scan.go:133 +0x28e
github.com/srwiley/scanFT.(*ScannerFT).saveCell(0xc420793000)
	/Users/thazy/go/src/github.com/srwiley/scanFT/scan.go:143 +0x38
github.com/srwiley/scanFT.(*ScannerFT).setCell(0xc420793000, 0x620, 0x7c1)
	/Users/thazy/go/src/github.com/srwiley/scanFT/scan.go:156 +0x39
github.com/srwiley/scanFT.(*ScannerFT).Line(0xc420793000, 0x1f27800018828)
	/Users/thazy/go/src/github.com/srwiley/scanFT/scan.go:288 +0x1f4
github.com/srwiley/rasterx.(*Filler).lineF(0xc4202d5b00, 0x1f27800018828)
	/Users/thazy/go/src/github.com/srwiley/rasterx/fill.go:194 +0x43
github.com/srwiley/rasterx.(*Filler).Line(0xc4202d5b00, 0x1f27800018828)
	/Users/thazy/go/src/github.com/srwiley/rasterx/fill.go:189 +0x3b
github.com/srwiley/rasterx.Path.AddTo(0xc42c1ce000, 0x2a0, 0x400, 0x46323a0, 0xc4202d5b00)
	/Users/thazy/go/src/github.com/srwiley/rasterx/geomx.go:133 +0x98
github.com/goki/gi.(*Paint).fill(0xc42044c430, 0xc42044c430)
	/Users/thazy/go/src/github.com/goki/gi/paint.go:549 +0xfb
github.com/goki/gi.(*Paint).FillPreserve(0xc42044c430, 0xc42044c430)
	/Users/thazy/go/src/github.com/goki/gi/paint.go:583 +0x35
github.com/goki/gi.(*Paint).Fill(0xc42044c430, 0xc42044c430)
	/Users/thazy/go/src/github.com/goki/gi/paint.go:589 +0x35
github.com/goki/gi.(*WidgetBase).RenderStdBox(0xc42012e000, 0xc42012f870)
	/Users/thazy/go/src/github.com/goki/gi/widget.go:610 +0x32f
github.com/goki/gi.(*ScrollBar).Render2DDefaultStyle(0xc42012e000)
	/Users/thazy/go/src/github.com/goki/gi/sliders.go:771 +0x52
github.com/goki/gi.(*ScrollBar).Render2D(0xc42012e000)
	/Users/thazy/go/src/github.com/goki/gi/sliders.go:756 +0x6d
github.com/goki/gi.(*Layout).RenderScrolls(0xc420152500)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1164 +0x59
github.com/goki/gi.(*Layout).Render2D(0xc420152500)
	/Users/thazy/go/src/github.com/goki/gi/layout.go:1640 +0x6d
github.com/goki/gi.(*Node2DBase).Render2DChildren(0xc42044c000)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:599 +0x8e
github.com/goki/gi.(*Viewport2D).Render2D(0xc42044c000)
	/Users/thazy/go/src/github.com/goki/gi/viewport2d.go:410 +0x6a
github.com/goki/gi.(*Node2DBase).Render2DTree(0xc42044c000)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:560 +0x82
github.com/goki/gi.(*Node2DBase).FullRender2DTree(0xc42044c000)
	/Users/thazy/go/src/github.com/goki/gi/node2d.go:472 +0x89
github.com/goki/gi.(*Viewport2D).Init2D.func1(0x463e540, 0xc42044c000, 0x463e540, 0xc42044c000, 0x1, 0x44d7720, 0x4d2ed40)
	/Users/thazy/go/src/github.com/goki/gi/viewport2d.go:275 +0xaa
github.com/goki/ki.(*Signal).Emit(0xc42044c058, 0x463e540, 0xc42044c000, 0x1, 0x44d7720, 0x4d2ed40)
	/Users/thazy/go/src/github.com/goki/ki/signal.go:157 +0x1b6
github.com/goki/ki.(*Node).UpdateSig(0xc42044c000, 0x44d8300)
	/Users/thazy/go/src/github.com/goki/ki/node.go:1156 +0xbb
github.com/goki/gi/giv.(*GiEditor).Update(0xc428827400)
	/Users/thazy/go/src/github.com/goki/gi/giv/gieditor.go:34 +0x42
reflect.Value.call(0x45c3860, 0xc428827400, 0x43213, 0x45cb5ba, 0x4, 0x0, 0x0, 0x0, 0x16, 0xc429fa2000, ...)
	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x45c3860, 0xc428827400, 0x43213, 0x0, 0x0, 0x0, 0xc429fa2000, 0x0, 0x1)
	/usr/local/Cellar/go/1.10.3/libexec/src/reflect/value.go:308 +0xa4
github.com/goki/gi/giv.MethViewCallMeth(0xc4202021c0, 0x0, 0x0, 0x0)
	/Users/thazy/go/src/github.com/goki/gi/giv/methview.go:370 +0x7d
github.com/goki/gi/giv.MethViewCall(0x463e540, 0xc42839c000, 0x4638aa0, 0xc428b53980, 0x0, 0x44c3620, 0xc4202021c0)
	/Users/thazy/go/src/github.com/goki/gi/giv/methview.go:330 +0x1ce
github.com/goki/ki.(*Signal).Emit(0xc428b55210, 0x4638aa0, 0xc428b53980, 0x0, 0x44c3620, 0xc4202021c0)
	/Users/thazy/go/src/github.com/goki/ki/signal.go:157 +0x1b6
github.com/goki/gi.(*Action).ButtonRelease(0xc428b53980)
	/Users/thazy/go/src/github.com/goki/gi/action.go:179 +0x163
github.com/goki/gi.ButtonEvents.func1(0x4638aa0, 0xc428b53980, 0x463ec80, 0xc420254000, 0x0, 0x4559960, 0xc42b0591d0)
	/Users/thazy/go/src/github.com/goki/gi/buttons.go:407 +0xcd
github.com/goki/gi.(*WinEventRecv).Call(0xc42ecf7de0, 0x463ec80, 0xc420254000, 0x0, 0x4559960, 0xc42b0591d0)
	/Users/thazy/go/src/github.com/goki/gi/window.go:1095 +0x6d
github.com/goki/gi.(*Window).SendEventSignal(0xc420254000, 0x4633820, 0xc42b0591d0, 0xf622e01)
	/Users/thazy/go/src/github.com/goki/gi/window.go:1215 +0xcab
github.com/goki/gi.(*Window).EventLoop(0xc420254000)
	/Users/thazy/go/src/github.com/goki/gi/window.go:974 +0xd2b
created by github.com/goki/gi.(*Window).GoStartEventLoop
	/Users/thazy/go/src/github.com/goki/gi/window.go:444 +0x3f
thazy@macbookpro ~/go/src/github.com/goki/gi/examples/widgets$

**Comment by rcoreilly** [comment]
finally one I could replicate and fix!
