### ISSUE TITLE
Attempt to resize widgets window causes black out + beach ball

### ISSUE THREAD

**Issue by thazy** [goki/gi#79]
Grabbed right border of widgets window and pulled right - immediately went black...

![img_0161](https://user-images.githubusercontent.com/30027010/44639688-78a53f80-a97a-11e8-8f81-be6a7bb37052.JPG)

**Comment by rcoreilly** [comment]
weird!  I do this all the time.. replicable?  steps to replicate?  latest build?

**Comment by rcoreilly** [comment]
closing for now until you can replicate..  something got hung somewhere.
