### ISSUE TITLE
Menu button menu - key shortcut not working

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#91]
widgets demo - looks like shift+control and 1 should select the first item and control and 3 the third but neither work.

Also why shift + control for first item?

**Comment by rcoreilly** [comment]
not sure why you're keyboard shortcuts aren't working / reliable -- this has never not worked for me.  shift+control just for testing out different combos.

**Comment by thazy** [comment]
Neither shift + control +1 nor control +3 seems to do anything for me.  I also tried by substituting command for control and still nothing.  Also, I noticed that while Command + (+/-) works for zoom in/out, Control + (+) zooms in, but Control + (-) doesn't seem to do anything.

**Comment by rohrlich** [comment]
Randy - if you can't replicate I can try to debug as I am also having problems with keyFunComplete not getting remapped to Control+Spacebar and other key pref issues.

**Comment by rcoreilly** [comment]
please do!  you can go to window.go, KeyChordEventHiPri (around line 1543) and uncomment the printf there and see what you're actually getting in for every keypress..

**Comment by rohrlich** [comment]
Indeed getting Control+3 but it is mapped to KeyFunNil

Also is there a way to reset prefs? I deleted every mapping from my custom map and now the std map is empty!!!

**Comment by rohrlich** [comment]
Getting "Received menu action data: 3 from menu action: Menu Item 3" so if I understand the code this is all that should happen other than the menu closing. So the latter part is what is not happening.

**Comment by rcoreilly** [comment]
that is all that should happen.  the menu is not opened or closed during the shortcut.  not quite sure what is not happening.

**Comment by rcoreilly** [comment]
This code should have removed all the nil entries.  it should be called during startup... I tested a while ago - I'll test again but if you have any nil's still around, please try and see if you can determine why this wasn't working.

Also, to reset the map, us the StdKeyMap button in prefs toolbar.

```Go
// Update ensures that the given keymap has at least one entry for every
// defined KeyFun, grabbing ones from the default map if not, and also
// eliminates any Nil entries which might reflect out-of-date functions
func (km *KeyMap) Update() {
	for key, val := range *km {
		if val == KeyFunNil {
			log.Printf("KeyMap: key function is nil -- probably renamed, for key: %v\n", key)
			delete(*km, key)
		}
	}
```

**Comment by rohrlich** [comment]
I think the KeyMap Update is working but it seems that none of my key mapping changes stick across save.

As regards the menu shortcut - maybe my assumption is wrong but I thought it would be the same as clicking on the menu item which dismisses the menu.

**Comment by rcoreilly** [comment]
nope keyboard shortcut is an entirely separate keyboard-event only mechanism not tied to the gui menu.

could you dig into that keymap stuff and commit the fix, given that you're in that code and are experiencing the issues?

**Comment by rohrlich** [comment]
Yep, will work on keymap problem tomorrow.

**Comment by rohrlich** [comment]
Works as designed so I'll close but would like to see the shortcut have the same behavior as menu select from mouse click.

For key map issue see #93
