### ISSUE TITLE
Update resetting saved keymap 

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#93]
To reproduce:
- StdKeyMap MacEmacsKeyMap
- CustomKeyMap change Control+Spacebar from selectmode to complete
- close custom map window - reopen - still set to complete
- close again and click Save - reopen - still set to complete
- close again and Update - reopen and set to selectmode

**Comment by rohrlich** [comment]
I've checked in a temporary change - let's discuss at meeting today.

**Comment by rcoreilly** [comment]
all good now?
