### ISSUE TITLE
Keymap usability fixes

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#95]
* keys sub-menu in toolbar and mainmenu
* reset custom keymap (use standard keymap name)
* add "<keyfun> Not Set" keymap name (e.g., SelectAll Not Set if there is no shortcut for SelectAll keyfun) for any not=set functions, instead of using std default
* sort map by either key or function (currently only by key) -- generic slice view sort selector
* save and load keymaps -- also prompt in StdKeyMap function before overwriting any existing custom keymap to save before overwrite.
* SliceViewStyleFun to highlight entries in custom map that are different from standard map.
* still debug why Command+P not working on John and Tom's system!

**Comment by rohrlich** [comment]
I've made the "Not Set" change and when I did I changed the code to always start with a copy of the default mappings as the custom map. Now you can see the mappings even if you have no custom mappings. Suggest we change prefs label "StdKeyMapName" to "KeyMap" and "CustomKeyMap" to "KeyMappings". This would be much clearer to the user and with styling of the key mappings that are custom and the ability to reset to defaults it will all be very clear.

Also, I have thought more about the multiple custom sets and the save/load and I don't think it is worth it. Unlikely that users will be switching key sets on a single computer.

**Comment by rcoreilly** [comment]
* I strongly prefer to NOT have a saved set of keymappings in preferences unless the user has specifically customized them, because we will likely end up adding / changing things and then you end up with a whole set of issues around dealing with the stale settings..
* Could easily allow people to view the standard map instead of creating one.
* If I have invested some time in customizing my key mappings, I'll want to copy those up to my other computers, so saving / loading would be useful I think..

**Comment by rohrlich** [comment]
Some progress
• we now have a prefs entry (name is awful) that lets you see the key mappings for the std key maps. How do I make this inactive and get rid of the "Add" button
* renamed the StdKeyMap button to InitCustomKeyMap
* added ClearCustomKeyMap button to toolbar

**Comment by rohrlich** [comment]
I see now that rather than having the separate var/dialog for viewing the stdkeymap mappings I could just add a button for each map name in the keymapvalueview. Might need to be a new dialog type whereas now it is a SliceViewSelectDialog and I want a SliceViewSelect but with the addition of the button as in the colorview dialog.

**Comment by rcoreilly** [comment]
I think this is all good now -- open more specific ticket if something comes up.
