### ISSUE TITLE
fileview not using Ext field to filter

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#98]
I believe I see the problem so I'll fix

**Comment by rohrlich** [comment]
The filter isn't getting set so that is an easy fix. But, I'm wondering when the filter will get applied if the user edits the extension. Maybe just update the list if the user edits the Ext and leaves that field?

**Comment by rohrlich** [comment]
Hey! Already works that way. I'll commit.

**Comment by rohrlich** [comment]
There is a remaining problem. The value of the Ext variable is not getting save (no '-' in the description field). Always returns to .json

**Comment by rcoreilly** [comment]
couple of things: 

* I really don't like to have my files *filtered* -- I only want to have the relevant ones highlighted.  I find it disconcerting not seeing the files I would expect to see in a directory..  If you really love to have your files filtered, then we could create a preference setting. :)

* whoever calls the fileview dialog in the first place sets the default ext as appropriate for that kind of file.  so it should not be saved.

**Comment by rcoreilly** [comment]
and the - there wouldn't save anyway b/c the fileview object itself is never being saved / loaded anyway..

**Comment by rcoreilly** [comment]
last thing: I habitually put the json:"-" and xml:"-" for all fields that are set dynamically, even when it is not actually relevant in practice, as a kind of hint about the status of that field..

**Comment by rohrlich** [comment]
I'm fine with not filtering and just highlighting. I'll remove the change I made.

- The current style func is coloring the directories and ignoring the extension field

**Comment by rcoreilly** [comment]
I'm not sure why you don't see the highlighting -- has always been working for me..

![screen shot 2018-08-31 at 11 48 24 am](https://user-images.githubusercontent.com/9605819/44928078-f1f2b880-ad13-11e8-9053-26948db60606.png)

**Comment by rohrlich** [comment]
My impression from what you said is that the files with the specified extension (in this case .json) would be styled so they stand out from the .go, .md, etc.

- John


On Aug 31, 2018, at 11:49 AM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure why you don't see the highlighting -- has always been working for me..

[screen shot 2018-08-31 at 11 48 24 am]<https://user-images.githubusercontent.com/9605819/44928078-f1f2b880-ad13-11e8-9053-26948db60606.png>

**Comment by rohrlich** [comment]
Wait! They do in your figure. I’ll check mine again.

- John


On Aug 31, 2018, at 11:53 AM, John Rohrlich <john.rohrlich@colorado.edu<mailto:john.rohrlich@colorado.edu>> wrote:

My impression from what you said is that the files with the specified extension (in this case .json) would be styled so they stand out from the .go, .md, etc.

- John


On Aug 31, 2018, at 11:49 AM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure why you don't see the highlighting -- has always been working for me..

[screen shot 2018-08-31 at 11 48 24 am]<https://user-images.githubusercontent.com/9605819/44928078-f1f2b880-ad13-11e8-9053-26948db60606.png>

**Comment by rohrlich** [comment]
So the problem is that the styling is not getting applied if you change the extension. If the directory has files with the specified extension when first opened then the highlight is applied. The directory I was opening had no .json files. I switched to a directory with .json files and they were highlighted but then I changed the extension to .go and the .json files stayed highlighted. See image.

[cid:A2087076-DD15-4D10-AC94-F8DC18F51DFE@hsd1.co.comcast.net.]
- John


On Aug 31, 2018, at 11:54 AM, John Rohrlich <john.rohrlich@colorado.edu<mailto:john.rohrlich@colorado.edu>> wrote:

Wait! They do in your figure. I’ll check mine again.

- John


On Aug 31, 2018, at 11:53 AM, John Rohrlich <john.rohrlich@colorado.edu<mailto:john.rohrlich@colorado.edu>> wrote:

My impression from what you said is that the files with the specified extension (in this case .json) would be styled so they stand out from the .go, .md, etc.

- John


On Aug 31, 2018, at 11:49 AM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure why you don't see the highlighting -- has always been working for me..

[screen shot 2018-08-31 at 11 48 24 am]<https://user-images.githubusercontent.com/9605819/44928078-f1f2b880-ad13-11e8-9053-26948db60606.png>

**Comment by rohrlich** [comment]
ConfigSliceGrid isn’t calling tv.ConfigSliceGridRows() on update because the caller is passing in force = false.

Suggestions on best way to fix that isn’t as having handed as passing true

- John


On Aug 31, 2018, at 12:02 PM, John Rohrlich <john.rohrlich@colorado.edu<mailto:john.rohrlich@colorado.edu>> wrote:

So the problem is that the styling is not getting applied if you change the extension. If the directory has files with the specified extension when first opened then the highlight is applied. The directory I was opening had no .json files. I switched to a directory with .json files and they were highlighted but then I changed the extension to .go and the .json files stayed highlighted. See image.

<Screen Shot 2018-08-31 at 11.59.01 AM.png>
- John


On Aug 31, 2018, at 11:54 AM, John Rohrlich <john.rohrlich@colorado.edu<mailto:john.rohrlich@colorado.edu>> wrote:

Wait! They do in your figure. I’ll check mine again.

- John


On Aug 31, 2018, at 11:53 AM, John Rohrlich <john.rohrlich@colorado.edu<mailto:john.rohrlich@colorado.edu>> wrote:

My impression from what you said is that the files with the specified extension (in this case .json) would be styled so they stand out from the .go, .md, etc.

- John


On Aug 31, 2018, at 11:49 AM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure why you don't see the highlighting -- has always been working for me..

[screen shot 2018-08-31 at 11 48 24 am]<https://user-images.githubusercontent.com/9605819/44928078-f1f2b880-ad13-11e8-9053-26948db60606.png>

**Comment by rcoreilly** [comment]
seems like force = true is the best?  why not?  this is going to require a full redraw..

**Comment by rohrlich** [comment]
Ok I'll make that change. I didn't look to see what work was being done by the method so it was just a guess that it might be doing a lot that wasn't needed.

**Comment by rcoreilly** [comment]
all good? close if so..
